Repository HumanSignal/label-studio, pull requests merged in 2022-08, with the labels that each got.

#2767 docs: Add video tutorial about pre-annotation import
  docs/source/guide/predictions.md
  docs/themes/htx/source/css/page.styl
Labels: docs

#2516 fix: DEV-2420: Fix overlap change in case of cohort percentage is changed maximum_annotations = 1max
  label_studio/projects/models.py
  label_studio/tests/test_projects.tavern.yml
Labels: fix

#2773 fix: DEV-3058: Change ML url validation flag name
  label_studio/core/settings/base.py
  label_studio/ml/serializers.py
Labels: fix

#2774 fix: DEV-3058: Rename variable to ML_BLOCK_LOCAL_IP
  label_studio/core/settings/base.py
  label_studio/ml/serializers.py
Labels: fix

#2755 docs: DEV-3020: LSE 2.3 feature documents for Pin, Unpin, and Duplica…
  docs/source/guide/manage_users.md
  docs/themes/htx/source/images/click-plus-sign.png
  docs/themes/htx/source/images/created-a-duplicated-project.png
  docs/themes/htx/source/images/delete-workspace.png
  docs/themes/htx/source/images/duplicate-new-project-created.png
  docs/themes/htx/source/images/duplicate-new-project.png
  docs/themes/htx/source/images/duplicate-options-settings.png
  docs/themes/htx/source/images/duplicate-project.png
  docs/themes/htx/source/images/filter-pinned-projects-only.png
  docs/themes/htx/source/images/filter-unpinned-projects-only.png
  docs/themes/htx/source/images/manage-members.png
  docs/themes/htx/source/images/name-the-workspace.png
  docs/themes/htx/source/images/new-project-pinned.png
  docs/themes/htx/source/images/pin-project.png
  docs/themes/htx/source/images/pinned-projects-only.png
  docs/themes/htx/source/images/save-duplicate-project.png
  docs/themes/htx/source/images/select-pinned-projects.png
  docs/themes/htx/source/images/select-unpinned-projects.png
  docs/themes/htx/source/images/settings.png
  docs/themes/htx/source/images/three-dots.png
  docs/themes/htx/source/images/view-all-projects.png
  docs/themes/htx/source/images/view-pinned-projects-only.png
  docs/themes/htx/source/images/view-unpinned-projects-only.png
  docs/themes/htx/source/images/view-unpinned-projects.png
Labels: docs

#2725 fix: DEV-1462: Fix changing label config for repeater tag
  deploy/requirements.txt
  label_studio/core/label_config.py
  label_studio/projects/models.py
  label_studio/tests/test_config_validation.py
Labels: fix

#2307 fix: DEV-2298: Increase long RQ jobs timeout
  label_studio/core/settings/base.py
  label_studio/io_storages/base_models.py
Labels: fix

#2787 fix: DEV-3090: Fix reset after adding or removing labels
  label_studio/projects/models.py
Labels: fix

#2802 ci: DEV-3111: Delete branch after follow merge PR is merged
  .github/workflows/delete_pr_branch.yml
Labels: ci

#2751 fix: DEV-3014: Missing empty body for 204 responses
  label_studio/data_import/api.py
Labels: fix

#2797 fix: Add reset for project summaries in Rename labels
  label_studio/data_manager/actions/experimental.py
Labels: fix

#2613 feat: DEV-2362: Add proxy password to interactive annotations context
  label_studio/ml/api.py
Labels: feat

#2801 fix: DEV-3131: Fix user creating API
  label_studio/tests/users.tavern.yml
  label_studio/users/api.py
Labels: fix

#2816 docs: Fix API validation success code
  label_studio/projects/api.py
Labels: docs

#2810 ci: DEV-3139: Update latest Docker tag
  .github/workflows/docker-release-promote.yml
Labels: ci

#2819 docs: Update docsearch with algolia
  docs/themes/htx/layout/layout.ejs
Labels: docs

#2782 fix: DEV-3089: Disable DTDForbidden for label config validation
  label_studio/core/label_config.py
Labels: fix

#2826 ci: DEV-3135: Case insensitive branch name for FollowMerge PRs
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#2831 docs: Add export all tasks without annotation info
  docs/source/guide/export.md
  docs/themes/htx/source/images/lse-export-snapshots-ui.png
Labels: docs

#2828 fix: DEV-3164: Remove potential data exposure from logs
  label_studio/core/label_config.py
  label_studio/core/utils/contextlog.py
  label_studio/io_storages/all_api.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/s3/utils.py
  label_studio/io_storages/utils.py
  label_studio/ml/models.py
  label_studio/projects/models.py
  label_studio/tasks/models.py
  label_studio/tasks/serializers.py
  label_studio/tasks/validation.py
Labels: fix

#2839 docs: DEV-3153: Adding the LS blog post for 10k github stars
  docs/source/blog/10k-stars-announcement.md
  docs/source/blog/index.html
  docs/themes/htx/source/images/10k-stars-blog/blog-timeline.png
  docs/themes/htx/source/images/10k-stars-blog/thumbnail.png
Labels: docs

#2849 ci: DEV-3236: removing .bash_history file that was accidentally commited to LS
  .bash_history
  .gitignore
Labels: ci

#2840 fix: DEV-3212: Add validation to avoid users import local files using URL
  label_studio/data_import/uploader.py
  label_studio/tests/data_import/__init__.py
  label_studio/tests/data_import/test_uploader.py
Labels: fix

#2824 feat: DEV-3145: Add command for export project in Opensource
  docs/source/guide/export.md
  label_studio/core/argparser.py
  label_studio/data_export/mixins.py
  label_studio/server.py
  label_studio/tasks/functions.py
  label_studio/tests/tasks/__init__.py
  label_studio/tests/tasks/test_functions.py
Labels: feat

#2868 feat: DEV-3031: Add uwsgi and nginx
  .dockerignore
  Dockerfile
  Dockerfile.redhat
  deploy/docker-entrypoint.d/10-copy-static-data.sh
  deploy/docker-entrypoint.d/20-wait-for-db.sh
  deploy/docker-entrypoint.d/30-run-db-migrations.sh
  deploy/docker-entrypoint.sh
  deploy/nginx/default.conf
  deploy/nginx/scripts/10-replace-subpath.sh
  deploy/nginx/scripts/11-replace-ssl-cert.sh
  deploy/requirements.txt
  deploy/uwsgi.ini
  docker-compose.yml
  label_studio/core/current_request.py
  label_studio/core/settings/base.py
  label_studio/core/utils/common.py
  label_studio/core/utils/formatter.py
  label_studio/core/wsgi.py
Labels: feat

#2874 ci: try to use python 3.10
  .github/workflows/bandit.yml
  .github/workflows/build_pypi.yml
  .github/workflows/docker-build.yml
  .github/workflows/docker-release-promote.yml
  .github/workflows/tests.yml
  Dockerfile
Labels: ci

#2876 chore: Remove sentry webpack plugin
  label_studio/frontend/package-lock.json
  label_studio/frontend/package.json
  label_studio/frontend/webpack.config.js
  label_studio/frontend/yarn.lock
Labels: chore

#2871 fix: DEV-2296: Add async tasks deletion
  label_studio/data_manager/actions/basic.py
  label_studio/tasks/models.py
  label_studio/tests/data_manager/test_api_actions.py
Labels: fix

#2858 fix: DEV-3134: Exclude Deactivated / Not Activated users from project dashboards and member assignments lists
  label_studio/core/settings/base.py
  label_studio/organizations/api.py
  label_studio/organizations/mixins.py
  label_studio/organizations/serializers.py
Labels: fix

#2885 docs: Fix URL link to point to LS App
  docs/source/guide/quality.md
Labels: docs
