Repository HumanSignal/label-studio, pull requests merged in 2022-10, with the labels that each got.

#3027 fix: DEV-3430: Adding CreateOnlyFieldsMixin and adding to BaseUserSerializer to make email only writeable on create
  label_studio/core/mixins.py
  label_studio/tests/users.tavern.yml
  label_studio/users/serializers.py
Labels: fix, Confirmed

#3040 feat: New header GitHub stars
  docs/themes/htx/layout/partials/github_stars.ejs
  docs/themes/htx/source/css/header-footer.css
  docs/themes/htx/source/css/page.styl
Labels: feat

#3060 ci: DEV-3525: Add PyPI puller
  .github/workflows/build_pypi.yml
Labels: ci

#3004 docs: Add GIF border for images in labeling page
  docs/source/guide/labeling.md
Labels: docs

#3066 docs: Update api.py
  label_studio/projects/api.py
Labels: docs

#3074 feat: update header css, github stars, cmd block on search
  docs/themes/htx/layout/partials/github_stars.ejs
  docs/themes/htx/layout/partials/header.ejs
  docs/themes/htx/layout/partials/search.ejs
  docs/themes/htx/source/css/header-footer.css
Labels: feat

#3046 fix: DEV-1923: Fix CONLL export tokenization issue with splitting into individual tokens
  deploy/requirements.txt
Labels: fix, Confirmed

#2942 fix: DEV-2915: Fix auth check for uploaded files
  label_studio/core/feature_flags/base.py
  label_studio/data_import/models.py
  label_studio/tasks/models.py
Labels: fix, Confirmed

#3068 docs: Add note insructions to storage page
  docs/source/guide/storage.md
Labels: docs

#3110 feat: DEV-3545: Adding multi-page document annotation in templates gallery
  label_studio/annotation_templates/computer-vision/multipage-documents/config.xml
  label_studio/annotation_templates/computer-vision/multipage-documents/config.yml
  label_studio/core/static/templates/multipage.png
Labels: feat

#2815 docs: DEV-2914: Add swagger docs for AllStorage APIs
  label_studio/io_storages/all_api.py
Labels: docs

#3120 docs: Cleanup and compress multi-page documentation images
  docs/source/templates/index.html
  label_studio/core/static/templates/asr-hypotheses.png
  label_studio/core/static/templates/automatic-speech-recognition-using-segments.png
  label_studio/core/static/templates/automatic-speech-recognition.png
  label_studio/core/static/templates/content-based-image-search.png
  label_studio/core/static/templates/coreference-resolution-and-entity-linking.png
  label_studio/core/static/templates/freeform-metadata.png
  label_studio/core/static/templates/multipage.png
  label_studio/core/static/templates/optical-character-recognition.png
  label_studio/core/static/templates/outliers-anomaly-detection.png
  label_studio/core/static/templates/pairwise-classification.png
  label_studio/core/static/templates/pairwise-regression.png
  label_studio/core/static/templates/repeater-tag-multi-page-document-annotation.png
  label_studio/core/static/templates/response-selection.png
  label_studio/core/static/templates/signal-quality-detection.png
  label_studio/core/static/templates/signal-quality.png
  label_studio/core/static/templates/sound-event-detection.png
  label_studio/core/static/templates/speaker-segmentation.png
  label_studio/core/static/templates/tabular-data.png
  label_studio/core/static/templates/taxonomy.png
  label_studio/core/static/templates/time-series-forecasting.png
Labels: docs

#3105 fix: DEV-3465: Projects, displayed on user's organization page, include other organizations
  label_studio/organizations/api.py
  label_studio/organizations/serializers.py
Labels: fix, Confirmed

#3115 fix: DEV-3303: Fix updating summary on delete annotations
  label_studio/data_manager/actions/basic.py
Labels: fix, Confirmed

#3133 ci: Extend GitLeaks config
  .gitleaks.toml
Labels: ci

#3044 fix: DEV-3478: striping unsafe html from project expert_instruction
  deploy/requirements.txt
  label_studio/constants.py
  label_studio/projects/serializers.py
  label_studio/tests/test_projects.tavern.yml
Labels: fix, Confirmed

#2605 fix: DEV-2792: Add YOLO and VOC export image without bounding box
  deploy/requirements.txt
Labels: fix, Confirmed

#2915 fix: DEV-1904: Fixed source storage duplicating tasks when double click Sync button
  label_studio/core/redis.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/migrations/0010_auto_20221014_1708.py
Labels: fix, Confirmed

#3154 fix: DEV-3669: Fix filename in COCO export
  deploy/requirements.txt
Labels: fix, Confirmed

#3167 Restore missed multipage.png
  label_studio/core/static/templates/multipage.png
Labels: title needs formatting

#3114 fix: DEV-3397: Added session expiration settings and conditions
  label_studio/core/middleware.py
  label_studio/core/settings/base.py
  label_studio/core/settings/label_studio.py
  label_studio/tests/conftest.py
  label_studio/tests/sessions.tavern.yml
  label_studio/users/forms.py
  label_studio/users/functions.py
  label_studio/users/templates/users/user_login.html
  label_studio/users/views.py
Labels: fix, Confirmed
