Repository HumanSignal/label-studio, pull requests merged in 2022-11, with the labels that each got.

#3181 Revert "fix: DEV-3397: Added session expiration settings and conditions"
  label_studio/core/middleware.py
  label_studio/core/settings/base.py
  label_studio/core/settings/label_studio.py
  label_studio/tests/conftest.py
  label_studio/tests/sessions.tavern.yml
  label_studio/users/forms.py
  label_studio/users/functions.py
  label_studio/users/templates/users/user_login.html
  label_studio/users/views.py
Labels: title needs formatting

#3185 fix: DEV-3397: Refactored setting of 'last_login' to reduce repetition
  label_studio/core/middleware.py
  label_studio/core/settings/base.py
  label_studio/core/settings/label_studio.py
  label_studio/tests/conftest.py
  label_studio/tests/sessions.tavern.yml
  label_studio/users/forms.py
  label_studio/users/functions.py
  label_studio/users/templates/users/user_login.html
  label_studio/users/views.py
Labels: fix, Confirmed

#3204 fix: Stop `cmd` key from focusing search input
  docs/themes/htx/layout/partials/search.ejs
Labels: fix

#3216 fix: dev-3718: Checking if user is logged in before continuing to reset session due to session age
  label_studio/core/middleware.py
Labels: fix

#3117 docs: DEV-2937: Update LSF guide
  docs/package-lock.json
  docs/package.json
  docs/source/guide/frontend.md
  docs/source/guide/frontend_reference.md
  docs/source/guide/persistent_storage.md
  docs/themes/htx/source/css/_details.styl
  docs/themes/htx/source/css/index.styl
  docs/themes/htx/source/css/page.styl
  docs/themes/htx/source/images/frontend/lsf-in-ls.jpg
Labels: docs

#2547 feat: DEV-2075: Add mixin to Project to support mechanism to cancel old jobs
  label_studio/core/redis.py
  label_studio/core/settings/base.py
  label_studio/data_import/api.py
  label_studio/data_manager/actions/basic.py
  label_studio/data_manager/actions/experimental.py
  label_studio/data_manager/actions/predictions_to_annotations.py
  label_studio/projects/mixins.py
  label_studio/projects/models.py
Labels: feat, Confirmed

#3165 fix: DEV-3578: Correclty serialize JSON fields in CSV output
  deploy/requirements.txt
Labels: fix

#3239 fix: DEV-3744: Fix task data validation for nested fields with repeater
  label_studio/tasks/validation.py
  label_studio/tests/data_import.repeater.tavern.yml
  label_studio/tests/test_suites/samples/example_repeater.json
Labels: fix, Confirmed

#2888 fix: DEV-3296: Add retry for bulk stats calculation
  label_studio/core/redis.py
  label_studio/core/settings/base.py
  label_studio/tasks/models.py
  label_studio/tests/test_block_objects.py
Labels: fix, Confirmed

#3195 fix: DEV-3668: Add project field to annotation
  label_studio/data_manager/actions/experimental.py
  label_studio/data_manager/actions/predictions_to_annotations.py
  label_studio/projects/api.py
  label_studio/tasks/api.py
  label_studio/tasks/functions.py
  label_studio/tasks/migrations/0029_annotation_project.py
  label_studio/tasks/migrations/0030_auto_20221102_1118.py
  label_studio/tasks/models.py
  label_studio/tasks/serializers.py
  label_studio/tests/test_api.py
  label_studio/tests/utils.py
Labels: fix, Confirmed

#3174 docs: Release Notes for Label Studio Enterprise 2.3.1
  docs/source/guide/release_notes.md
Labels: docs

#3283 fix: DEV-3822: Rollback change DEV-3296
  label_studio/tasks/models.py
Labels: fix

#3244 feat: DEV-3259: Support updated_by for Annotations
  label_studio/tasks/api.py
  label_studio/tasks/migrations/0031_auto_20221118_2338.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
Labels: feat, Confirmed

#3289 fix: DEV-3259: Support updated_by for Annotations - Revert
  label_studio/tasks/api.py
  label_studio/tasks/migrations/0031_auto_20221118_2338.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
Labels: fix

#3291 ci: Fix upload release asset
  .github/workflows/build_pypi.yml
Labels: ci

#3266 fix: DEV-3779: Add control tag name to error
  label_studio/projects/models.py
Labels: fix

#3300 fix: DEV-3259: Delete Migration file
  label_studio/tasks/migrations/0031_auto_20221118_2338.py
Labels: fix

#3263 fix: DEV-3764: Fix CSV export download with non-existing columns
  deploy/requirements.txt
  label_studio/tests/data_export.tavern.yml
Labels: fix

#3302 ci: SRE-342: Auto generate release notes against previous release tag
  .github/workflows/cicd_pipeline.yml
Labels: ci

#3307 fix: SRE-330: Remove MEDIA_URL from uploaded file path
  label_studio/tasks/models.py
Labels: fix

#3326 fix: DEV-3866: Add info logs for delete job
  label_studio/core/redis.py
Labels: fix

#3335 fix: SRE-351: GCS persistent storage is broken
  deploy/requirements.txt
  label_studio/io_storages/gcs/models.py
Labels: ci
