Repository HumanSignal/label-studio, pull requests merged in 2022-07, with the labels that each got.

#2592 docs: Update Feature matrix page with links and remove Teams column
  docs/source/guide/label_studio_compare.md
Labels: docs, WIP

#2599 ci: Add Cancel PR Pipeline workflow
  .github/workflows/cancel_cicd_pipeline.yml
Labels: ci

#2606 Make subtopic for Export timeout in Community Edition
  docs/source/guide/export.md
  docs/source/includes/annotation_ids.md
Labels: docs

#2601 fix: Remove extra slash for file url
  label_studio/data_import/models.py
Labels: fix

#2610 feat: DEV-2750: Add ubi-based docker image
  .dockerignore
  .github/workflows/cicd_pipeline.yml
  .github/workflows/docker-build.yml
  .github/workflows/upload_to_pypi.yml
  Dockerfile
  Dockerfile.redhat
  licenses/django_license.txt
  licenses/python_license.txt
Labels: feat

#2609 feat: DEV-2651: Add pinned_at for project backend
  label_studio/projects/api.py
  label_studio/projects/migrations/0017_project_pinned_at.py
  label_studio/projects/models.py
  label_studio/projects/serializers.py
  label_studio/tests/test_projects.tavern.yml
Labels: feat

#2620 fix: DEV-2808: fix checkout from forks
  .github/workflows/bandit.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/gitleaks.yml
  .github/workflows/submodules-validator.yml
  .github/workflows/tests.yml
Labels: fix

#2624 fix: DEV-2687: Hide storage filename field for old projects
  label_studio/data_manager/migrations/0007_auto_20220708_0832.py
Labels: fix

#2616 ci: DEV-2802: Add Follow Merge workflow
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#2628 ci: fix indent
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#2636 ci: Bump Node version in follow merge
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#2640 docs: DEV-2825 Update Frontend Reference page
  docs/source/guide/frontend_reference.md
Labels: docs

#2645 docs: DEV-2834 Add a message for environment variable
  docs/source/guide/start.md
Labels: docs

#2644 ci: DEV-2826 Add Frontend Build
  .github/workflows/cicd_pipeline.yml
  .github/workflows/frontend-build.yml
Labels: ci

#2633 fix: Quote relative path
  label_studio/io_storages/localfiles/models.py
Labels: fix

#2657 ci: Support release Docker builds
  .github/workflows/cicd_pipeline.yml
  .github/workflows/docker-build.yml
Labels: ci

#2664 ci: Add draft release/hotfix workflow
  .github/workflows/draft-new-hotfix-release.yml
Labels: ci

#2670 docs: Fix menu for tags docs
  docs/themes/htx/layout/partials/toc.ejs
Labels: docs

#2666 ci: test
  .github/workflows/bandit.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/gitleaks.yml
  .github/workflows/submodules-validator.yml
  .github/workflows/tests.yml
Labels: ci

#2676 fix: DEV-2880: Skipped tasks are placed in the beginning of label stream
  label_studio/projects/functions/next_task.py
  label_studio/tasks/api.py
  label_studio/tests/next_task_skip_queue.tavern.yml
Labels: fix

#2691 ci: DEV-2901: Use merge commit as head SHA
  .github/workflows/cicd_pipeline.yml
Labels: ci

#2540 docs: DEV-1622: SCIM integration guide
  docs/source/guide/scim_setup.md
Labels: docs

#2687 ci: DEV-2731: Release pipeline
  .github/workflows/cicd_pipeline.yml
  .github/workflows/docker-release-promote.yml
  .github/workflows/release-pipeline.yml
  .github/workflows/upload_to_pypi.yml
Labels: ci

#2692 docs: Fix scim
  docs/source/guide/scim_setup.md
Labels: docs

#2698 docs: DEV-2912: Go back functionality docs page
  docs/source/guide/quality.md
Labels: docs

#2677 feat: DEV-1232: notification for storage persistence
  label_studio/core/settings/label_studio.py
  label_studio/core/static/css/Toast.min.css
  label_studio/core/static/js/Toast.min.js
  label_studio/templates/base.html
Labels: feat

#2614 docs: DEV-2810 Add Data Retrieval
  docs/source/guide/tasks.md
Labels: docs

#2706 fix: DEV-2936: Update django version
  deploy/requirements.txt
Labels: fix

#2273 fix: DEV-2236: Stored XSS via SVG file
  label_studio/core/settings/base.py
  label_studio/data_import/api.py
  label_studio/data_import/uploader.py
  label_studio/tests/test_upload_svg.py
Labels: fix

#2723 fix: Pytest with svg
  docs/source/guide/predictions.md
  label_studio/tests/test_upload_svg.py
Labels: fix

#2722 docs: Fix import predictions
  docs/source/guide/predictions.md
  docs/source/templates/optical_character_recognition.md
Labels: docs

#2726 ci: DEV-2732: DEV-2732: Create LS PR on release
  .github/workflows/update_pip_dependancy.yml
Labels: ci

#2752 ci: DEV-2902: Merge base branch on submodules bump
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#2753 ci: DEV-2902: Fix Follow merge branch
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#2760 fix: DEV-2939: Adding new fields leads to error in label config validation
  label_studio/projects/models.py
  label_studio/tests/config_validation.tavern.yml
Labels: fix
