Repository HumanSignal/label-studio, pull requests merged in 2022-12, with the labels that each got.

#3345 ci: SRE-344: add more cache
  .github/workflows/build_pypi.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/tests.yml
Labels: ci

#3353 fix: Add is_labeled filter to skip queue
  label_studio/projects/functions/next_task.py
Labels: fix

#3354 fix: Bump label-studio-converter to 0.0.48rc0
  deploy/requirements.txt
  label_studio/core/settings/base.py
  label_studio/data_manager/actions/experimental.py
  label_studio/tasks/serializers.py
Labels: fix

#3279 fix: DEV-3814: Fix update_tasks_counters call with DM filters
  label_studio/data_manager/actions/basic.py
  label_studio/data_manager/migrations/0008_manual_counters_update.py
  label_studio/tasks/functions.py
Labels: fix, Confirmed

#3373 Update LDAP capabilities
  docs/source/guide/auth_setup.md
Labels: title needs formatting

#3282 feat: DEV-3756: Queue management min backend
  label_studio/projects/api.py
  label_studio/projects/migrations/0018_alter_project_control_weights.py
  label_studio/tasks/migrations/0031_alter_task_options.py
  label_studio/tasks/mixins.py
  label_studio/tasks/models.py
  label_studio/tasks/serializers.py
Labels: feat, Confirmed

#3318 feat: DEV-3259: Updated_by field on annotation level for "Update", "Accept" and "Reject"
  label_studio/core/argparser.py
  label_studio/tasks/api.py
  label_studio/tasks/functions.py
  label_studio/tasks/management/commands/annotations_fill_updated_by.py
  label_studio/tasks/migrations/0032_annotation_updated_by.py
  label_studio/tasks/migrations/0033_annotation_updated_by_fill.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
Labels: feat, Confirmed

#3384 fix: DEV-3839: Avoid creation of pg_trgm in postgres if it's already existing
  label_studio/core/utils/common.py
  label_studio/tasks/migrations/0009_auto_20210913_0739.py
  label_studio/tasks/migrations/0017_new_index_anno_result.py
Labels: fix

#3398 feat: DEV-3259: Updated_by field on annotation level for "Update", "Accept" and "Reject" - revert again
  label_studio/core/argparser.py
  label_studio/tasks/api.py
  label_studio/tasks/functions.py
  label_studio/tasks/management/commands/annotations_fill_updated_by.py
  label_studio/tasks/migrations/0032_annotation_updated_by.py
  label_studio/tasks/migrations/0033_annotation_updated_by_fill.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
Labels: feat

#3401 feat: DEV-3259: Updated_by field on annotation level for "Update", "Accept" and "Reject"
  label_studio/core/argparser.py
  label_studio/tasks/api.py
  label_studio/tasks/functions.py
  label_studio/tasks/management/commands/annotations_fill_updated_by.py
  label_studio/tasks/migrations/0032_annotation_updated_by.py
  label_studio/tasks/migrations/0033_annotation_updated_by_fill.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
Labels: feat, Confirmed

#3418 ci: SRE-345: Add make migrations check
  .github/workflows/cicd_pipeline.yml
  .github/workflows/test_migrations.yml
  .github/workflows/tests.yml
Labels: ci

#3420 Revert "feat: DEV-3259: Updated_by field on annotation level for "Update", "Accept" and "Reject""
  label_studio/core/argparser.py
  label_studio/tasks/api.py
  label_studio/tasks/functions.py
  label_studio/tasks/management/commands/annotations_fill_updated_by.py
  label_studio/tasks/migrations/0032_annotation_updated_by.py
  label_studio/tasks/migrations/0033_annotation_updated_by_fill.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
Labels: title needs formatting

#3377 fix: DEV-3911: Move persistent storages to OS
  deploy/default.conf
  deploy/requirements.txt
  label_studio/core/all_urls.json
  label_studio/core/settings/base.py
  label_studio/core/storage.py
  label_studio/data_import/api.py
  label_studio/data_import/urls.py
Labels: fix

#3427 feat: DEV-3259: Annotation updated by
  label_studio/core/argparser.py
  label_studio/tasks/api.py
  label_studio/tasks/functions.py
  label_studio/tasks/management/commands/annotations_fill_updated_by.py
  label_studio/tasks/migrations/0032_annotation_updated_by.py
  label_studio/tasks/migrations/0033_annotation_updated_by_fill.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
Labels: title needs formatting

#3426 ci: SRE-364: Add octokit pagination
  .github/workflows/cicd_pipeline.yml
  .github/workflows/docker-release-promote.yml
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#3439 ci: Fix release branch prefix
  .github/workflows/upstream_repo_sync.yml
Labels: ci

#3440 ci: Fix workflow repo
  .github/workflows/cicd_pipeline.yml
Labels: ci

#3444 chore: DEV-2715: Allow js chunks to be served from static js root for lsf
  label_studio/frontend/get-build.js
Labels: chore

#3450 ci: Extend pypi timeout
  .github/workflows/build_pypi.yml
Labels: ci

#3452 fix: DEV-3259: Fix CLI command to manually migrate
  label_studio/tasks/management/commands/annotations_fill_updated_by.py
Labels: fix

#3454 fix: DEV-3865: Filter with the specific annotator works extremely slow
  label_studio/data_manager/managers.py
Labels: fix

#3448 fix: DEV-4039: Download storage empty path
  label_studio/data_import/api.py
  label_studio/tests/test_download_storage.tavern.yml
Labels: fix, Confirmed

#3471 ci: SRE-379: More readable release candidate version
  .github/workflows/cicd_pipeline.yml
Labels: ci

#3475 fix: DEV-4092: Pin numpy version
  deploy/requirements.txt
Labels: fix

#3382 fix: DEV-3812: Fix /validate to return 400 instead of 500 on invalid body request
  label_studio/core/utils/common.py
  label_studio/tests/test_config_validation.py
Labels: fix, Confirmed

#3485 fix: DEV-4092: Fix numpy version
  deploy/requirements.txt
Labels: fix

#3495 fix: Allow_postpone when task is none
  label_studio/projects/functions/next_task.py
Labels: fix

#3479 fix: DEV-4094: Fix multipage PDF template
  label_studio/annotation_templates/structured-data-parsing/pdf-multipage-annotation/config.xml
  label_studio/annotation_templates/structured-data-parsing/pdf-multipage-annotation/config.yml
  label_studio/frontend/dist/react-app/main.css
  label_studio/frontend/dist/react-app/main.css.map
  label_studio/frontend/src/pages/CreateProject/CreateProject.styl
Labels: fix, Confirmed
