Repository HumanSignal/label-studio, pull requests merged in 2022-09, with the labels that each got.

#2890 ci: DEV-3261: More strict conflict check
  .github/workflows/git-command.yml
Labels: ci

#2891 fix: DEV-3251: Sentry release frontend
  label_studio/frontend/src/config/Sentry.ts
  label_studio/frontend/webpack.config.js
Labels: fix

#2893 ci: DEV-3280: Add Sentry sourcemaps for LS releases
  .github/workflows/docker-release-promote.yml
Labels: title needs formatting

#2895 fix: DEV-3313: Fix Delete tasks action to work with annotated queryset
  label_studio/data_manager/actions/basic.py
Labels: fix, Confirmed

#2892 fix: DEV-1947: Fixed tabs randomly mixed after label stream
  label_studio/data_manager/api.py
  label_studio/tests/data_manager/test_views_api.py
Labels: fix, Confirmed

#2910 ci: Remove point from next develop version
  .github/workflows/cut-off-release-branch.yml
Labels: ci

#2914 docs: Added ENT tag for Outliner section
  docs/source/guide/labeling.md
Labels: docs

#2917 docs: Add custom tags assignment for Custom Agreement metric
  docs/source/guide/custom_metric.md
Labels: docs

#2921 docs: DEV-3378: added new LS blog post for 6 common mistakes
  docs/source/blog/6-costly-data-labeling-mistakes-and-how-to-avoid-them.md
  docs/source/blog/index.html
  docs/themes/htx/source/images/6-mistakes/6-costly-mistakes-thumbnail.png
  docs/themes/htx/source/images/6-mistakes/good-bad-label-error.png
  docs/themes/htx/source/images/6-mistakes/great-dane-label-error.png
  docs/themes/htx/source/images/6-mistakes/poodle-label-error.png
Labels: docs

#2929 fix: Misspell in data export
  label_studio/data_export/mixins.py
Labels: fix

#2931 docs: DEV-3398: publishing two label studio blog articles on sentiment analysis
  docs/source/blog/index.html
  docs/source/blog/sentiment-analysis-get-started.md
  docs/source/blog/understanding-sentiment-analysis.md
  docs/themes/htx/source/images/sentiment/get-started-sentiment-analysis-thumbnail.png
  docs/themes/htx/source/images/sentiment/understanding-sentiment-analysis-thumbnail.png
Labels: docs

#2918 fix: DEV-3379: Remove unused fields from completed_by
  label_studio/data_manager/serializers.py
  label_studio/io_storages/serializers.py
  label_studio/tasks/api.py
  label_studio/tasks/serializers.py
  label_studio/users/serializers.py
Labels: fix, Confirmed

#2946 fix: DEV-3387: Fix maximum annotations change after overlap change
  label_studio/projects/models.py
Labels: fix, Confirmed

#2912 fix: DEV-3351: Add more details for ML backend error
  label_studio/ml/api_connector.py
  label_studio/ml/serializers.py
Labels: fix, Confirmed

#2909 docs: DEV-3288: Add doc how to load data from LS from ML backend
  docs/source/guide/export.md
Labels: docs

#2925 fix: DEV-3342: Fix _scan_and_create_links failure for invalid annotation and prediction
  label_studio/io_storages/base_models.py
Labels: fix, Confirmed

#2980 fix: DEV-3491: Pin django rest framework requirement
  deploy/requirements.txt
Labels: fix

#2932 fix: DEV-3340: Update google storage dependencies
  deploy/requirements.txt
Labels: fix

#2977 fix: DEV-3216: User in request for managers.py
  label_studio/data_manager/functions.py
  label_studio/data_manager/managers.py
  label_studio/tasks/api.py
Labels: fix

#2976 feat: DEV-3372: Add "video" type to the Data Manager columns API
  label_studio/data_manager/functions.py
Labels: feat

#2984 docs: Removed ENT tag from Release Notes info section
  docs/source/guide/release_notes.md
Labels: docs

#2985 fix: LDAP docs
  docs/source/guide/auth_setup.md
Labels: fix

#2988 feat: revert: DEV-3372: Add "video" type to the Data Manager columns API
  label_studio/data_manager/functions.py
Labels: feat

#2972 Enable feature flags for 1.6 release
  label_studio/feature_flags.json
Labels: title needs formatting

#3003 docs: Introduce VideoRectangle tag
  docs/source/tags/audioplus.md
  docs/source/tags/datetime.md
  docs/source/tags/image.md
  docs/source/tags/paragraphs.md
  docs/source/tags/videorectangle.md
Labels: docs

#2966 docs: Add content for multiple BB creation
  docs/source/guide/labeling.md
Labels: docs

#3005 docs: Add mode property in Repeater Tag page
  docs/source/tags/repeater.md
Labels: docs

#3007 fix: DEV-3505: Cleanup contextlog
  .github/workflows/tests.yml
  label_studio/core/all_urls.json
  label_studio/core/feature_flags/base.py
  label_studio/core/middleware.py
  label_studio/core/urls.py
  label_studio/core/utils/common.py
  label_studio/core/utils/contextlog.py
  label_studio/data_export/api.py
  label_studio/data_import/urls.py
  label_studio/data_manager/api.py
  label_studio/data_manager/urls.py
  label_studio/io_storages/base_models.py
  label_studio/manage.py
  label_studio/ml/api.py
  label_studio/ml/api_connector.py
  label_studio/organizations/api.py
  label_studio/organizations/urls.py
  label_studio/tasks/api.py
  label_studio/tests/test_core.py
  label_studio/tests/test_endpoints.py
Labels: fix

#3014 fix: DEV-3513: Revert google deps
  deploy/requirements.txt
Labels: fix

#3023 Update LD client library
  deploy/requirements.txt
Labels: title needs formatting

#3016 docs: DEV-3514: Update README.md with new label studio brand images
  README.md
Labels: docs

#3022 fix: DEV-3239, DEV-3465: Data manager is broken if annotator is deactivated
  label_studio/organizations/api.py
  label_studio/organizations/serializers.py
Labels: fix

#2991 fix: DEV-1990: Fix config validation for video rectangle
  label_studio/projects/models.py
Labels: fix, Confirmed

#3008 docs: New header for docs site
  docs/themes/htx/layout/layout.ejs
  docs/themes/htx/layout/partials/footer.ejs
  docs/themes/htx/layout/partials/github_stars.ejs
  docs/themes/htx/layout/partials/header.ejs
  docs/themes/htx/layout/partials/heartex_header.ejs
  docs/themes/htx/layout/partials/index.ejs
  docs/themes/htx/layout/partials/ribbon.ejs
  docs/themes/htx/layout/partials/search.ejs
  docs/themes/htx/source/css/_common.styl
  docs/themes/htx/source/css/_header.styl
  docs/themes/htx/source/css/_settings.styl
  docs/themes/htx/source/css/header-footer.css
  docs/themes/htx/source/css/new-header.css
  docs/themes/htx/source/css/new-index.css
  docs/themes/htx/source/css/page.styl
  docs/themes/htx/source/js/common.js
  docs/themes/htx/source/js/new-index.js
Labels: docs

#3028 fix: Skip tests
  .github/workflows/tests.yml
Labels: fix
