Repository HumanSignal/label-studio, pull requests merged in 2023-08, with the labels that each got.

#4582 fix: LSDV-5221: Making sure that subquery for annotation only returns annotation matching its respective task
  label_studio/data_manager/managers.py
Labels: fix

#4595 docs: Fix display of contextual_scrolling.md image ref
  docs/source/templates/contextual_scrolling.md
Labels: docs

#4571 feat: LOPS-333: Get file metadata from files in AWS/Azure
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/azure_blob/utils.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/s3/utils.py
Labels: feat

#4603 fix: LSDV-5289: add logging to transactions FF check for debugging purposes
  label_studio/core/utils/db.py
  label_studio/projects/models.py
  label_studio/tasks/models.py
Labels: fix

#4608 fix: LSDV-4604: Move Webhooks to RQ jobs
  label_studio/tests/webhooks/test_webhooks.py
  label_studio/webhooks/utils.py
Labels: fix

#4588 fix: LSDV-5425-1: Harden task/annotation permissions
  label_studio/tasks/mixins.py
  label_studio/tasks/models.py
Labels: fix

#4606 feat: LOPS-384: Add synchronizable flag to storages
  label_studio/io_storages/api.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/migrations/0015_auto_20230804_1732.py
  label_studio/io_storages/serializers.py
  label_studio/tests/io_storages.tavern.yml
Labels: feat

#4590 feat: LOPS-334: Support AWS/Azure Dataset Storage
  label_studio/io_storages/azure_blob/serializers.py
  label_studio/io_storages/s3/serializers.py
  label_studio/tests/utils.py
Labels: feat

#4611 fix: LSDV-5222: custom weights reset following labeling interface changes
  label_studio/projects/models.py
Labels: fix

#4623 fix: LSDV-5425-1: Fix possible performance regression introduced in #4588
  label_studio/core/utils/db.py
  label_studio/tasks/mixins.py
  label_studio/tasks/models.py
Labels: fix

#4630 fix: LSDV-5515: introduce freeze_clock fixture and tick_clock function
  deploy/requirements-test.txt
  label_studio/tests/conftest.py
  label_studio/tests/sessions.tavern.yml
Labels: fix

#4586 feat: LSDV-3958: Server side encryption for Target Storage (KMS)
  label_studio/io_storages/migrations/0015_auto_20230722_0012.py
  label_studio/io_storages/s3/form_layout.yml
  label_studio/io_storages/s3/models.py
  label_studio/tests/conftest.py
  label_studio/tests/io_storages.tavern.yml
Labels: feat

#4633 fix: Develop/MR
  label_studio/io_storages/migrations/0016_add_aws_sse_kms_key.py
Labels: fix

#4635 fix: Add list to Text on labeling config validation
  label_studio/tasks/validation.py
Labels: fix

#4638 docs: Update links to roadmap in new org
  roadmap.md
Labels: docs

#4647 fix: LEAP-15: Only email is used for ff evaluation
  label_studio/core/feature_flags/base.py
Labels: fix

#4643 fix: LSDV-5486: Double encoding issue with file proxy urls
  label_studio/tasks/models.py
Labels: fix

#4663 fix: LSDV-5486: Double encoding issue with file proxy urls
  label_studio/tasks/models.py
Labels: fix

#4665 fix: LSDV-5348: More robust and uniform SSRF defenses (#4483)
  deploy/requirements.txt
  label_studio/core/settings/base.py
  label_studio/core/utils/contextlog.py
  label_studio/core/utils/exceptions.py
  label_studio/core/utils/io.py
  label_studio/data_import/uploader.py
  label_studio/feature_flags.json
  label_studio/ml/serializers.py
  label_studio/tests/data_import/test_uploader.py
  label_studio/tests/test_api.py
  label_studio/tests/test_core.py
  label_studio/tests/utils.py
Labels: fix

#4666 fix: LSDV-5348: More robust and uniform SSRF defenses
  deploy/requirements.txt
Labels: fix

#4629 perf: LSDV-4695: Add Project relation to Prediction model to improve overall performance
  label_studio/core/old_ls_migration.py
  label_studio/data_import/api.py
  label_studio/ml/models.py
  label_studio/tasks/functions.py
  label_studio/tasks/migrations/0041_prediction_project.py
  label_studio/tasks/migrations/0042_auto_20230810_2304.py
  label_studio/tasks/models.py
  label_studio/tests/test_export.py
  label_studio/tests/test_next_task.py
  label_studio/tests/test_predictions.py
  label_studio/tests/utils.py
Labels: perf

#4675 feat: LSDV-5545: Update conversational analysis template to include contextual scrolling by default
  label_studio/annotation_templates/audio-speech-processing/conversational-analysis/config.yml
Labels: feat

#4637 fix: LSDV-5507: Add contatct info to organization page when user is deactivated
  label_studio/data_manager/migrations/0008_manual_counters_update.py
  label_studio/organizations/migrations/0004_organization_contact_info.py
  label_studio/organizations/models.py
  label_studio/organizations/serializers.py
  label_studio/tasks/migrations/0024_manual_migrate_counters_again.py
Labels: fix

#4677 fix: LSDV-5507: fix migration order issue by using defer()
  label_studio/data_manager/migrations/0008_manual_counters_update.py
  label_studio/tasks/functions.py
  label_studio/tasks/migrations/0024_manual_migrate_counters_again.py
Labels: fix

#4679 docs: Remove defunct preview from contextual scrolling info
  docs/source/templates/contextual_scrolling.md
Labels: docs

#4676 fix: LSDV-5289-1: Load stats recalculation function from string, call after update task states
  label_studio/core/settings/base.py
  label_studio/data_import/api.py
  label_studio/data_import/functions.py
  label_studio/projects/mixins.py
  label_studio/projects/models.py
Labels: fix

#4686 chore: LEAP-35: Clean up feature flag and conditional_atomic usages
  label_studio/core/utils/db.py
  label_studio/projects/models.py
  label_studio/tasks/models.py
Labels: chore

#4687 chore: LEAP-35: remove default arg from conditional_atomic
  label_studio/core/utils/common.py
Labels: chore

#4690 fix: LSDV-5071: Ensure secret key is securely set persisting a new one if required
  deploy/requirements.txt
  label_studio/core/settings/base.py
  label_studio/core/utils/io.py
  label_studio/core/utils/params.py
Labels: fix

#4711 ci: Fix several vulnerabilities from dependabot
  docs/package.json
  docs/yarn.lock
  label_studio/frontend/dist/dm/version.json
  label_studio/frontend/dist/lsf/version.json
  label_studio/frontend/yarn.lock
Labels: ci

#4713 fix: LEAP-38: rework secret key generation to use data volume more reliably
  label_studio/core/settings/base.py
  label_studio/core/utils/io.py
  label_studio/core/utils/params.py
  label_studio/core/utils/secret_key.py
Labels: fix

#4716 fix: LEAP-38: Rework secret key generation to use data volume more reliably
  label_studio/core/settings/base.py
  label_studio/core/utils/io.py
  label_studio/core/utils/params.py
  label_studio/core/utils/secret_key.py
Labels: fix

#4718 docs: LSDV-5553: Remove dependency note from quickstart
  docs/source/guide/get_started.md
Labels: docs

#4721 fix: LEAP-41: Relocate secret key setting to LS only file
  label_studio/core/settings/base.py
  label_studio/core/settings/label_studio.py
  label_studio/core/utils/secret_key.py
Labels: fix

#4723 docs: Fix <details> plugin
  docs/package.json
  docs/scripts/details.js
  docs/yarn.lock
Labels: docs

#4725 fix: LEAP-7: Convert STORAGE_IN_PROGRESS_TIMER setting to float
  label_studio/core/settings/base.py
Labels: fix
