Repository HumanSignal/label-studio, pull requests merged in 2023-11, with the labels that each got.

#5005 fix: LEAP-58: split label config hash migration, use values_list
  label_studio/projects/migrations/0025_project_label_config_hash.py
  label_studio/projects/migrations/0026_auto_20231103_0020.py
  label_studio/tasks/migrations/0033_annotation_updated_by_fill.py
Labels: fix

#4927 feat: OPTIC-181: refactoring of soft-delete from Users to OrganizationMembers
  label_studio/core/all_urls.json
  label_studio/core/api_permissions.py
  label_studio/core/settings/base.py
  label_studio/data_export/api.py
  label_studio/organizations/api.py
  label_studio/organizations/migrations/0005_organizationmember_deleted_at.py
  label_studio/organizations/mixins.py
  label_studio/organizations/models.py
  label_studio/organizations/urls.py
  label_studio/tests/users.tavern.yml
  label_studio/tests/webhooks/organizations.tavern.yml
  label_studio/users/admin.py
  label_studio/users/api.py
  label_studio/users/mixins.py
  label_studio/users/models.py
  label_studio/users/serializers.py
  label_studio/users/urls.py
  label_studio/users/views.py
Labels: feat, Confirmed

#4920 docs: DOC-144: Label group visibility in project dashboards
  docs/source/guide/dashboards.md
Labels: docs

#4899 docs: DOC-143: Add section about deleting a user
  docs/source/guide/manage_users.md
  docs/themes/v2/source/images/user_delete.png
Labels: docs

#5020 ci: PLATE-696: Avoid direct usage of variables
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#5012 fix: LEAP-237: Patch ORM Leak vulnerability in open source
  label_studio/core/settings/base.py
  label_studio/core/utils/params.py
  label_studio/data_manager/functions.py
  label_studio/data_manager/serializers.py
  label_studio/tests/data_manager/api_tasks.tavern.yml
Labels: fix

#5021 refactor: LEAP-65: Add pdm section to pyproject.toml
  pyproject.toml
Labels: refactor

#5033 fix: DIA-354: Fix validation for non-existing GCS bucket prefix
  label_studio/tests/utils.py
Labels: fix

#4864 docs: DOC-121: Add external taxonomy info to the Taxonomy templates page
  docs/source/templates/taxonomy.md
  label_studio/core/static/templates/taxonomy.png
Labels: docs

#5035 refactor: Poetry instead of PDM
  .dockerignore
  .github/workflows/build_pypi.yml
  .github/workflows/test_conda.yml
  .github/workflows/test_migrations.yml
  .github/workflows/tests.yml
  Dockerfile
  Dockerfile.redhat
  label_studio/frontend/package.json
  label_studio/frontend/release.js
  label_studio/frontend/yarn.lock
  poetry.lock
  pyproject.toml
Labels: refactor

#4888 feat: LEAP-65: Use poetry for dependecies management
  .dockerignore
  .github/workflows/build_pypi.yml
  .github/workflows/test_conda.yml
  .github/workflows/test_migrations.yml
  .github/workflows/tests.yml
  .gitignore
  Dockerfile
  Dockerfile.redhat
  label_studio/__init__.py
  label_studio/frontend/package.json
  label_studio/frontend/release.js
  label_studio/frontend/yarn.lock
  poetry.lock
  pyproject.toml
Labels: feat

#5056 docs: Update `Try Cloud` link in header
  docs/themes/v2/layout/partials/header.ejs
Labels: docs

#4931 feat: OPTIC-188: Separating swagger and redoc views so that they can be permissioned differently
  label_studio/core/urls.py
Labels: feat, Confirmed

#4950 fix: LEAP-297: Fix import rq job timeout
  label_studio/io_storages/base_models.py
Labels: fix, Confirmed

#5071 fix: Include static files into pypi package
  pyproject.toml
Labels: fix

#5078 ci: Fix multiline GITHUB_OUTPUT
  .github/workflows/frontend-command.yml
Labels: ci

#5080 fix: OPTIC-45: Font styles incorrect on settings pages
  label_studio/core/static/css/main.css
Labels: fix, Confirmed

#5105 fix: Update ff_front_dev_1682_model_version_dropdown_070622_short state
  label_studio/feature_flags.json
Labels: fix

#5102 docs: DOC-161: Beta tag and note about syncing with taxonomy
  docs/source/templates/taxonomy.md
Labels: docs

#5121 docs: Update contact link in the footer
  docs/themes/v2/layout/partials/footer.ejs
Labels: docs
