Repository HumanSignal/label-studio, pull requests merged in 2023-01, with the labels that each got.

#3473 fix: DEV-4091: Remove unused task lock ttl settings
  label_studio/core/settings/base.py
  label_studio/tasks/models.py
Labels: fix

#3364 docs: Add status info for user accounts
  docs/source/guide/manage_users.md
Labels: docs

#3496 fix: DEV-3577: Fix validation for required toName parameter on TextArea
  label_studio/core/utils/schema/label_config_schema.json
  label_studio/tests/test_config_validation.py
  label_studio/tests/test_data/data_for_test_label_config_matrix.yml
Labels: fix, Confirmed

#3540 fix: Typos identified by codespell
  docs/source/blog/6-costly-data-labeling-mistakes-and-how-to-avoid-them.md
  docs/source/blog/Automate-your-ML-pipeline-with-Label-Studio-and-Amazon-SageMaker.md
  docs/source/blog/Improve-OCR-quality-with-Tesseract-and-Label-Studio.md
  docs/source/blog/release-050.md
  docs/source/guide/frontend.md
  docs/source/tags/number.md
  docs/source/templates/intent_classification.md
  docs/source/templates/inventory_tracking.md
  docs/source/templates/multi-page-document-annotation.md
  docs/source/templates/taxonomy.md
  label_studio/annotation_templates/natural-language-processing/taxonomy/config.xml
  label_studio/core/feature_flags/README.md
  label_studio/core/settings/base.py
  label_studio/core/storage.py
  label_studio/core/utils/common.py
  label_studio/frontend/README.md
  label_studio/io_storages/redis/models.py
  label_studio/projects/api.py
  label_studio/projects/migrations/0001_squashed_0065_auto_20210223_2014.py
  label_studio/projects/models.py
  label_studio/server.py
  label_studio/tasks/models.py
  label_studio/tests/test_invites.py
  label_studio/tests/test_predictions.py
  label_studio/tests/test_project_validation.py
  label_studio/webhooks/utils.py
Labels: fix

#3538 fix: DEV-4175: Fix task lock logging exception
  label_studio/tasks/models.py
Labels: fix

#3536 fix: DEV-1395: Activity log fixes
  label_studio/core/all_urls.json
  label_studio/core/models.py
  label_studio/data_export/mixins.py
  label_studio/data_import/models.py
  label_studio/data_manager/models.py
  label_studio/io_storages/base_models.py
  label_studio/labels_manager/models.py
  label_studio/ml/models.py
  label_studio/projects/mixins.py
  label_studio/projects/models.py
  label_studio/tasks/migrations/0033_annotation_updated_by_fill.py
  label_studio/tasks/models.py
  label_studio/users/admin.py
  label_studio/webhooks/models.py
Labels: fix

#3544 ci: SRE-391: Add release permissions
  .github/workflows/cicd_pipeline.yml
  .github/workflows/release-pipeline.yml
Labels: ci

#3531 fix: DEV-4166: Fix make_queryset_from_iterable for empty list
  label_studio/projects/functions/utils.py
  label_studio/tests/test_project.py
Labels: fix, Confirmed

#3541 fix: DOC-106: Issues on ENT docs site
  docs/source/guide/get_started.md
  docs/themes/v2/layout/home.ejs
Labels: title needs formatting

#3553 fix: Relax and update pydantic version
  deploy/requirements.txt
Labels: fix

#3549 fix: DEV-4185: Switch level of next task log messages
  label_studio/projects/functions/next_task.py
  label_studio/tasks/models.py
Labels: fix

#3467 fix: DEV-4086: Remove unused indexes
  label_studio/core/utils/common.py
  label_studio/tasks/migrations/0034_auto_20221221_1101.py
  label_studio/tasks/migrations/0035_auto_20221221_1116.py
  label_studio/tasks/models.py
  label_studio/webhooks/migrations/0004_auto_20221221_1101.py
  label_studio/webhooks/models.py
Labels: fix, Confirmed

#3558 fix: Account page misspell leading to broken javascript
  label_studio/users/templates/users/user_account.html
Labels: fix

#3570 ci: Use only first commit message line in version.json
  label_studio/frontend/get-build.js
Labels: ci

#3571 fix: DEV-4090: Fix migration conflict
  label_studio/tasks/migrations/0037_merge_0035_auto_20221221_1116_0036_auto_20221223_1102.py
Labels: fix

#3547 fix: DEV-4114: Fix Text and HyperText elements can be added without value and name
  label_studio/core/utils/schema/label_config_schema.json
  label_studio/tests/data_export.tavern.yml
  label_studio/tests/test_config_validation.py
  label_studio/tests/test_data/data_for_test_label_config_matrix.yml
Labels: fix, Confirmed, test

#3466 fix: DEV-4074: Fix task matching query does not exist status code to 404
  label_studio/tasks/api.py
  label_studio/tests/tasks_api.tavern.yml
Labels: fix, Confirmed

#3577 fix: DEV-4229: Run label-studio init in docker-compose
  deploy/default.conf
  deploy/docker-entrypoint.d/app/31-run-label-studio-init.sh
  deploy/docker-entrypoint.sh
  label_studio/core/argparser.py
  label_studio/server.py
Labels: fix

#3579 feat: Experimental features add range expression
  label_studio/data_manager/actions/experimental.py
Labels: feat

#3515 fix: Codespell configuration and github action workflow
  .codespellrc
  .github/workflows/codespell.yml
  docs/source/guide/webhook_reference.md
Labels: fix

#3575 fix: DEV-4228: Critical overlap issue with task locks and skipped annotations
  label_studio/projects/functions/next_task.py
  label_studio/tasks/models.py
Labels: fix

#3567 fix: DEV-4202: Task locks in postponed/skipped queue
  label_studio/projects/docs/README.md
  label_studio/projects/functions/next_task.py
  label_studio/tasks/models.py
Labels: fix, Confirmed

#3582 fix: Check storages before sending save signal in rq
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/redis/models.py
  label_studio/io_storages/s3/models.py
Labels: fix

#3587 fix: DEV-4210: Import jobs are submitted twice (or more) times
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/s3/models.py
  label_studio/tasks/api.py
Labels: fix

#3585 fix: DEV-4263: Can't start LS after upgrade because of pinned_at depe…
  label_studio/tasks/migrations/0024_manual_migrate_counters_again.py
Labels: fix

#3606 fix: LSDV-4524: Fix migration dependency for upgrade
  label_studio/data_manager/migrations/0008_manual_counters_update.py
Labels: fix

#3614 ci: SRE-407: Fix PyPI release details parser
  .github/workflows/build_pypi.yml
Labels: ci, breaking

#3615 fix: DEV-4180: Optimize memory and speed during exports (LSDV-1010)
  label_studio/data_export/mixins.py
  label_studio/data_export/serializers.py
  label_studio/projects/models.py
Labels: fix

#3618 fix: Add s3 custom endpoints support
  label_studio/core/settings/base.py
Labels: fix
