Repository HumanSignal/label-studio, pull requests merged in 2023-03, with the labels that each got.

#3763 ci: SRE-446: Switch RN generator to tags
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
  .github/workflows/cicd_pipeline.yml
Labels: ci, breaking

#3765 ci: SRE-446: Switch RN generator to tags
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
  .github/workflows/cicd_pipeline.yml
Labels: ci, breaking

#3767 fix: LSDV-4677: Add custom endpoint support to persistent storages, AWS_S3_USE_SSL was missed
  label_studio/core/settings/base.py
Labels: fix

#3771 feat: LOPS-26: Dataset Import Storage
  label_studio/io_storages/README.md
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/localfiles/models.py
  label_studio/io_storages/redis/models.py
  label_studio/io_storages/s3/models.py
Labels: feat

#3777 docs: Fix "$remote-csv" value, not supported now
  docs/source/guide/tasks.md
Labels: docs

#3780 ci: SRE-447: Support AHA! Requirements in changelog
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
Labels: ci, breaking

#3782 ci: Sync GH workflows
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
  .github/workflows/algolia-crawler.yml
  .github/workflows/docker-build-ontop.yml
  .github/workflows/docs-enterprise.yml
  .github/workflows/release-pipeline.yml
Labels: ci, breaking

#3785 docs: Fix broken tag pages
  docs/source/tags/choices.md
  docs/source/tags/labels.md
  docs/source/tags/style.md
Labels: docs

#3789 docs: LSDV-4713: Add timeout for SaaS Cloud
  docs/source/guide/ml_troubleshooting.md
Labels: docs, breaking

#3792 docs: LSDV-4714: Fix switch target for currentTarget for copy code buttons
  docs/themes/v2/source/js/code-blocks-enhancements.js
Labels: docs, fix

#3800 docs: LSDV-4714: Add Compare page back
  docs/source/guide/label_studio_compare.md
Labels: docs

#3793 docs: LSDV-4714: Update JS syntax to support old Firefox version
  docs/themes/v2/source/js/header.js
Labels: docs

#3798 docs: LSDV-4718: Fix incorrect naming of the mounted directory
  docs/source/guide/install.md
Labels: docs

#3795 docs: Add release notes for 2.4.3
  docs/source/guide/release_notes/onprem/2.4.3.md
Labels: docs

#3815 ci: Add header about helm chart
  docs/source/guide/release_notes/onprem/2.4.3.md
Labels: ci

#3770 fix: LSDV-4568: Fix csv import from url
  label_studio/data_import/uploader.py
  label_studio/tests/conftest.py
  label_studio/tests/data_import.tavern.yml
  label_studio/tests/test_tasks_upload.py
  label_studio/tests/utils.py
Labels: fix

#3769 feat: LOPS-26: Understand tradeoffs for reuse of LSE storage implementation in Indexer module
  label_studio/core/all_urls.json
  label_studio/io_storages/README.md
  label_studio/io_storages/azure_blob/form_layout.yml
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/gcs/form_layout.yml
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/gcs/serializers.py
  label_studio/io_storages/gcs/utils.py
  label_studio/io_storages/localfiles/models.py
  label_studio/io_storages/redis/models.py
  label_studio/io_storages/s3/form_layout.yml
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/urls.py
  label_studio/tests/utils.py
Labels: feat, breaking

#3829 docs: LSDV-4742: Add image about LS server and user invites
  docs/source/guide/signup.md
  docs/themes/v2/source/images/invite-collaborators-ls-single-server.png
Labels: docs

#3830 docs: Add example with ngrok
  docs/source/guide/start.md
Labels: docs, breaking

#3833 feat: LSDV-4748: annotate_task_number works slowly in api/projects
  label_studio/projects/functions/__init__.py
Labels: feat

#3835 fix: LSDV-4567: Issue with Python SDK and null values in fields
  label_studio/tasks/validation.py
Labels: fix, breaking

#3844 fix: LSDV-961: Bad gateway at api/projects and performance fixes: remove excess distincts
  label_studio/projects/functions/__init__.py
Labels: fix, breaking

#3849 fix: LSDV-4661: Full solution for storage link resolver in nested task data fields
  label_studio/io_storages/utils.py
  label_studio/tasks/models.py
Labels: fix, breaking

#3861 fix: LSDV-4661: Full solution for storage link resolver in nested task fields: Add tests
  label_studio/io_storages/utils.py
  label_studio/tests/io_storages.tavern.yml
Labels: fix, breaking

#3297 fix: DEV-3743: Fixing aggregation for annotation results
  label_studio/data_manager/managers.py
  label_studio/tests/data_manager/filters/annotation_results.tavern.yml
  label_studio/tests/tasks_api.tavern.yml
Labels: fix

#3863 docs: LSDV-4803: Concatenate release notes based on specific release md files in docs
  docs/package-lock.json
  docs/package.json
  docs/scripts/release-notes.js
  docs/source/guide/release_notes.md
  docs/source/guide/release_notes/onprem/2.2.8.md
  docs/source/guide/release_notes/onprem/2.2.9.md
  docs/source/guide/release_notes/onprem/2.2.md
  docs/source/guide/release_notes/onprem/2.3.1.md
  docs/source/guide/release_notes/onprem/2.4.0.md
  docs/source/guide/release_notes/onprem/2.4.1.md
  docs/source/guide/release_notes/onprem/2.4.2.md
  docs/source/guide/release_notes/onprem/2.4.3.md
  docs/themes/v2/layout/layout.ejs
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/js/collapse.js
Labels: docs

#2872 fix: LSDV-4808: Remove html minification when import html directly
  label_studio/data_import/models.py
Labels: fix

#3875 fix: LSDV-4806: Proper unhandled exceptions processing
  label_studio/core/utils/params.py
  label_studio/data_manager/managers.py
  label_studio/tests/test_core.py
Labels: fix, breaking

#3842 docs: LSDV-4754: Update Audio documentation to point to v3
  docs/source/tags/audio.md
  docs/source/tags/hypertext.md
  docs/source/tags/image.md
  docs/source/tags/paragraphs.md
  docs/source/tags/style.md
  docs/source/tags/table.md
  docs/source/tags/text.md
  docs/source/tags/timeseries.md
  docs/source/tags/video.md
  docs/source/tags/view.md
Labels: docs

#3756 docs: Magic Wand tool
  docs/source/tags/magicwand.md
  docs/source/tags/number.md
  docs/source/tags/pairwise.md
  docs/source/tags/paragraphlabels.md
  docs/source/tags/polygon.md
  docs/source/tags/polygonlabels.md
  docs/source/tags/ranker.md
  docs/source/tags/rating.md
  docs/source/tags/rectangle.md
  docs/source/tags/rectanglelabels.md
  docs/source/tags/relation.md
  docs/source/tags/relations.md
  docs/source/tags/shortcut.md
  docs/source/tags/taxonomy.md
  docs/source/tags/textarea.md
  docs/source/tags/timeserieslabels.md
  docs/source/tags/videorectangle.md
  docs/themes/v2/source/images/magicwand_example.gif
Labels: docs

#3822 ci: SRE-422: Follow Merge auto conflict resolver
  .github/workflows/upstream_repo_sync.yml
Labels: ci, breaking

#3880 ci: SRE-461: Tag Aha! ticket with oss release
  .github/workflows/pr-labeler.yml
Labels: ci

#3874 docs: Github-3396: Add remark for newer versions of pytorch and mmdet…
  docs/source/tutorials/object-detector.md
Labels: docs, breaking

#3886 ci: Add oss releases tag on release
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
  .github/workflows/cicd_pipeline.yml
Labels: ci

#3889 docs: LSDV-4840: Fix api link in ML interactive annotations for docs
  label_studio/ml/api.py
Labels: docs

#3890 docs: LSDV-4841: Fix pre-annotations page in docs. Add more storage docs
  docs/source/guide/predictions.md
  docs/source/guide/release_notes.md
  docs/source/guide/storage.md
  docs/source/includes/image_units.md
  docs/themes/v2/source/images/predictions_loaded.png
  docs/themes/v2/source/images/predictions_loaded_text.png
  docs/themes/v2/source/images/source-cloud-storages.png
Labels: docs

#3873 docs: Update broken links in export.md
  docs/source/guide/export.md
Labels: docs, breaking

#3866 feat: LOPS-61: Add columns endpoint for views in DataExplorer
  deploy/requirements.txt
  label_studio/tests/__init__.py
Labels: feat, breaking

#3897 docs: SRE-456: Add Brew install guide
  docs/source/guide/install.md
Labels: docs

#3901 ci: SRE-464: Delete release candidates on release publish
  .github/workflows/release-pipeline.yml
Labels: ci

#3888 feat: LOPS-29-1: API to get column names from user's data
  label_studio/tests/utils.py
Labels: feat

#3909 fix: LSDV-4862: Clarify Feature Flags usage in our products
  label_studio/core/feature_flags/README.md
  label_studio/core/feature_flags/__init__.py
  label_studio/core/feature_flags/base.py
  label_studio/core/views.py
Labels: fix

#3911 ci: SRE-469: get ls version
  label_studio/core/utils/common.py
  label_studio/core/version.py
Labels: ci

#3915 ci: SRE-468: Bump version as direct push
  .github/workflows/release-cut-off-release-branch.yml
  .github/workflows/release-pipeline.yml
  .github/workflows/release-set-version.yml
Labels: ci

#3919 docs: LSDV-4874: Update audio documentation to outline splitchannels usage
  docs/source/tags/audio.md
Labels: docs

#3931 docs: LSDV-4714: Update algolia-crawler.yml
  .github/workflows/algolia-crawler.yml
Labels: docs

#3933 ci: SRE-471: Scheduled LSF sync
  .github/workflows/follow-merge-lsf-sync-schedule.yml
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#3936 ci: User releases task field in RN
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
Labels: ci

#3937 ci: User releases task field in RN
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
Labels: ci

#3938 ci: Revert "User releases task field in RN"
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
Labels: ci

#3942 ci: Refactor Follow Merge
  .github/workflows/follow-merge-lsf-sync-schedule.yml
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci
