Repository HumanSignal/label-studio, pull requests merged in 2023-10, with the labels that each got.

#4851 chore: upgrade some dependencies to unbreak docker build with test deps
  deploy/requirements-test.txt
  deploy/requirements.txt
Labels: chore

#4856 docs: DOCS-128: Fix role descriptions to include appropriate API access
  docs/source/guide/manage_users.md
Labels: docs

#4858 fix: API permissions for docs
  label_studio/core/urls.py
Labels: fix

#4859 Revert "fix: API permissions for docs"
  label_studio/core/urls.py
Labels: title needs formatting

#4863 fix: make blue required in cicd
  .github/workflows/cicd_pipeline.yml
Labels: fix

#4871 docs: DOC-137: Remove page for unsupported time series feature
  docs/source/guide/ts+video.md
Labels: docs

#4872 docs: DOC-120: Recommend SSRF protection variable
  docs/source/guide/helm_values.md
  docs/source/guide/install_enterprise_k8s.md
  docs/source/guide/install_k8s.md
  docs/source/guide/security.md
Labels: docs

#4873 docs: Remove tier-specific content from the table of content
  docs/scripts/index.js
  docs/scripts/removeContent.js
  docs/themes/v2/layout/page.ejs
Labels: docs

#4832 feat: OPTIC-118: Query updates to support user soft deletion
  label_studio/users/admin.py
  label_studio/users/migrations/0001_squashed_0009_auto_20210219_1237.py
  label_studio/users/migrations/0008_alter_user_managers.py
  label_studio/users/models.py
  label_studio/users/serializers.py
Labels: feat

#4862 fix: LEAP-182: Org and deployment level setting for cert verification
  label_studio/core/settings/base.py
  label_studio/core/utils/windows_sqlite_fix/__init__.py
  label_studio/data_import/uploader.py
  label_studio/organizations/models.py
  label_studio/tasks/functions.py
Labels: fix

#4818 fix: LEAP-192: Check avatar file extension
  label_studio/users/functions.py
  label_studio/users/urls.py
Labels: fix

#4876 feat: OPTIC-116: User soft-deletion API
  label_studio/core/all_urls.json
  label_studio/core/api_permissions.py
  label_studio/core/settings/base.py
  label_studio/tests/users.tavern.yml
  label_studio/users/models.py
  label_studio/users/urls.py
  label_studio/users/views.py
Labels: feat

#4891 chore: LEAP-52: add tests for the pagination fix in label-studio-sdk#153
  label_studio/tests/conftest.py
  label_studio/tests/sdk/__init__.py
  label_studio/tests/sdk/test_projects.py
  label_studio/tests/sdk/utils.py
Labels: chore

#4897 docs: DOC-132: Small update to Projects to Groups Mapping description
  docs/source/guide/auth_setup.md
  docs/source/guide/scim_setup.md
Labels: docs

#4847 fix: DIA-414: Validate bucket/credentials when editing storage
  label_studio/io_storages/s3/serializers.py
Labels: fix

#4890 fix: OPTIC-116 update users api for soft delete to match format of other users api endpoints
  label_studio/core/all_urls.json
  label_studio/tests/users.tavern.yml
  label_studio/users/urls.py
  label_studio/users/views.py
Labels: fix

#4905 fix: LEAP-280: Azure storage validation too long
  deploy/requirements-test.txt
  label_studio/io_storages/azure_blob/models.py
Labels: fix, Confirmed

#4937 docs: Fix broken links in Project Setup page
  docs/source/guide/setup_project.md
Labels: docs

#4778 fix: LEAP-19: Add GCS bucket cache
  label_studio/core/utils/common.py
  label_studio/io_storages/gcs/utils.py
Labels: fix, Confirmed

#4869 feat: Allow the AWS S3 signature version to be specified for Django storages
  label_studio/core/settings/base.py
Labels: feat

#4965 docs: Support parents in sidebar menu
  docs/source/guide/helm_values.md
  docs/source/guide/ingress_config.md
  docs/source/guide/install_k8s_airgapped.md
  docs/themes/v2/layout/partials/toc.ejs
Labels: docs

#4934 docs: DOC-148: Update feature_request.md remove auto-assignment
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: docs

#4925 fix: OPTIC-182: Ensuring Task view always has task attribute no matter the method called
  label_studio/tasks/api.py
Labels: fix, Confirmed

#4967 docs: DOC-153: Adjust order in page front matter
  docs/scripts/release-notes.js
  docs/source/guide/FAQ.md
  docs/source/guide/active_learning.md
  docs/source/guide/api.md
  docs/source/guide/auth_setup.md
  docs/source/guide/billing.md
  docs/source/guide/comments_notifications.md
  docs/source/guide/custom_metric.md
  docs/source/guide/dashboards.md
  docs/source/guide/dataset_create.md
  docs/source/guide/dataset_manage.md
  docs/source/guide/dataset_search.md
  docs/source/guide/email_setup.md
  docs/source/guide/export.md
  docs/source/guide/frontend.md
  docs/source/guide/frontend_reference.md
  docs/source/guide/get_started.md
  docs/source/guide/helm_values.md
  docs/source/guide/index.md
  docs/source/guide/ingress_config.md
  docs/source/guide/install.md
  docs/source/guide/install_enterprise.md
  docs/source/guide/install_enterprise_docker.md
  docs/source/guide/install_enterprise_k8s.md
  docs/source/guide/install_k8s.md
  docs/source/guide/install_k8s_airgapped.md
  docs/source/guide/label_studio_compare.md
  docs/source/guide/labeling.md
  docs/source/guide/manage_data.md
  docs/source/guide/manage_projects.md
  docs/source/guide/manage_users.md
  docs/source/guide/ml.md
  docs/source/guide/ml_create.md
  docs/source/guide/ml_troubleshooting.md
  docs/source/guide/ml_tutorials.html
  docs/source/guide/persistent_storage.md
  docs/source/guide/predictions.md
  docs/source/guide/quality.md
  docs/source/guide/saas.md
  docs/source/guide/scim_setup.md
  docs/source/guide/sdk.md
  docs/source/guide/security.md
  docs/source/guide/setup.md
  docs/source/guide/setup_project.md
  docs/source/guide/signup.md
  docs/source/guide/start.md
  docs/source/guide/stats.md
  docs/source/guide/storage.md
  docs/source/guide/storedata.md
  docs/source/guide/task_format.md
  docs/source/guide/tasks.md
  docs/source/guide/upgrade_enterprise.md
  docs/source/guide/webhook_create.md
  docs/source/guide/webhook_reference.md
  docs/source/guide/webhooks.md
Labels: docs

#4969 docs: DOC-151: Remove Firefox and Safari from browser list
  docs/source/guide/install.md
Labels: docs

#4973 fix: OPTIC-182: Ensuring Task view always has task attribute no matter the method called (#4925)
  deploy/requirements-test.txt
  label_studio/tasks/api.py
Labels: fix

#4979 fix: OPTIC-79: Add queueTotal to lsfProperties from project (#4742)
  label_studio/projects/serializers.py
Labels: fix

#4849 feat: OPTIC-65: Adding label_config_hash to project
  label_studio/projects/migrations/0025_project_label_config_hash.py
  label_studio/projects/models.py
  label_studio/tasks/functions.py
Labels: feat, Confirmed
