Repository HumanSignal/label-studio, pull requests merged in 2023-06, with the labels that each got.

#4249 fix: LSDV-3860: Insufficient Authorization Checks – Email Field
  label_studio/tests/users.tavern.yml
  label_studio/users/api.py
  label_studio/users/serializers.py
Labels: fix

#4297 feat: LSDV-5212: Add Ranker templates
  label_studio/annotation_templates/generative-ai/llm-ranker/config.yml
  label_studio/annotation_templates/generative-ai/llm-ranker/example.json
  label_studio/annotation_templates/generative-ai/visual-ranker/config.yml
  label_studio/annotation_templates/generative-ai/visual-ranker/example.json
  label_studio/core/static/samples/chairs/chair1.png
  label_studio/core/static/samples/chairs/chair2.png
  label_studio/core/static/samples/chairs/chair3.png
  label_studio/core/static/samples/chairs/chair4.png
  label_studio/core/static/templates/visual-ranker.png
Labels: feat

#4304 fix: LSDV-1060: Remove duplicated PDF template
  label_studio/annotation_templates/structured-data-parsing/pdf-multipage-annotation/config.xml
  label_studio/annotation_templates/structured-data-parsing/pdf-multipage-annotation/config.yml
Labels: fix

#4302 fix: LSDV-1060: Remove duplicated PDF template
  label_studio/annotation_templates/structured-data-parsing/pdf-multipage-annotation/config.xml
  label_studio/annotation_templates/structured-data-parsing/pdf-multipage-annotation/config.yml
Labels: fix

#4315 fix: LSDV-5229: Add missing image for templates
  label_studio/core/static/templates/llm-ranker.png
Labels: fix

#4311 docs: LSDV-4880: updating docs for cors policy
  docs/source/guide/persistent_storage.md
  docs/source/guide/storage.md
Labels: docs

#4294 docs: LSDV-3869: Add more info about Results format
  docs/package.json
  docs/source/guide/task_format.md
  docs/source/includes/result_format.md
  docs/source/includes/task_format.md
Labels: docs

#4280 feat: LSDV-5212: Add Ranker templates
  label_studio/annotation_templates/generative-ai/llm-ranker/config.yml
  label_studio/annotation_templates/generative-ai/llm-ranker/example.json
  label_studio/annotation_templates/generative-ai/visual-ranker/config.yml
  label_studio/annotation_templates/generative-ai/visual-ranker/example.json
  label_studio/core/static/samples/chairs/chair1.png
  label_studio/core/static/samples/chairs/chair2.png
  label_studio/core/static/samples/chairs/chair3.png
  label_studio/core/static/samples/chairs/chair4.png
  label_studio/core/static/templates/visual-ranker.png
Labels: feat

#4289 fix: LSDV-5218: Fix data import through SDK
  label_studio/data_import/functions.py
Labels: fix

#4335 fix: LSDV-5249: Dependabot updates
  deploy/requirements-mw.txt
  docs/package-lock.json
  docs/package.json
Labels: fix

#4349 chore: remove Ranker templates from release
  label_studio/annotation_templates/generative-ai/llm-ranker/config.yml
  label_studio/annotation_templates/generative-ai/llm-ranker/example.json
  label_studio/annotation_templates/generative-ai/visual-ranker/config.yml
  label_studio/annotation_templates/generative-ai/visual-ranker/example.json
Labels: chore

#4348 fix: LSDV-5245: COCO and YOLO export error
  deploy/requirements.txt
Labels: fix

#4355 ci: SRE-536: Add ff ChatOps command
  .github/workflows/cicd_pipeline.yml
  .github/workflows/feature-flags-update.yml
  .github/workflows/ff-command.yml
  .github/workflows/release-cut-off-release-branch.yml
  .github/workflows/slash-command-dispatch.yml
Labels: ci

#4361 docs: Restore tags/index.md
  docs/source/tags/index.md
Labels: docs

#4360 chore: LSDV-4983: FF file update
  label_studio/feature_flags.json
Labels: chore

#4369 ci: Add workflow link to commit message
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#4372 fix: Use class name in validation message
  label_studio/tasks/validation.py
Labels: fix

#4345 doc: fix typo in install_k8s.md
  docs/source/guide/install_k8s.md
Labels: title needs formatting

#4377 ci: Add workflow links to commit message
  .github/workflows/bump-helm-chart.yml
  .github/workflows/feature-flags-update.yml
  .github/workflows/follow-merge-upstream-repo-sync.yml
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-command.yml
  .github/workflows/release-set-version.yml
  .github/workflows/update_pip_dependancy.yml
Labels: ci

#4145 feat: SRE-508: Add support for STORAGE_AWS_OBJECT_PARAMETERS
  label_studio/core/settings/base.py
Labels: feat

#4194 fix: LSDV-5096: Loading a pre-signed url with the new proxy urls in a new tab does not work
  label_studio/core/static/js/sw.js
Labels: fix

#4411 ci: Change scheduled lsf sync PR name
  .github/workflows/follow-merge-lsf-sync-schedule.yml
Labels: ci

#4382 ci: SRE-541: Dynamic github org name
  .github/workflows/follow-merge-lsf-sync-schedule.yml
  .github/workflows/follow-merge-sync-pr.yml
  .github/workflows/follow-merge-upstream-repo-sync.yml
  .github/workflows/release-cut-off-release-branch.yml
  .github/workflows/release-pipeline.yml
  .github/workflows/submodules-validator.yml
Labels: ci

#4416 ci: SRE-541: Local workflow call
  .github/workflows/bump-helm-chart.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/ff-command.yml
  .github/workflows/follow-merge-upstream-repo-sync.yml
  .github/workflows/release-cut-off-release-branch.yml
  .github/workflows/release-pipeline.yml
Labels: ci

#4417 ci: SRE-542: Use org vars for Docker Hub
  .github/workflows/docker-build-ontop.yml
  .github/workflows/docker-build-ubi.yml
  .github/workflows/docker-build.yml
  .github/workflows/docker-release-promote.yml
  .github/workflows/frontend-command.yml
Labels: ci

#4418 docs: Update logo to HumanSignal
  docs/_multiconfig.yml
  docs/source/guide/notion-faq.md
  docs/source/guide/release_notes.md
  docs/themes/v2/layout/partials/footer.ejs
  docs/themes/v2/source/css/styles.css
Labels: docs

#4420 Update labeling.md - Remove Audio hotkeys
  docs/source/guide/labeling.md
Labels: title needs formatting

#4433 fix: LSDV-5328: Data export tests
  label_studio/tests/conftest.py
  label_studio/tests/data_export.tavern.yml
Labels: fix

#4431 chore: LSDV-5321: Fix docs dependencies
  docs/package.json
Labels: chore

#4434 chore: LSDV-5321: Update package-lock.json
  docs/package-lock.json
  docs/source/guide/notion-faq.md
Labels: chore

#4435 chore: LSDV-5321: Use yarn.lock instead of npm
  .gitignore
  docs/.gitignore
  docs/package-lock.json
  docs/yarn.lock
Labels: chore

#4400 feat: LSDV-5243: Support $undefined$ resolving in html values for object tags
  label_studio/core/label_config.py
  label_studio/core/settings/base.py
  label_studio/data_import/uploader.py
  label_studio/tests/data_import.hypertext.tavern.yml
Labels: feat

#4292 fix: LSDV-5333: regression where variable 'total' was not defined.
  label_studio/data_import/uploader.py
  label_studio/tests/data_import/test_uploader.py
Labels: fix

#4430 fix: LSDV-5321: Upgrade vulnerable packages
  .github/workflows/tests.yml
  deploy/requirements.txt
Labels: fix

#4439 fix: LSDV-5340: Storage links creation for Remove duplicates
  label_studio/data_manager/actions/experimental.py
  label_studio/tests/data_import.hypertext.tavern.yml
Labels: fix

#4441 docs: Update algolia-crawler.yml and replace heartex.com with humansignal.com
  .github/workflows/algolia-crawler.yml
Labels: docs

#4394 fix: LSDV-5289: Prevent db deadlocks
  label_studio/projects/models.py
  label_studio/tasks/models.py
Labels: fix

#4447 fix: LSDV-5337: Pre-signed file proxy url clashing with already html encoded values causing errors in signature
  label_studio/data_import/api.py
  label_studio/io_storages/base_models.py
  label_studio/tests/conftest.py
  label_studio/tests/io_storages_presign_proxy.tavern.yml
  label_studio/tests/tasks/test_presign_storage_data.py
Labels: fix

#4341 fix: LSDV-5072: adds check that any redirects are not redirecting to an external host
  label_studio/tests/users.tavern.yml
  label_studio/users/views.py
Labels: fix
