Repository HumanSignal/label-studio, pull requests merged in 2023-07, with the labels that each got.

#4450 docs: Remove HumanSignal changelog from releases notes for now
  docs/package.json
  docs/scripts/release-notes.js
  docs/yarn.lock
Labels: docs

#4466 chore: LSDV-5366: Add docker unit testing workflow for Label Studio
  .dockerignore
  Dockerfile.testing
  Makefile
Labels: chore

#4458 chore: Unblock docs deploy
  docs/package.json
  docs/yarn.lock
Labels: chore

#4468 fix: LSDV-5366: Fix a couple unit tests that break due to perms of Label Studio volume
  .gitignore
  Dockerfile.testing
  label_studio/core/settings/base.py
  label_studio/tests/test_bulk_operations.py
  label_studio/tests/test_data/gen_tasks_and_annotations.py
  label_studio/tests/utils.py
Labels: fix

#4467 fix: LSDV-5289: Decrease lockiness of task update code
  label_studio/projects/mixins.py
  label_studio/projects/models.py
Labels: fix

#4470 docs: update yarn.lock file
  docs/yarn.lock
Labels: docs

#4474 fix: LSDV-5289: Remove subquery from is_labeled update
  label_studio/projects/models.py
Labels: fix

#4476 docs: Update README.md to use yarn install step
  README.md
  label_studio/frontend/README.md
Labels: docs

#4481 docs: Add archive workspace to enterprise documentation
  docs/source/guide/manage_projects.md
  docs/themes/v2/source/images/workspace-archive-expand.png
  docs/themes/v2/source/images/workspace-dropdown-menu.png
  docs/themes/v2/source/images/workspace-edit-modal.png
  docs/themes/v2/source/images/workspace-unarchive-menu.png
Labels: docs

#4488 fix: LSDV-5375: fix session and queue tests
  label_studio/tests/conftest.py
  label_studio/tests/sessions.tavern.yml
Labels: fix

#4483 fix: LSDV-5348: More robust and uniform SSRF defenses
  deploy/requirements.txt
  label_studio/core/settings/base.py
  label_studio/core/utils/contextlog.py
  label_studio/core/utils/exceptions.py
  label_studio/core/utils/io.py
  label_studio/data_import/uploader.py
  label_studio/feature_flags.json
  label_studio/ml/serializers.py
  label_studio/tests/data_import/test_uploader.py
  label_studio/tests/test_api.py
  label_studio/tests/test_core.py
  label_studio/tests/utils.py
Labels: fix

#4482 docs: LSDV-5366: Add documentation of testing container to readme
  README.md
Labels: title needs formatting, docs

#4506 fix: LOPS-221: Allow glob syntax in GCS connection validation
  label_studio/io_storages/gcs/utils.py
Labels: fix

#4436 fix: LSDV-4719: improve performance of project annotations
  label_studio/projects/functions/__init__.py
Labels: fix

#4486 docs: LSDV-5358: Add Generative AI templates
  docs/_config.yml
  docs/source/guide/notion-faq.md
  docs/source/guide/release_notes.md
  docs/source/templates/gallery_generative_ai.ejs
  docs/source/templates/generative-chatbot-assessment.md
  docs/source/templates/generative-llm-ranker.md
  docs/source/templates/generative-pairwise-human-preference.md
  docs/source/templates/generative-supervised-llm.md
  docs/source/templates/generative-visual-ranker.md
  docs/source/templates/get_started.md
  docs/source/templates/html_classification.md
  docs/source/templates/index.ejs
  docs/themes/v2/layout/partials/toc.ejs
Labels: documentation, docs

#4363 fix: LSDV-2775: fix predictions selector in next task with ML backend model version
  docs/source/guide/ml.md
  label_studio/ml/api_connector.py
  label_studio/ml/models.py
  label_studio/projects/models.py
  label_studio/tasks/serializers.py
  label_studio/tests/conftest.py
  label_studio/tests/ml.tavern.yml
  label_studio/tests/utils.py
Labels: fix

#4522 feat: LSDV-5391: Add API filter to search projects by title
  label_studio/projects/api.py
Labels: feat

#4511 fix: LSDV-5289: add FF to toggle long atomic transactions for perf/deadlocks reasons
  label_studio/core/utils/common.py
  label_studio/ml/models.py
  label_studio/projects/functions/next_task.py
  label_studio/projects/models.py
  label_studio/tasks/models.py
  label_studio/tests/test_block_objects.py
Labels: fix

#4495 feat: LSDV-5307: Import review and drafts from exported snapshots
  label_studio/tasks/migrations/0040_auto_20230628_1101.py
  label_studio/tasks/models.py
  label_studio/tasks/serializers.py
Labels: feat

#4527 fix: LSDV-5307: Import review and drafts from exported snapshots: Add tests, little fixes
  label_studio/tasks/serializers.py
Labels: fix

#4533 fix: LSDV-5410: Use flag to enable async Retrieve Prediction function in DataManager
  label_studio/core/redis.py
  label_studio/ml/models.py
Labels: fix

#4540 docs: Revert "docs: update yarn.lock file (#4470)"
  docs/yarn.lock
Labels: docs

#4551 fix: LSDV-5368: add project_defined annotations to all columns
  label_studio/data_manager/functions.py
  label_studio/tests/data_manager/test_columns_api.py
Labels: fix

#4561 fix: LSDV-5307: Fix user for FF in import
  label_studio/tasks/serializers.py
Labels: fix

#4567 fix: LSDV-5368: Revert "add project_defined annotations to all columns (#4551)"
  label_studio/data_manager/functions.py
  label_studio/tests/data_manager/test_columns_api.py
Labels: fix

#4564 docs: Fix details tags
  docs/package.json
  docs/yarn.lock
Labels: docs

#4573 docs: Update error in left:right mixup in documentation
  docs/source/guide/labeling.md
Labels: docs

#4555 docs: Note to clarify the rotation is around the (x,y) , not (cx,cy)
  docs/source/tags/rectanglelabels.md
Labels: community:reviewed, community:docs

#4574 docs: Update Enterprise API redirect
  docs/netlify.toml
Labels: docs

#4579 fix: LSDV-5458-1: Get model version from predictions
  label_studio/ml/models.py
Labels: fix

#4512 feat: LSDV-5370: Docs for transcription context
  docs/source/tags/paragraphs.md
  docs/source/templates/contextual_scrolling.md
  docs/source/templates/gallery_asr.ejs
  docs/themes/v2/source/images/templates-misc/contextual_scrolling.png
Labels: feat

#4575 docs: PROD-281: Document project search functionality
  docs/source/guide/manage_projects.md
  docs/themes/v2/source/images/search-clear-results.png
  docs/themes/v2/source/images/search-criteria-no-results.png
  docs/themes/v2/source/images/search-pinned-projects.png
  docs/themes/v2/source/images/search-projects-in-all-workspaces.png
  docs/themes/v2/source/images/search-projects-in-workspace.png
  docs/themes/v2/source/images/search-unpinned-projects.png
Labels: docs

#4570 docs: Add release notes for 2.4.9-2
  docs/scripts/release-notes.js
  docs/source/guide/release_notes.md
  docs/source/guide/release_notes/onprem/2.4.9-2.md
Labels: docs
