Repository HumanSignal/label-studio, pull requests merged in 2023-12, with the labels that each got.

#5126 docs: DOC-162: Fix LSE and LSO divisions in Setup project page
  docs/source/guide/setup_project.md
Labels: docs

#5113 feat: OPTIC-159: Task assignment for low agreement docs
  docs/source/guide/setup_project.md
  docs/source/guide/stats.md
Labels: feat

#5144 fix: LEAP-63: Migration with rqworker
  label_studio/tasks/migrations/0045_auto_20231124_1238.py
  label_studio/tasks/models.py
Labels: fix

#5148 docs: DOC-164: Remove low task agreement docs
  docs/source/guide/setup_project.md
  docs/source/guide/stats.md
Labels: docs

#5146 docs: DOC-124: Data Discovery docs
  docs/source/guide/dataset_manage.md
  docs/source/guide/dataset_overview.md
  docs/source/guide/dataset_search.md
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/images/data_discovery/add_tasks.png
  docs/themes/v2/source/images/data_discovery/dataset_settings.png
  docs/themes/v2/source/images/data_discovery/search_remove.png
  docs/themes/v2/source/images/data_discovery/semantic_search_flower.gif
  docs/themes/v2/source/images/data_discovery/similarity_score_filter.gif
  docs/themes/v2/source/images/data_discovery/similarity_search_lake.gif
Labels: docs

#5149 chore: Add some more Label Studio SDK unit tests
  label_studio/tests/sdk/common.py
  label_studio/tests/sdk/test_annotations.py
  label_studio/tests/sdk/test_projects.py
  label_studio/tests/sdk/test_storages.py
  label_studio/tests/sdk/test_tasks.py
  label_studio/tests/sdk/test_users.py
  label_studio/tests/sdk/test_views.py
  poetry.lock
  pyproject.toml
Labels: chore

#5136 fix: LEAP-346: Rework org token to use get_random_string instead of hash(time.time)
  label_studio/core/utils/common.py
  label_studio/organizations/models.py
  label_studio/projects/models.py
Labels: fix, Confirmed

#5156 fix: LEAP-448: stop using only() during migration
  label_studio/tasks/functions.py
Labels: fix

#5157 fix: LEAP-449: remove Project model from migration path
  label_studio/data_import/api.py
  label_studio/data_manager/actions/basic.py
  label_studio/projects/mixins.py
  label_studio/projects/models.py
  label_studio/tasks/functions.py
  label_studio/tasks/management/commands/calculate_stats.py
Labels: fix

#5125 feat: OPTIC-184: Remove is_deleted field from User model and manager
  label_studio/users/admin.py
  label_studio/users/migrations/0001_squashed_0009_auto_20210219_1237.py
  label_studio/users/migrations/0008_alter_user_managers.py
  label_studio/users/migrations/0009_auto_20231201_0001.py
  label_studio/users/models.py
Labels: feat, Confirmed

#5168 fix: OPTIC-184: Revert "feat: OPTIC-184: Remove is_deleted field from User model and manager"
  label_studio/users/admin.py
  label_studio/users/migrations/0001_squashed_0009_auto_20210219_1237.py
  label_studio/users/migrations/0008_alter_user_managers.py
  label_studio/users/migrations/0009_auto_20231201_0001.py
  label_studio/users/models.py
Labels: fix

#5165 chore: 2.8.0 Cherrypicking LEAP-448 and LEAP-449 Migration fixes
  label_studio/data_import/api.py
  label_studio/data_manager/actions/basic.py
  label_studio/projects/mixins.py
  label_studio/projects/models.py
  label_studio/tasks/functions.py
  label_studio/tasks/management/commands/calculate_stats.py
Labels: chore

#5181 chore: LEAP-463: Nearly empty diff to trigger followmerge
  label_studio/tests/conftest.py
Labels: chore

#5182 chore: Revert "fix: OPTIC-184: Revert "feat: OPTIC-184: Remove is_deleted fi…
  label_studio/users/admin.py
  label_studio/users/migrations/0001_squashed_0009_auto_20210219_1237.py
  label_studio/users/migrations/0008_alter_user_managers.py
  label_studio/users/migrations/0009_auto_20231201_0001.py
  label_studio/users/models.py
Labels: chore

#5185 ci: OPTIC-349: Poetry zip url instead of git
  .github/workflows/follow-merge-upstream-repo-sync-monorepo.yml
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#5188 ci: PLATE-775: ChatOps: Instant Workflow Run link
  .github/workflows/docker-command.yml
  .github/workflows/frontend-command.yml
  .github/workflows/git-command.yml
  .github/workflows/jira-command.yml
Labels: ci

#5135 feat: OPTIC-263: Putting webhooks on high queue
  label_studio/webhooks/utils.py
Labels: feat, Confirmed

#5189 ci: Fix docker ChatOps command notification
  .github/workflows/docker-command.yml
Labels: ci

#4472 fix: LSDV-5367: Cancelled and updated annotations don't recalculate
  label_studio/tasks/models.py
Labels: fix

#5212 docs: DOC-132: Release notes date fix
  docs/source/guide/release_notes/onprem/2.7.0-1.md
Labels: docs

#5216 docs: SCIM: remove sync passwords option from docs
  docs/source/guide/scim_setup.md
Labels: docs

#5204 fix: LEAP-408: Optimize storage export memory usage
  label_studio/core/settings/base.py
  label_studio/io_storages/base_models.py
Labels: fix

#5222 fix: DIA-783: Fix adding candidate task if it was accidentally deleted from project
  label_studio/data_manager/actions/basic.py
  label_studio/tasks/mixins.py
  label_studio/tasks/models.py
Labels: fix

#5228 fix: DIA-641: Fix unable to verify cloud connection
  label_studio/io_storages/azure_blob/form_layout.yml
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/azure_blob/serializers.py
  label_studio/io_storages/gcs/serializers.py
  label_studio/io_storages/s3/serializers.py
Labels: fix
