Repository HumanSignal/label-studio, pull requests merged in 2023-05, with the labels that each got.

#4127 feat: SRE-506: add info about real hostname
  label_studio/core/settings/base.py
Labels: feat

#4117 docs: LSDV-4714: Fix 404 links
  docs/source/guide/install_k8s.md
  docs/source/guide/security.md
  docs/source/tags/index.md
Labels: docs

#4118 chore: Remove redundant github issue template
  .github/ISSUE_TEMPLATE/custom.md
Labels: title needs formatting

#3975 feat: LSDV-4664: Implementing file delete
  label_studio/data_export/api.py
  label_studio/data_export/models.py
  label_studio/tests/data_export.tavern.yml
  label_studio/tests/utils.py
Labels: feat

#4142 ci: LSDV-4894: Migrate docker images to Yarn
  Dockerfile
  Dockerfile.redhat
Labels: ci

#3945 docs: 3944: local minio install
  README.md
  docker-compose.minio.yml
  docker-compose.yml
  docs/source/guide/storedata.md
  prometheus/minio/prometheus.yml
Labels: docs

#4034 feat: LSDV-4915: Async import
  label_studio/core/all_urls.json
  label_studio/core/redis.py
  label_studio/core/utils/common.py
  label_studio/data_import/README.md
  label_studio/data_import/api.py
  label_studio/data_import/functions.py
  label_studio/data_import/uploader.py
  label_studio/projects/api.py
  label_studio/projects/migrations/0022_projectimport.py
  label_studio/projects/models.py
  label_studio/projects/serializers.py
  label_studio/projects/urls.py
  label_studio/tests/conftest.py
Labels: feat

#4143 fix: LSDV-5036: Issue with cloud storage url causing errors and improperly created urls
  label_studio/data_export/api.py
  label_studio/data_import/api.py
Labels: fix

#4146 fix: LSDV-5036: Issue with cloud storage url causing errors and improperly created urls
  label_studio/data_import/api.py
Labels: fix

#4147 fix: LSDV-5036: Issue with cloud storage url causing errors and improperly created urls (#4143)
  label_studio/data_export/api.py
  label_studio/data_import/api.py
Labels: fix

#4076 fix: LOPS-76: Improve GCS storage endpoint to have clear error
  label_studio/io_storages/gcs/utils.py
  label_studio/tests/test_io_storages.py
Labels: fix

#4153 ci: SRE-509: Remove arm64 Docker build
  .github/workflows/docker-build.yml
Labels: ci

#4126 docs: LSDV-4714: Add free trial call to actions
  docs/_multiconfig.yml
  docs/source/guide/frontend_reference.md
  docs/source/guide/get_started.md
  docs/source/guide/install.md
  docs/source/guide/label_studio_compare.md
  docs/source/guide/ml.md
  docs/source/guide/notion-faq.md
  docs/source/playground/index.ejs
  docs/themes/v2/layout/page.ejs
  docs/themes/v2/source/css/styles.css
Labels: docs

#4171 chore: Fix frontend setup
  Makefile
  label_studio/frontend/package.json
  label_studio/frontend/yarn.lock
Labels: ci, chore

#4184 fix: Presigned storage tests
  label_studio/core/all_urls.json
  label_studio/tests/tasks/test_presign_storage_data.py
Labels: fix

#4180 feat: LSDV-3958: Server side encryption for Target Storage (AES256)
  label_studio/core/redis.py
  label_studio/io_storages/s3/models.py
  label_studio/tests/conftest.py
  label_studio/tests/io_storages.tavern.yml
Labels: feat

#4198 fix: LSDV-4974: Add storage status and debug: fix migration
  label_studio/io_storages/migrations/0014_init_statuses.py
Labels: fix

#4197 docs: LSDV-4880: Adding docs for labeling overlap
  docs/source/guide/labeling.md
Labels: docs

#4141 feat: LSDV-4702: Updating vulnerable deps and fixing cross depencies
  deploy/requirements.txt
Labels: feat

#4156 ci: SRE-478: Bump chart
  .github/workflows/bump-helm-chart.yml
  .github/workflows/release-pipeline.yml
Labels: ci

#4228 fix: LSDV-4913: Prediction results cannot be displayed immediately
  label_studio/data_manager/api.py
  label_studio/tasks/api.py
Labels: fix

#4234 ci: Remove obsolate LSF docs
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#4186 feat: LSDV-4941: Backend validation + sample-task for new Ranker
  label_studio/core/label_config.py
  label_studio/core/utils/schema/data_examples.json
  label_studio/core/utils/schema/label_config_schema.json
  label_studio/tasks/validation.py
Labels: feat

#4240 docs: Restore index page for tags documentation
  docs/source/tags/index.md
Labels: docs

#3744 fix: LSDV-4523: Show overlap first order
  label_studio/projects/functions/next_task.py
Labels: fix

#4243 fix: LSDV-5163: Storage errors AttributeError can't set attribute 'storage' when pre-signed proxy urls are turned on
  label_studio/data_import/api.py
  label_studio/tasks/models.py
Labels: fix

#3993 fix: LSDV-4821: Check labels in draft for config validation
  label_studio/core/utils/common.py
  label_studio/projects/migrations/0022_projectsummary_created_labels_drafts.py
  label_studio/projects/migrations/0023_merge_20230512_1333.py
  label_studio/projects/models.py
  label_studio/tasks/models.py
  label_studio/tests/config_validation.tavern.yml
Labels: fix

#4245 fix: LSDV-5178: Update django version to fix CVE-2023-31047
  deploy/requirements.txt
Labels: fix

#4267 fix: LSDV-5199: API docs redoc version updated to fix DOMPurify incompatibility
  label_studio/core/static/drf-yasg/redoc/redoc.min.js
Labels: fix

#4276 chore: Remove obsolete node-fetch
  .github/workflows/frontend-command.yml
  label_studio/frontend/get-build.js
Labels: chore

#4278 fix: LSDV-5208: Fix error with draft saving
  label_studio/projects/models.py
Labels: fix
