Repository HumanSignal/label-studio, pull requests merged in 2023-09, with the labels that each got.

#4726 fix: LSDV-5462: Add DATA_UPLOAD_MAX_NUMBER_FILES as environment variable
  label_studio/core/settings/base.py
  label_studio/core/utils/io.py
  label_studio/ml/serializers.py
Labels: fix

#4712 docs: LSDV-5550: Update ML docs to reflect performance improvement work
  docs/source/guide/ml.md
  docs/source/guide/ml_create.md
Labels: docs

#4610 fix: LSDV-4837: Upgrading swagger to address vulnerability
  deploy/requirements.txt
  label_studio/core/settings/base.py
  label_studio/core/urls.py
  label_studio/core/utils/common.py
Labels: fix

#4745 docs: LSDV-5553: Add styling for info/tip admonition
  docs/themes/v2/source/css/styles.css
  label_studio/core/version.py
Labels: docs

#4744 docs: Update Free Trial visual
  docs/source/guide/get_started.md
  docs/source/guide/install.md
  docs/source/guide/label_studio_compare.md
  docs/source/playground/index.ejs
  docs/themes/v2/layout/page.ejs
  docs/themes/v2/layout/partials/header.ejs
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/images/gradient.svg
Labels: docs

#4756 chore: cherry pick release fixes
  deploy/requirements.txt
  label_studio/core/settings/base.py
  label_studio/core/urls.py
  label_studio/core/utils/common.py
  label_studio/io_storages/base_models.py
Labels: chore

#4759 fix: LSDV-5554: Support prefix level access configs for S3 config validation
  label_studio/io_storages/s3/models.py
Labels: fix

#4762 fix: LSDV-5554: allow setting currently nonexistent prefix when configuring target storage
  label_studio/io_storages/s3/models.py
Labels: fix

#4743 docs: LSDV-5539: Clean up old LSE release notes
  docs/source/guide/release_notes.md
  docs/source/guide/release_notes/onprem/2.2.8.md
  docs/source/guide/release_notes/onprem/2.2.9.md
  docs/source/guide/release_notes/onprem/2.2.md
  docs/source/guide/release_notes/onprem/2.3.1.md
  docs/source/guide/release_notes/onprem/2.4.0.md
  docs/source/guide/release_notes/onprem/2.4.1.md
  docs/source/guide/release_notes/onprem/2.4.2.md
  docs/source/guide/release_notes/onprem/2.4.3.md
  docs/source/guide/release_notes/onprem/2.4.4.md
  docs/source/guide/release_notes/onprem/2.4.5.md
  docs/source/guide/release_notes/onprem/2.4.6-1.md
  docs/source/guide/release_notes/onprem/2.4.6.md
  docs/source/guide/release_notes/onprem/2.4.7.md
  docs/source/guide/release_notes/onprem/2.4.8-1.md
  docs/source/guide/release_notes/onprem/2.4.8.md
  docs/source/guide/release_notes/onprem/2.4.9-2.md
  docs/source/guide/release_notes/onprem/2.4.9-4.md
  docs/source/guide/release_notes/onprem/2.4.9-5.md
  docs/source/guide/release_notes/onprem/2.4.9-6.md
  docs/source/guide/release_notes/onprem/2.4.9-7.md
Labels: docs

#4639 perf: LSDV-4695: update Prediction model queries to take advantage of new direct project relation
  label_studio/projects/functions/__init__.py
  label_studio/projects/models.py
  label_studio/tasks/api.py
  label_studio/tasks/models.py
  label_studio/tasks/serializers.py
  label_studio/tests/test_predictions.py
  label_studio/tests/test_tasks_upload.py
Labels: perf

#4760 docs: DOC-113: Add information about code autocomplete
  docs/source/guide/setup.md
  docs/themes/v2/source/images/label/autocomplete.gif
Labels: docs

#4780 docs: Update release notes 2.4.10 with Helm chart info
  docs/source/guide/release_notes/onprem/2.4.10.md
Labels: docs

#4700 feat: OPTIC-44: Submit and exit docs
  docs/source/guide/labeling.md
  docs/themes/v2/source/images/submit-and-exit.png
Labels: feat

#4746 chore: LSDV-4606: use Django migration to define indexes
  label_studio/tasks/migrations/0044_auto_20230907_0155.py
  label_studio/tasks/models.py
Labels: chore

#4749 fix: OPTIC-104: Fixing packages
  .github/workflows/cicd_pipeline.yml
  .github/workflows/tests.yml
  deploy/requirements.txt
Labels: fix

#4810 docs: DOCS-117 Remove Slack ping requests from documentation
  docs/source/guide/tasks.md
  docs/source/templates/time_series.md
Labels: docs

#4808 docs: DOCS-115: Update open source contribution guide
  CONTRIBUTING.md
Labels: docs

#4812 fix: Annotation sync in storages with project
  label_studio/io_storages/base_models.py
Labels: fix

#4813 ci: PLATE-634: Add repo name to concurrency group
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#4772 fix: LSDV-5561: Fix updating drafts summary
  deploy/requirements-test.txt
  deploy/requirements.txt
  label_studio/tasks/api.py
  label_studio/tests/config_validation.tavern.yml
  label_studio/tests/conftest.py
  label_studio/tests/drafts.tavern.yml
Labels: fix

#4738 fix: LEAP-24: /api/tasks performance improvement
  label_studio/data_manager/api.py
  label_studio/data_manager/managers.py
Labels: fix

#4837 fix: OPTIC-140: Using pypi for human signal drf-yasg fork
  deploy/requirements.txt
Labels: fix

#4802 fix: LEAP-184: Fix created_labels_drafts handling and improve error display
  label_studio/data_manager/actions/basic.py
  label_studio/projects/models.py
  label_studio/tasks/models.py
  label_studio/tests/config_validation.tavern.yml
Labels: fix

#4836 docs: DOC-116: Create a page on upgrading Label Studio Enterprise
  docs/scripts/release-notes.js
  docs/source/guide/install_enterprise_k8s.md
  docs/source/guide/upgrade_enterprise.md
Labels: docs

#4842 chore: fix s3 export tests
  label_studio/tests/conftest.py
Labels: chore

#4846 docs: DOCS-132: Fix note formatting across files
  docs/source/guide/comments_notifications.md
  docs/source/guide/frontend.md
  docs/source/guide/frontend_reference.md
  docs/source/guide/install.md
  docs/source/guide/labeling.md
  docs/source/guide/manage_projects.md
  docs/source/guide/manage_users.md
  docs/source/guide/quality.md
  docs/source/guide/setup_project.md
  docs/source/guide/signup.md
Labels: docs

#4806 feat: OPTIC-115: Add is_deleted field to User model
  label_studio/users/migrations/0007_user_is_deleted.py
  label_studio/users/models.py
Labels: feat
