Repository HumanSignal/label-studio, pull requests merged in 2023-04, with the labels that each got.

#3961 feat: LSDV-4896: Show DM actions to reviewers
  label_studio/data_manager/actions/__init__.py
  label_studio/data_manager/actions/experimental.py
  label_studio/feature_flags.json
Labels: feat

#3725 fix: LSDV-3854-1: Add extension check
  label_studio/core/settings/base.py
  label_studio/data_import/uploader.py
  label_studio/tests/data_import.tavern.yml
  label_studio/tests/test_suites/samples/test.wrong_ext
  label_studio/tests/test_suites/samples/test_file_without_extension
Labels: fix

#3967 feat: LSDV-4826: AnnotationHistory deletion API, fix redis start func
  label_studio/core/redis.py
  label_studio/feature_flags.json
Labels: feat

#3968 docs: LSDV-4875: Small fixes in docs about storages
  docs/source/guide/storage.md
Labels: docs

#3972 ci: Unimpersonate user
  .github/workflows/feature-flags-update.yml
  .github/workflows/frontend-build.yml
Labels: ci

#3973 ci: Fix PR body dependency
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#3977 ci: SRE-477: implement migrate lock
  deploy/docker-entrypoint.d/common/30-run-db-migrations.sh
  deploy/docker-entrypoint.sh
  label_studio/core/management/commands/locked_migrate.py
Labels: ci

#3899 feat: LSDV-4813: Async export file conversion
  Makefile
  label_studio/core/all_urls.json
  label_studio/data_export/api.py
  label_studio/data_export/migrations/0006_convertedformat.py
  label_studio/data_export/migrations/0007_auto_20230327_1910.py
  label_studio/data_export/migrations/0008_convertedformat_traceback.py
  label_studio/data_export/models.py
  label_studio/data_export/serializers.py
  label_studio/data_export/urls.py
  label_studio/feature_flags.json
  label_studio/tests/data_export.tavern.yml
Labels: feat

#4009 feat: LSDV-4744, LSDV-4826: Activity log extra data removing and Annotation History removing for lse-release/2.4.5-1
  label_studio/core/redis.py
Labels: feat

#4018 fix: LDSV-4631: CSV and TSV exports work incorrectly, postfixes with read(1)
  deploy/requirements.txt
  label_studio/feature_flags.json
Labels: fix

#4028 ci: Disable FF update in PRs
  .github/workflows/cicd_pipeline.yml
Labels: ci

#4022 feat: LSDV-4932: Fix test to enable memory profiler
  label_studio/core/feature_flags/base.py
  label_studio/feature_flags.json
  label_studio/tests/conftest.py
Labels: feat

#4017 fix: LSDV-4920: Async conversion postfixes
  label_studio/data_export/api.py
  label_studio/data_export/models.py
  label_studio/data_export/serializers.py
Labels: fix

#4014 docs: LSDV-4880: Small docs fixes with misspells: update get_started.md
  docs/source/guide/get_started.md
Labels: docs

#4032 Update README.md
  README.md
Labels: title needs formatting

#4030 fix: LSDV-4920: Async conversion postfixes
  label_studio/data_export/api.py
  label_studio/data_export/migrations/0009_alter_convertedformat_traceback.py
Labels: fix

#4041 docs: LSDV-4775: Small fixes in storage docs
  docs/source/guide/storage.md
  docs/themes/v2/source/images/source-storages-treat-off.png
  docs/themes/v2/source/images/source-storages-treat-on.png
Labels: docs

#4049 fix: LSDV-4920: Download JSON without conversion
  label_studio/data_export/api.py
Labels: fix

#4054 docs: LSDV-4880: Small docs fixes: update rqworker capacity planning
  docs/source/guide/install_enterprise_k8s.md
Labels: docs

#4011 feat: LOPS-88: Add utils to get GCS object metadata
  label_studio/io_storages/gcs/utils.py
Labels: feat

#4071 ci: SRE-491: Add Conda install
  .github/workflows/cicd_pipeline.yml
  .github/workflows/test_conda.yml
Labels: ci

#4040 fix: LSDV-4920: Async conversion trace
  label_studio/data_export/api.py
Labels: fix

#4038 feat: LSDV-4965: Adding Generative AI section in templates gallery
  label_studio/annotation_templates/generative-ai/chatbot-assessment/config.yml
  label_studio/annotation_templates/generative-ai/human-feedback-collection/config.yml
  label_studio/annotation_templates/generative-ai/supervised-llm/config.yml
  label_studio/annotation_templates/groups.txt
  label_studio/core/static/templates/generative-chatbot-assessment.png
  label_studio/core/static/templates/generative-pairwise-human-preference.png
  label_studio/core/static/templates/generative-supervised-llm.png
Labels: feat

#4048 fix: LSDV-4895: Line breaks in instructions modal
  label_studio/frontend/dist/react-app/main.css
  label_studio/frontend/dist/react-app/main.css.map
  label_studio/frontend/src/components/Modal/Modal.styl
Labels: fix

#4073 docs: LSDV-4880: Small docs fixes with misspells: update LS comparison
  docs/scripts/release-notes.js
  docs/source/guide/label_studio_compare.md
  docs/source/guide/notion-faq.md
  docs/source/guide/release_notes.md
  docs/source/guide/release_notes/onprem/2.4.4.md
  docs/source/guide/start.md
Labels: docs

#4100 fix: LSDV-4711: Presigned proxy redirect should not cache
  label_studio/data_import/api.py
  label_studio/tasks/models.py
Labels: fix

#4101 fix: LSDV-4711: Presigned proxy redirect should not cache (#4100)
  label_studio/data_import/api.py
  label_studio/tasks/models.py
Labels: fix

#4102 ci: SRE-358: Migrate from ubuntu-20.04
  .github/workflows/test_migrations.yml
  .github/workflows/tests.yml
Labels: ci

#4104 ci: SRE-358: Migrate from ubuntu-20.04
  .github/workflows/test_migrations.yml
  .github/workflows/tests.yml
Labels: ci
