Repository HumanSignal/label-studio, pull requests merged in 2023-02, with the labels that each got.

#3631 fix: Add s3 custom endpoints support (#3618)
  label_studio/core/settings/base.py
Labels: fix

#3628 feat: LSDV-2973: Add polygon support in YOLO export
  deploy/requirements.txt
  label_studio/tests/export.tavern.yml
Labels: feat, breaking

#3594 fix: LSDV-1044: Check annotations exist in postpone
  label_studio/projects/functions/next_task.py
Labels: fix

#3641 ci: SRE-407: Split UBI Docker release pipeline
  .github/workflows/docker-build-ubi.yml
  .github/workflows/docker-build.yml
  .github/workflows/docker-release-promote.yml
  .github/workflows/release-pipeline.yml
Labels: ci, breaking

#3634 fix: DEV-4058: Add Google project ID to Source/Target GCS form
  label_studio/io_storages/gcs/form_layout.yml
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/migrations/0011_gcsstoragemixin_google_project_id.py
Labels: fix, breaking

#3453 feat: DEV-4058: User-defined Google Project ID for Import/Target storage connector
  label_studio/io_storages/gcs/form_layout.yml
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/migrations/0011_gcsstoragemixin_google_project_id.py
Labels: feat

#3610 feat: issue #3589: support url signing for all valid elements in array
  label_studio/io_storages/base_models.py
Labels: feat, breaking

#3646 fix: Next task with drafts optimizations
  deploy/requirements-test.txt
  label_studio/projects/functions/next_task.py
  label_studio/tests/tasks/test_functions.py
  label_studio/tests/test_next_task.py
Labels: fix

#3652 fix: Migration total_annotation dependency fix in data_manager
  label_studio/data_manager/migrations/0008_manual_counters_update.py
Labels: fix

#3616 fix: LSDV-3029: Add logging for last_login check
  label_studio/core/middleware.py
Labels: fix

#3650 fix: #3649: display number of projects list per page
  label_studio/frontend/src/pages/Projects/Projects.js
Labels: fix, breaking

#3630 fix: LSDV-1311: Don't touch output image filename
  deploy/requirements.txt
Labels: fix

#3682 fix: Resolve task data with array of dicts with URIs
  label_studio/data_manager/api.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/utils.py
  label_studio/tasks/api.py
  label_studio/tasks/models.py
Labels: fix

#3642 feat: LSDV-3936: Task history is stored on the backend
  Makefile
  label_studio/core/all_urls.json
  label_studio/core/settings/base.py
  label_studio/projects/api.py
  label_studio/projects/functions/next_task.py
  label_studio/projects/functions/stream_history.py
  label_studio/projects/migrations/0019_labelstreamhistory.py
  label_studio/projects/migrations/0020_labelstreamhistory_unique_history.py
  label_studio/projects/models.py
  label_studio/projects/urls.py
  label_studio/tasks/api.py
  label_studio/tests/conftest.py
  label_studio/tests/shared_stages.yml
  label_studio/tests/test_stream_history.tavern.yml
Labels: feat

#3695 fix: LSDV-3074: Ignore feature flag file in git
  .gitignore
Labels: fix

#3588 fix: DEV-4084: Bad gateway at api/projects and performance fix for annotation.project joins
  label_studio/core/feature_flags/base.py
  label_studio/core/utils/db.py
  label_studio/data_export/models.py
  label_studio/data_export/serializers.py
  label_studio/data_manager/actions/experimental.py
  label_studio/data_manager/api.py
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/localfiles/models.py
  label_studio/io_storages/redis/models.py
  label_studio/io_storages/s3/models.py
  label_studio/labels_manager/functions.py
  label_studio/organizations/serializers.py
  label_studio/projects/functions/__init__.py
  label_studio/projects/functions/next_task.py
  label_studio/projects/migrations/0019_project_project_pinned__a39ccb_idx.py
  label_studio/projects/models.py
  label_studio/projects/serializers.py
  label_studio/tasks/api.py
  label_studio/tasks/migrations/0038_auto_20230209_1412.py
  label_studio/tasks/models.py
  label_studio/tests/test_annotations.py
  label_studio/tests/test_next_task.py
  label_studio/users/models.py
  label_studio/webhooks/models.py
Labels: fix

#3704 fix: DEV-4084: Migration conflict in projects django app
  label_studio/projects/migrations/0021_merge_20230215_1943.py
Labels: fix

#3708 fix: LSDV-4633: Opensource LS init with username and password doesn't work in docker
  deploy/docker-entrypoint.d/app/31-run-label-studio-init.sh
  label_studio/core/argparser.py
  label_studio/server.py
Labels: fix

#3673 feat: LSDV-4614: API call to retrieve project file uploads
  label_studio/data_import/api.py
  label_studio/tests/data_import.tavern.yml
Labels: feat, breaking

#3715 docs: update links and language README.md
  README.md
Labels: docs, breaking

#3690 fix: LSDV-3856: Add get_parent_object mixin
  label_studio/core/mixins.py
  label_studio/core/settings/base.py
  label_studio/core/utils/common.py
  label_studio/core/utils/get_object.py
  label_studio/data_export/api.py
  label_studio/data_manager/api.py
  label_studio/io_storages/api.py
  label_studio/ml/api.py
  label_studio/organizations/api.py
  label_studio/organizations/models.py
  label_studio/projects/api.py
  label_studio/projects/views.py
  label_studio/tasks/api.py
  label_studio/tasks/serializers.py
Labels: fix

#3691 feat: LSDV-4583-5 Add valueList validation
  label_studio/core/utils/schema/label_config_schema.json
Labels: feat

#3728 docs: Add release notes for 2.4.2
  docs/source/release_notes/2.4.2.md
Labels: docs, breaking

#3733 docs: Change release notes parent dir
  docs/source/guide/release_notes/onprem/2.4.2.md
Labels: docs, breaking

#3741 ci: Changelog 1.1
  .github/helpers/gh_changelog_generator/.gitignore
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
  .github/helpers/gh_changelog_generator/requirements.txt
  .github/helpers/gh_jira_comparisonator/gh_jira_releases.py
  .github/helpers/gh_jira_comparisonator/requirements.txt
  .github/workflows/cicd_pipeline.yml
Labels: ci, breaking

#3745 ci: Fix LaunchDarkly env link
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
  .github/workflows/cicd_pipeline.yml
Labels: ci, breaking

#3752 docs: Add ML backend timeouts in Label Studio
  docs/source/guide/ml_troubleshooting.md
Labels: docs, breaking

#3753 docs: Improve dynamic Choices example, add html attribute
  docs/source/tags/choices.md
  docs/source/tags/image.md
  docs/source/tags/video.md
Labels: docs
