Repository HumanSignal/label-studio, pull requests merged in 2024-06, with the labels that each got.

#5945 fix: DIA-1035: Allow Manager role to add/remove prompts API keys
  label_studio/ml_model_providers/models.py
Labels: fix

#5946 docs: DOC-218: Update SDK page
  docs/source/guide/sdk.md
Labels: docs

#5948 docs: DOC-218: Add links updated and old doc url
  docs/source/guide/sdk.md
Labels: docs

#5951 fix: LEAP-1136: put data import operations on high priority queue
  label_studio/data_import/api.py
Labels: fix

#5949 docs: changing api links
  docs/source/guide/api.md
  docs/source/guide/ml.md
  docs/source/guide/release_notes.md
  docs/source/guide/sdk.md
  docs/source/guide/storage.md
  docs/themes/v2/layout/partials/header.ejs
Labels: docs

#5769 feat: LEAP-1119: Feature/gridview thumbnail
  web/libs/datamanager/__mocks__/fileMock.ts
  web/libs/datamanager/jest.config.ts
  web/libs/datamanager/src/components/MainView/GridView/GridView.jsx
  web/libs/datamanager/src/components/MainView/GridView/__tests__/GridView.test.tsx
Labels: feat, Community, community:fix

#5950 feat: DIA-1064: Get all / sample tasks for prompts task list
  label_studio/ml_models/migrations/0006_alter_modelrun_project_subset.py
  label_studio/ml_models/models.py
Labels: feat

#5925 fix: RND-77: Create idiomatic method names for sdk
  label_studio/core/views.py
  label_studio/data_export/api.py
  label_studio/data_import/api.py
  label_studio/data_manager/api.py
  label_studio/io_storages/all_api.py
  label_studio/io_storages/azure_blob/api.py
  label_studio/io_storages/gcs/api.py
  label_studio/io_storages/localfiles/api.py
  label_studio/io_storages/redis/api.py
  label_studio/io_storages/s3/api.py
  label_studio/labels_manager/api.py
  label_studio/ml/api.py
  label_studio/organizations/api.py
  label_studio/projects/api.py
  label_studio/tasks/api.py
  label_studio/tasks/openapi_schema.py
  label_studio/tasks/serializers.py
  label_studio/users/api.py
  label_studio/webhooks/api.py
Labels: fix

#5961 fix: RND-86: Upgrade LS to use label-studio-sdk=1.0
  .github/workflows/follow-merge-upstream-repo-sync.yml
  label_studio/core/label_config.py
  label_studio/core/utils/common.py
  label_studio/data_export/mixins.py
  label_studio/data_export/models.py
  label_studio/data_export/serializers.py
  label_studio/projects/models.py
  label_studio/tests/export.tavern.yml
  poetry.lock
  pyproject.toml
Labels: fix

#5471 chore: update minio
  docker-compose.minio.yml
Labels: chore

#5405 fix: Get host for curl usage example
  label_studio/users/templates/users/user_account.html
Labels: Stale, fix

#5972 fix: RND-93: Exclude payload from DELETE all tasks response
  label_studio/projects/api.py
Labels: fix

#5963 fix: RND-88: Fix args and improve descriptions for storage validate
  label_studio/io_storages/azure_blob/api.py
  label_studio/io_storages/azure_blob/openapi_schema.py
  label_studio/io_storages/gcs/api.py
  label_studio/io_storages/gcs/openapi_schema.py
  label_studio/io_storages/localfiles/api.py
  label_studio/io_storages/localfiles/openapi_schema.py
  label_studio/io_storages/redis/api.py
  label_studio/io_storages/redis/openapi_schema.py
  label_studio/io_storages/s3/api.py
  label_studio/io_storages/s3/openapi_schema.py
  label_studio/projects/api.py
  label_studio/tasks/serializers.py
Labels: fix

#5976 fix: RND-93: Fix response schema for delete_all_tasks
  label_studio/projects/api.py
Labels: fix

#5971 feat: OPTIC-800: introducing stale feature flags
  label_studio/core/feature_flags/base.py
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: feat

#5947 docs: Edit favicon
  docs/themes/v2/source/images/favicon.ico
  docs/themes/v2/source/images/favicon.svg
Labels: docs

#5975 fix: RND-94: Fix API docs for actions.create() and prepare params in DM
  label_studio/core/utils/common.py
  label_studio/data_manager/api.py
  label_studio/data_manager/functions.py
  label_studio/data_manager/prepare_params.py
  label_studio/tasks/api.py
Labels: fix

#5968 fix: LEAP-860: have GCS generate data URLs if presign is disabled
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/gcs/utils.py
Labels: fix, Confirmed

#5552 fix: Add missing storage title field to Redis config
  label_studio/io_storages/redis/form_layout.yml
Labels: fix, Community, community:reviewed, community:fix

#5988 ci: PLT-366: Build frontend static in develop/release
  .github/workflows/cicd_pipeline.yml
  .github/workflows/frontend-build.yml
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/version.json
Labels: ci

#5711 feat: LEAP-1020: Relation side panel improvements
  web/libs/editor/src/components/SidePanels/DetailsPanel/DetailsPanel.styl
  web/libs/editor/src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/Relations.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RelationsControls.styl
  web/libs/editor/src/components/SidePanels/DetailsPanel/RelationsControls.tsx
  web/libs/editor/src/stores/RelationStore.js
  web/libs/editor/tests/integration/e2e/relations/hide-all.cy.ts
  web/libs/editor/tests/integration/e2e/relations/order.cy.ts
  web/libs/frontend-test/src/helpers/LSF/Relations.ts
Labels: feat, Community, community:fix

#5991 fix: Return users in project.all_members()
  label_studio/projects/mixins.py
  label_studio/tests/test_project.py
Labels: fix

#5982 fix: RND-97: Support for multiple ML backend predictions per task
  label_studio/ml/models.py
  label_studio/tests/data_manager/test_api_actions.py
  label_studio/tests/ml/test_predict.py
  label_studio/tests/sdk/test_ml.py
Labels: fix

#5994 fix: RND-97: Revert missed import in tests
  label_studio/tests/sdk/test_ml.py
Labels: fix

#5996 fix: LEAP-1161: fix User import in mixin
  label_studio/projects/mixins.py
  label_studio/tests/conftest.py
  label_studio/tests/ml/test_predict.py
  label_studio/tests/sdk/test_ml.py
  label_studio/tests/test_project.py
Labels: fix

#5997 docs: DOC-210: Add info to section on allowing ML backend access
  docs/source/guide/ml.md
Labels: docs

#6003 docs: Remove line breaks to match GitHub markdown rendering
  docs/_config.yml
Labels: docs

#6009 chore: Change the audio url for tests to a local one to avoid connection issues which cause test flakes
  web/libs/editor/tests/e2e/examples/audio-paragraphs.js
  web/libs/editor/tests/e2e/examples/audio-regions.js
  web/libs/editor/tests/e2e/examples/classification.js
  web/libs/editor/tests/e2e/examples/text-paragraphs.js
  web/libs/editor/tests/e2e/tests/audio/audio-controls.test.js
  web/libs/editor/tests/e2e/tests/audio/audio-regions.test.js
  web/libs/editor/tests/e2e/tests/audio/audio-webaudio-decoder.test.js
  web/libs/editor/tests/e2e/tests/maxUsage.test.js
  web/libs/editor/tests/e2e/tests/paragraphs-filter.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/hotkey.test.js
  web/libs/editor/tests/e2e/tests/shortcuts.test.js
  web/libs/editor/tests/e2e/tests/sync/audio-paragraphs.test.js
  web/libs/editor/tests/e2e/tests/sync/audio-video-paragraphs.test.js
  web/libs/editor/tests/e2e/tests/sync/multiple-audio.test.js
  web/libs/editor/tests/integration/data/audio/audio_paragraphs.ts
  web/libs/editor/tests/integration/e2e/audio/audio.cy.ts
Labels: chore

#5986 docs: Fix broken link
  docs/source/guide/install.md
Labels: docs, Community, community:docs

#6013 fix: LEAP-1169: LEAP-1165: LEAP-1177 Fix security issues
  web/libs/editor/tests/e2e/package.json
  web/libs/editor/tests/e2e/yarn.lock
  web/package.json
  web/yarn.lock
Labels: fix, Confirmed

#6023 docs: Add scrolling if the sidebar is too tall
  docs/themes/v2/source/css/styles.css
Labels: docs

#5979 feat: 5525: Closes Pydantic 2.0 Migration / Support
  label_studio/core/permissions.py
  label_studio/data_manager/managers.py
  pyproject.toml
Labels: feat

#6024 chore: Update LS to the latest SDK 1.0.2
  label_studio/core/permissions.py
  label_studio/data_manager/managers.py
  poetry.lock
  pyproject.toml
Labels: chore

#6012 fix: RND-98: correct response schema for tasks.get()
  label_studio/data_manager/serializers.py
  label_studio/tasks/api.py
  label_studio/tasks/openapi_schema.py
  label_studio/tests/sdk/test_tasks.py
Labels: fix

#6014 feat: OPTIC-791: Update model run stats to be based on total tasks, predictions, and ground truths rather than the current page of tasks
  label_studio/ml_models/migrations/0007_auto_20240617_2200.py
  label_studio/ml_models/migrations/0008_modelrun_total_tasks.py
  label_studio/ml_models/models.py
Labels: feat

#6032 fix: RND-102: Ensure SDK compatibility with LSE
  label_studio/projects/api.py
  label_studio/tests/conftest.py
  label_studio/tests/ml/test_predict.py
  label_studio/tests/sdk/test_ml.py
  label_studio/tests/sdk/test_projects.py
  label_studio/tests/sdk/test_tasks.py
  poetry.lock
  pyproject.toml
Labels: fix

#6005 fix: LEAP-453: Fix annotation and draft being requested at the same time
  web/libs/editor/src/stores/AppStore.js
Labels: fix, Confirmed

#6034 chore: LEAP-1192: Remove feat_front_dev_4008_quick_task_open_short
  web/libs/datamanager/src/components/MainView/DataView/Table.jsx
  web/libs/datamanager/src/utils/feature-flags.js
Labels: chore
