Repository HumanSignal/label-studio, pull requests merged in 2024-12, with the labels that each got.

#6735 fix: OPTIC-1407: Optimize the tasks API paginated prediction and annotation totals
  label_studio/data_manager/api.py
Labels: fix, Confirmed

#6738 docs: Add security section about storages and VPC
  docs/source/guide/security.md
  docs/source/guide/storage.md
  docs/themes/v2/source/images/storages/cloud-storage-ip-restriction.jpg
  docs/themes/v2/source/images/storages/cloud-storage-vpn.jpg
Labels: docs

#6732 refactor: LEAP-1314: Remove Stale Feature Flag - fflag_feat_front_dev…
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/datamanager/src/components/Common/Table/TableHead/TableHead.jsx
  web/libs/datamanager/src/utils/feature-flags.js
Labels: refactor

#6742 chore: OPTIC-1413: Add internal tracking of Heidi Tips
  label_studio/users/templates/users/new-ui/user_tips.html
  web/apps/labelstudio/src/components/HeidiTips/HeidiTip.tsx
  web/apps/labelstudio/src/components/HeidiTips/HeidiTips.tsx
  web/apps/labelstudio/src/components/HeidiTips/hooks.ts
  web/apps/labelstudio/src/components/HeidiTips/types.ts
  web/apps/labelstudio/src/components/HeidiTips/utils.ts
  web/libs/core/src/lib/utils/analytics.ts
Labels: chore, Confirmed

#6744 refactor: LEAP-1308: Remove Stale Feature Flag - ff_back_dev_3865_filters_anno_171222_short
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6753 refactor: LEAP-1308: REVERT Remove Stale Feature Flag - ff_back_dev_3865_filters_anno_171222_short
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6203 feat: LEAP-1351: LSF customization for bulk annotation
  web/libs/editor/src/components/App/App.jsx
  web/libs/editor/src/components/BottomBar/Actions.jsx
  web/libs/editor/src/components/BottomBar/Controls.tsx
  web/libs/editor/src/components/BottomBar/buttons.tsx
  web/libs/editor/src/components/TopBar/Actions.jsx
  web/libs/editor/src/components/TopBar/TopBar.jsx
  web/libs/editor/src/core/Tree.tsx
  web/libs/editor/src/stores/AppStore.js
  web/libs/editor/src/stores/CustomButton.ts
  web/libs/editor/src/stores/types.d.ts
  web/libs/editor/src/tags/control/Choice.jsx
  web/libs/editor/src/tags/control/ClassificationBase.js
  web/libs/editor/src/tags/visual/Collapse.jsx
  web/libs/editor/src/tags/visual/Filter.jsx
  web/libs/editor/src/tags/visual/Style.jsx
  web/libs/editor/src/tags/visual/View.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/integration/data/bulk_mode/smoke.ts
  web/libs/editor/tests/integration/e2e/bulk_mode/smoke.cy.ts
  web/libs/editor/tests/integration/e2e/core/bottom_bar.cy.ts
  web/libs/frontend-test/src/helpers/LSF/Collapse.ts
  web/libs/frontend-test/src/helpers/LSF/LabelStudio.ts
  web/libs/frontend-test/src/helpers/LSF/Labels.ts
  web/libs/frontend-test/src/helpers/LSF/Paragraphs.ts
  web/libs/frontend-test/src/helpers/LSF/Ranker.ts
  web/libs/frontend-test/src/helpers/LSF/Table.ts
  web/libs/frontend-test/src/helpers/LSF/TimeSeries.ts
  web/libs/frontend-test/src/helpers/LSF/ToolBar.ts
  web/libs/frontend-test/src/helpers/LSF/index.ts
  web/libs/frontend-test/src/helpers/utils/fixLSParams.ts
Labels: feat

#6736 feat: OPTIC-1360: [BE] create Account settings endpoints that handle existing functionality in the django template
  label_studio/organizations/api.py
  label_studio/organizations/serializers.py
  label_studio/tests/test_organizations.py
  label_studio/tests/webhooks/organizations.tavern.yml
  label_studio/users/serializers.py
  poetry.lock
  pyproject.toml
Labels: feat

#6726 fix: LEAP-1651: Properly update meta text for regions
  web/libs/editor/src/components/Entity/Entity.jsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionDetails.tsx
  web/libs/editor/src/mixins/Normalization.ts
  web/libs/editor/src/regions/Result.js
  web/libs/editor/src/tags/control/TextArea/TextArea.jsx
Labels: fix, Confirmed

#6761 ci: LEAP-1676: LEAP-1677: LEAP-1674: LEAP-1673: Upgrade cross-spawn version
  web/yarn.lock
Labels: ci, Confirmed

#6762 ci: LEAP-1565: LEAP-1566: LEAP-1567: Upgrade cookie version
  web/package.json
  web/yarn.lock
Labels: ci, Confirmed

#6760 fix: LEAP-1610: fix is_labeled calculation if overlap enabled
  label_studio/tasks/models.py
Labels: fix

#6770 ci: LEAP-1567: Upgrade cookie version
  web/libs/editor/tests/e2e/package.json
  web/libs/editor/tests/e2e/yarn.lock
Labels: ci, Confirmed

#6563 docs: Change link to label-studio-sdk/converter in README.md
  README.md
Labels: Stale, docs, fix

#6757 fix: LEAP-1352: API for Bulk Annotation Configuration Validation
  label_studio/projects/serializers.py
  label_studio/tests/config_validation.tavern.yml
Labels: fix, Confirmed

#6614 chore: BEG-7: Django 5 upgrade
  .github/workflows/tests.yml
  label_studio/core/settings/base.py
  label_studio/data_manager/managers.py
  poetry.lock
  pyproject.toml
Labels: chore

#6790 docs: Update cta buttons for humansignal on enterprise and opensource
  docs/source/guide/release_notes.md
  docs/source/playground/index.ejs
  docs/themes/v2/layout/page.ejs
  docs/themes/v2/source/css/styles.css
Labels: docs

#6780 fix: OPTIC-1418: Improve Organization Membership API usage to reduce latency
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/utils/api-proxy/index.js
Labels: fix, Confirmed

#6769 feat: OPTIC-1350: [BE] Create API to return project counts
  label_studio/core/all_urls.json
  label_studio/projects/api.py
  label_studio/projects/serializers.py
  label_studio/projects/urls.py
  label_studio/tests/test_project.py
Labels: feat

#6795 fix: LEAP-1727: less info on version page
  label_studio/core/views.py
Labels: fix

#6797 chore: OPTIC-1061: Improve webpack bundle management so bundles can be cached more effectively
  label_studio/core/templatetags/filters.py
  label_studio/core/urls.py
  label_studio/core/utils/manifest_assets.py
  label_studio/core/utils/static_serve.py
  label_studio/templates/base.html
  label_studio/templates/simple.html
Labels: chore, Confirmed

#6803 docs: SAML SSO role fix
  docs/source/guide/auth_setup.md
Labels: docs

#6704 fix: OPTIC-1178: Possible LS Memory Leak
  web/libs/datamanager/src/components/App/App.jsx
  web/libs/datamanager/src/components/CellViews/Agreement/Agreement.jsx
  web/libs/datamanager/src/components/CellViews/Annotators/Annotators.jsx
  web/libs/datamanager/src/components/Common/AnnotationPreview/AnnotationPreview.jsx
  web/libs/datamanager/src/components/Common/Dropdown/DropdownComponent.jsx
  web/libs/datamanager/src/components/Common/Form/Form.jsx
  web/libs/datamanager/src/components/Common/Icon/Icon.jsx
  web/libs/datamanager/src/components/Common/Menu/Menu.jsx
  web/libs/datamanager/src/components/Common/Table/Table.jsx
  web/libs/datamanager/src/components/Common/Table/TableCell/TableCell.jsx
  web/libs/datamanager/src/components/Common/Table/TableContext.js
  web/libs/datamanager/src/components/Common/Table/TableHead/TableHead.jsx
  web/libs/datamanager/src/components/Common/Table/TableRow/TableRow.jsx
  web/libs/datamanager/src/components/Common/Tabs/Tabs.jsx
  web/libs/datamanager/src/components/Common/Userpic/Userpic.jsx
  web/libs/datamanager/src/components/DataManager/DataManager.jsx
  web/libs/datamanager/src/components/MainView/GridView/GridView.jsx
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/utils/bem.tsx
  web/libs/datamanager/src/utils/feature-flags.js
  web/libs/editor/src/components/App/App.jsx
  web/libs/editor/src/components/BottomBar/Controls.tsx
  web/libs/editor/src/components/InstructionsModal/InstructionsModal.tsx
  web/libs/editor/src/components/Settings/Settings.jsx
Labels: fix, Confirmed

#6781 feat: LEAP-1424: LEAP-1370: Allow to zoom and pan the image in preview modal
  web/libs/datamanager/src/components/Common/Table/utils.js
  web/libs/datamanager/src/components/MainView/GridView/GridPreview.module.scss
  web/libs/datamanager/src/components/MainView/GridView/GridPreview.tsx
  web/libs/datamanager/src/components/MainView/GridView/GridView.jsx
  web/libs/datamanager/src/components/MainView/GridView/ImagePreview.tsx
  web/libs/datamanager/src/utils/feature-flags.js
Labels: feat

#6785 fix: OPTIC-1420: Inner IDs are duplicated and counted wrong
  label_studio/tasks/serializers.py
Labels: fix

#6814 chore: OPTIC-1121: Removing Vite dependencies as they are unused
  web/package.json
  web/yarn.lock
Labels: chore, Confirmed
