Repository HumanSignal/label-studio, pull requests merged in 2024-02, with the labels that each got.

#5363 fix: OPTIC-101: Project pagination copy is cut off on LS when user opens project and navigates back to Projects page
  web/apps/labelstudio/src/components/Pagination/Pagination.styl
  web/dist/apps/labelstudio/main.css
  web/dist/apps/labelstudio/main.css.map
  web/dist/apps/labelstudio/main.js
Labels: fix, Confirmed

#5413 fix: DIA-825: Fix stylus build issue
  web/apps/labelstudio/src/themes/default/colors.styl
  web/dist/apps/labelstudio/main.js
Labels: fix

#5414 docs: DOC-183: Move troubleshooting docs to support center articles
  docs/source/guide/FAQ.md
  docs/source/guide/custom_metric.md
  docs/source/guide/import_troubleshoot.md
  docs/source/guide/ml.md
  docs/source/guide/ml_troubleshooting.md
  docs/source/guide/predictions.md
  docs/source/guide/project_troubleshoot.md
  docs/source/guide/quality_troubleshoot.md
  docs/source/guide/storage.md
  docs/source/guide/tasks.md
Labels: docs

#5418 docs: Add troubleshooting link in the sidebar
  docs/themes/v2/layout/partials/toc.ejs
  docs/themes/v2/source/css/styles.css
Labels: docs

#5420 docs: DOC-188: Fix broken links on project setup page
  docs/source/guide/setup_project.md
Labels: docs

#5431 docs: DOC-132: Small fixes to title of backup page for LSE
  docs/source/guide/backup_enterprise.md
Labels: docs

#5433 docs: DOC-168: Create Administration section in the docs
  docs/source/guide/admin_logs.md
  docs/source/guide/admin_manage.md
  docs/source/guide/admin_manage_lse.md
  docs/source/guide/admin_roles.md
  docs/source/guide/admin_user.md
  docs/source/guide/auth_setup.md
  docs/source/guide/billing.md
  docs/source/guide/manage_users.md
  docs/source/guide/saas.md
  docs/source/guide/scim_setup.md
  docs/source/guide/scim_workflow.md
  docs/source/guide/signup.md
  docs/source/guide/user_account.md
  docs/themes/v2/layout/partials/toc.ejs
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/images/admin/account_settings.png
  docs/themes/v2/source/images/admin/assign_role.png
  docs/themes/v2/source/images/admin/org_menu.png
Labels: docs

#5442 docs: DOC-192: Remove references to LSF repo
  docs/source/guide/get_started.md
  docs/source/guide/labeling.md
Labels: docs

#5451 chore: LEAP-622: upgrade EOL'd launchdarkly sdk
  poetry.lock
  pyproject.toml
Labels: chore

#5441 docs: DOC-190: Updated LSE installation overview with new diagram
  docs/source/guide/install_enterprise.md
  docs/themes/v2/source/images/LSE_k8s_scheme.png
Labels: docs

#5461 chore: LEAP-647: upgrade cryptography and django
  poetry.lock
  pyproject.toml
Labels: chore

#5468 ci: PLATE-840: Add wheel size check
  .github/workflows/build_pypi.yml
  .github/workflows/release-pipeline.yml
Labels: ci

#5469 ci: PLATE-856: Add post hotfix release name support
  docs/scripts/release-notes.js
Labels: ci

#5479 docs: DOC-132: Update page template
  docs/scaffolds/page.md
Labels: docs

#5315 fix: OPTIC-362: Ensure that count queries use strict select values
  label_studio/data_manager/api.py
Labels: fix, Confirmed

#5484 fix: Add missing ending quotation mark in href
  label_studio/data_manager/actions/basic.py
  label_studio/ml/serializers.py
Labels: fix

#5503 docs: DOC-182: Add information about disabling telemetry
  docs/source/guide/security.md
Labels: docs

#5504 docs: DOC-182: Fix typo in security page
  docs/source/guide/security.md
Labels: docs

#5513 ci: Fix poetry lock
  poetry.lock
Labels: ci

#5463 docs: Steps for connect to S3 storage with own CA
  docs/source/guide/security.md
Labels: docs

#5508 feat: DIA-860: Add ModelRun
  label_studio/ml_models/migrations/0002_modelrun.py
  label_studio/ml_models/models.py
  poetry.lock
Labels: feat

#5500 fix: LEAP-626: Fix serialization for user without org member
  label_studio/users/serializers.py
Labels: fix, Confirmed

#5519 feat: DIA-950: Add associated_projects, input_fields, output_classes columns to modelinterface
  label_studio/ml_models/migrations/0003_auto_20240228_2228.py
  label_studio/ml_models/models.py
Labels: feat
