Repository HumanSignal/label-studio, pull requests merged in 2024-01, with the labels that each got.

#5219 docs: DOC-163: Surface troubleshooting information
  docs/source/guide/FAQ.md
  docs/source/guide/custom_metric.md
  docs/source/guide/import_troubleshoot.md
  docs/source/guide/install.md
  docs/source/guide/install_troubleshoot.md
  docs/source/guide/predictions.md
  docs/source/guide/project_troubleshoot.md
  docs/source/guide/quality_troubleshoot.md
  docs/source/guide/storage.md
  docs/source/guide/troubleshooting_install.md
Labels: docs

#5229 fix: LEAP-386: Fix axios dependency vulnerability
  label_studio/frontend/package.json
  label_studio/frontend/yarn.lock
Labels: fix, Confirmed

#5251 fix: LEAP-495: Add react-app, editor, and DM to wheel build
  pyproject.toml
Labels: fix

#5248 ci: PLATE-794: Enable Monorepo for Docker image
  .dockerignore
  Dockerfile
Labels: ci

#5249 fix: LEAP-491: Set ENABLE_MONOREPO_ENV to false
  docker-compose.yml
Labels: fix, Confirmed

#5255 docs: DOC-170: Update the comparison page to include data discovery
  docs/source/guide/label_studio_compare.md
Labels: docs

#5178 feat: DIA-771: Add validate methods for glob patterns if it matches at least something
  label_studio/core/settings/base.py
  label_studio/io_storages/azure_blob/utils.py
  label_studio/io_storages/gcs/utils.py
  label_studio/io_storages/s3/utils.py
Labels: feat

#5260 ci: Restore get-build.js to fix submodules
  label_studio/frontend/get-build.js
Labels: ci

#5271 docs: DOC-150: Added note to security page about securing cloud data
  docs/source/guide/security.md
Labels: docs

#5257 fix: LEAP-514: Removed the ENABLE_MONOREPO_ENV environment variable and set monorepo files as default
  .github/codeql/codeql-config.yaml
  .github/workflows/docker-release-promote.yml
  Dockerfile
  docker-compose.yml
  label_studio/core/context_processors.py
  label_studio/core/settings/base.py
  label_studio/templates/base.html
  pyproject.toml
Labels: fix

#5279 ci: PLATE-785: Fix Sentry frontend static files
  .github/workflows/docker-release-promote.yml
Labels: ci

#5277 ci: PLATE-795: Use pyproject.toml as a source version
  .github/workflows/release-cut-off-release-branch.yml
  .github/workflows/release-set-version.yml
  label_studio/__init__.py
  pyproject.toml
Labels: ci

#5288 docs: DOC-157: Remove .avi from list of supported video file types
  docs/source/guide/tasks.md
Labels: docs

#5289 fix: LEAP-458: implement storage_filename filter in data manager
  label_studio/data_manager/functions.py
  label_studio/data_manager/managers.py
  label_studio/data_manager/serializers.py
  label_studio/tasks/models.py
  label_studio/tests/data_manager/api_tasks.tavern.yml
Labels: fix, Confirmed

#5153 feat: OPTIC-139: [M1] Workflow Automation: Task Assignment
  label_studio/core/settings/base.py
  label_studio/data_manager/managers.py
  label_studio/projects/functions/__init__.py
  label_studio/projects/functions/next_task.py
  label_studio/tasks/models.py
Labels: feat

#5300 chore: Revert "feat: OPTIC-139: [M1] Workflow Automation: Task Assignment"
  label_studio/core/settings/base.py
  label_studio/data_manager/managers.py
  label_studio/projects/functions/__init__.py
  label_studio/projects/functions/next_task.py
  label_studio/tasks/models.py
Labels: chore

#5304 ci: PLATE-806: Add Poetry and monorepo support for git chatops command
  .github/workflows/git-command.yml
Labels: ci

#5305 ci: PLATE-785: Remove old frontend dist from FollowMerge
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#5308 docs: DOC-114: Add note about not opening the label stream in two tabs
  docs/source/guide/labeling.md
Labels: docs

#5320 docs: PLATE-805: Add x.y.z.devN version format support
  docs/scripts/release-notes.js
Labels: docs

#5311 docs: Add highlights to on-prem releases notes
  docs/themes/v2/source/js/collapse.js
Labels: docs

#5316 fix: LEAP-396: More exhaustative IP validation for SSRF defenses, plus user configurability
  label_studio/core/settings/base.py
  label_studio/core/utils/io.py
  label_studio/tests/data_import/test_uploader.py
Labels: fix

#5333 docs: PLATE-805: Fix release notes sort function
  docs/scripts/release-notes.js
Labels: docs

#5334 docs: PLATE-805: Fix release notes sort function order
  docs/scripts/release-notes.js
Labels: docs

#5336 ci: PLATE-777: Add PR link to release notes
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
Labels: ci

#5341 Revert "docs: DOC-137: Remove page for unsupported time series feature"
  docs/source/guide/ts+video.md
Labels: title needs formatting

#5331 docs: DOC-175: Page on backing up LSE on-prem
  docs/source/guide/backup_enterprise.md
  docs/source/guide/upgrade_enterprise.md
Labels: docs

#5335 docs: Fix Onprem 2.2.0 release md file name
  docs/source/guide/release_notes/onprem/2.2.0.md
Labels: docs

#5329 docs: DOC-174: Update docs to reflect monorepo
  CONTRIBUTING.md
  README.md
  docs/source/guide/frontend.md
  docs/source/guide/frontend_reference.md
  docs/themes/v2/layout/home.ejs
Labels: docs

#5346 docs: DOC-176: Add blog link to API guide page
  docs/source/guide/api.md
  docs/source/guide/sdk.md
Labels: docs

#5345 chore: remove requirements.txt and setup.py
  .dockerignore
  .github/workflows/cicd_pipeline.yml
  Dockerfile.testing
  MANIFEST.in
  deploy/requirements-mw.txt
  deploy/requirements-test.txt
  deploy/requirements.txt
  pyproject.toml
  setup.py
Labels: chore

#5256 fix: LEAP-480: Switch to dynamic domain names
  label_studio/core/settings/base.py
Labels: fix

#5366 ci: Optimize Docker image
  Dockerfile
Labels: ci

#5372 docs: DOC-169: New page on SCIM for LSE
  docs/source/guide/scim_setup.md
  docs/source/guide/scim_workflow.md
Labels: docs

#5356 docs: DOC-177: Add CVE links to on-prem release notes
  docs/source/guide/release_notes/onprem/2.7.0.md
  docs/source/guide/release_notes/onprem/2.9.0.md
Labels: docs

#5360 docs: Replace `Label Studio Enterprise` with `LSE` in the table of content
  docs/scripts/index.js
  docs/scripts/replaceContent.js
  docs/themes/v2/layout/page.ejs
Labels: docs

#5386 docs: DOC-181: Moved new helm chart section to LSE 2.3.1 section
  docs/scripts/release-notes.js
  docs/source/guide/release_notes/onprem/2.3.1.md
Labels: docs

#5387 docs: Update API and SDK links in header/footer
  docs/themes/v2/layout/partials/footer.ejs
  docs/themes/v2/layout/partials/header.ejs
Labels: docs

#5397 chore: LEAP-608: bump LSC version to support Repeater
  poetry.lock
  pyproject.toml
Labels: chore, Confirmed
