Repository HumanSignal/label-studio, pull requests merged in 2024-11, with the labels that each got.

#6600 docs: Agolia crawlers should only run on merge to `develop`
  .github/workflows/algolia-crawler-hs-docs.yml
  .github/workflows/algolia-crawler-ls-docs.yml
Labels: docs

#6585 ci: PLT-536: rework migration script to use pg_try_advisory_xact_lock
  label_studio/core/management/commands/locked_migrate.py
Labels: ci

#6583 feat: LEAP-1600: Add created_at for TaskLock
  label_studio/tasks/migrations/0051_tasklock_created_at.py
  label_studio/tasks/migrations/0052_auto_20241030_1757.py
  label_studio/tasks/models.py
Labels: feat

#6601 docs: DOC-244: Video frame classification template
  docs/source/templates/gallery_videos.ejs
  docs/source/templates/video_frame_classification.md
  label_studio/core/static/templates/video-frame-classification.png
Labels: docs

#6577 feat: LEAP-1599: Allow to edit TimelineRegion spans
  web/libs/editor/src/assets/icons/timeline/index.ts
  web/libs/editor/src/assets/icons/timeline/region.svg
  web/libs/editor/src/components/Node/Node.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionEditor.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/TimelineRegionEditor.module.scss
  web/libs/editor/src/components/SidePanels/DetailsPanel/TimelineRegionEditor.tsx
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.scss
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.tsx
  web/libs/editor/src/regions/EditableRegion.js
  web/libs/editor/src/regions/TimelineRegion.js
  web/libs/editor/src/stores/types.d.ts
Labels: feat, Confirmed

#6603 fix: OPTIC-1239: Update how api docs link is included
  label_studio/users/templates/users/user_account.html
Labels: fix, Confirmed

#6610 feat: LEAP-1603: Use custom_task_lock_ttl in set_lock
  label_studio/tasks/models.py
Labels: feat

#6616 ci: PLT-550: Dry run twine upload
  .github/workflows/build_pypi.yml
Labels: ci

#6624 feat: OPTIC-1245: Add HeidiTips as a json file within source control
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: feat

#6634 fix: OPTIC-1334: Cache labels action in DM gets timeout and cache labels for predictions should have separate name [base]
  label_studio/data_manager/actions/cache_labels.py
  label_studio/tests/data_manager/actions/test_cache_labels.py
Labels: fix

#6621 refactor: OPTIC-1333: Remove helpers.js
  label_studio/core/static/js/helpers.js
  label_studio/templates/base.html
  label_studio/users/templates/users/user_account.html
Labels: Confirmed, refactor

#6632 docs: Ngrock->Ngrok
  docs/source/guide/signup.md
Labels: docs

#6622 fix: LEAP-1647: Fix comments when user uses OCR textarea
  web/libs/editor/src/components/InteractiveOverlays/watchers/DOMWatcher.js
Labels: fix, Confirmed

#6638 fix: LEAP-1650: pkg_resources deprecation problems for 3.12,3.13
  label_studio/core/utils/common.py
  label_studio/core/utils/io.py
  poetry.lock
  pyproject.toml
Labels: fix

#6645 docs: LEAP-1657: Add a note to Text tag about \r\n
  docs/source/tags/text.md
  web/libs/editor/src/tags/object/Text.js
Labels: docs

#6623 feat: OPTIC-1245: Allow HeidiTips to pull content updates live
  label_studio/core/all_urls.json
  label_studio/core/urls.py
  label_studio/core/views.py
  web/apps/labelstudio/src/components/HeidiTips/HeidiTips.tsx
  web/apps/labelstudio/src/components/HeidiTips/content.ts
  web/apps/labelstudio/src/components/HeidiTips/hooks.ts
  web/apps/labelstudio/src/components/HeidiTips/types.ts
  web/apps/labelstudio/src/components/HeidiTips/utils.ts
Labels: feat, Confirmed

#6647 refactor: OPTIC-925: Remove Stale Feature Flag - fix_back_dev_3351_ml_validation_error_extension_short
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/ml/api_connector.py
Labels: refactor

#6641 fix: OPTIC-1341: Filtering on data fields is not working when $undefined$ and other columns in task data
  label_studio/data_manager/functions.py
  label_studio/data_manager/managers.py
  label_studio/projects/functions/utils.py
  label_studio/projects/models.py
  label_studio/tests/data_manager/test_undefined.py
Labels: fix

#6663 chore: Switch Makefile to use poetry for python commands
  Makefile
Labels: chore

#6636 fix: LEAP-1332: Add task example for MIG config
  label_studio/core/label_config.py
  label_studio/tests/sample_tasks.tavern.yml
Labels: fix, Confirmed

#6604 chore: OPTIC-1313: Reducing Toast usage in django templates to get rid of toast.min.js
  label_studio/core/static/css/Toast.min.css
  label_studio/core/static/css/uikit.css
  label_studio/core/static/js/Toast.min.js
  label_studio/templates/base.html
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/app/RootPage.jsx
  web/apps/labelstudio/src/assets/icons/index.js
  web/apps/labelstudio/src/components/DraftGuard/DraftGuard.jsx
  web/apps/labelstudio/src/components/HeidiTips/HeidiTip.tsx
  web/apps/labelstudio/src/components/Modal/ModalPopup.jsx
  web/apps/labelstudio/src/components/Toast/MessageToast.scss
  web/apps/labelstudio/src/components/Toast/MessageToast.tsx
  web/apps/labelstudio/src/components/Toast/Toast.tsx
  web/apps/labelstudio/src/hooks/useOrgValidation.tsx
  web/apps/labelstudio/src/pages/DataManager/DataManager.jsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/SelectedUser.jsx
  web/apps/labelstudio/src/pages/WebhookPage/WebhookDetail.jsx
  web/apps/labelstudio/src/pages/WebhookPage/WebhookList.jsx
  web/libs/ui/src/assets/icons/cross.svg
  web/libs/ui/src/assets/icons/index.ts
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/Toast/Toast.module.scss
  web/libs/ui/src/lib/Toast/Toast.tsx
Labels: chore, Confirmed

#6648 refactor: OPTIC-924: Remove Stale Feature Flag - ff_back_dev_2915_storage_nginx_proxy_26092022_short
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/core/storage.py
  label_studio/data_import/models.py
  label_studio/tasks/models.py
Labels: refactor

#6649 refactor: OPTIC-920: Remove Stale Feature Flag - fflag_fix_back_LSDV_961_project_list_09022023_short
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/projects/functions/__init__.py
Labels: refactor

#6655 feat: OPTIC-1242: Ask new OSS installs how they found about us
  label_studio/core/static/css/login.css
  label_studio/users/forms.py
  label_studio/users/functions.py
  label_studio/users/templates/users/new-ui/user_signup.html
  label_studio/users/views.py
Labels: feat

#6676 ci: LEAP-1564: Update `@sentry-react` to secure version
  web/apps/labelstudio/src/config/Sentry.ts
  web/package.json
  web/yarn.lock
Labels: ci

#6630 fix: LEAP-1615: LEAP-456: Fix tool unselect
  web/libs/editor/src/components/Toolbar/Toolbar.jsx
  web/libs/editor/src/tools/Manager.js
  web/libs/editor/src/tools/Selection.js
  web/libs/editor/tests/e2e/tests/regression-tests/brush-relations.test.js
Labels: fix, Confirmed

#6682 fix: Text for import dialog about uploads
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
Labels: fix

#6685 feat: DIA-1627: Support user context in LD
  label_studio/core/feature_flags/base.py
  label_studio/core/feature_flags/utils.py
  label_studio/core/settings/base.py
Labels: feat

#6662 fix: LEAP-1508: Prevent editing non-owned draft annotations
  web/libs/editor/src/components/BottomBar/Controls.tsx
  web/libs/editor/src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#6656 fix: OPTIC-1045: Update default placeholder text used in task data to be more clear
  label_studio/core/utils/schema/data_examples.json
  label_studio/tests/sample_tasks.tavern.yml
Labels: fix, Confirmed

#6680 ci: OPTIC-1357: biomejs level error sin ci
  .github/workflows/biome.yml
Labels: ci, Confirmed

#6686 docs: Update direct uploads warning
  docs/source/guide/tasks.md
  docs/themes/v2/source/css/styles.css
Labels: docs

#6678 fix: OPTIC-1354: [Incident] Table locks in prod SaaS causing degraded performance
  label_studio/tasks/models.py
  label_studio/tests/test_annotations_result_count.py
Labels: fix

#6683 fix: LEAP-1662: Add handling "valueList" attribute in visual config editor
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/Config/Template.js
Labels: fix, Confirmed

#6692 fix: DIA-1655: SC Prompter budget getting reset to 0
  label_studio/ml_model_providers/models.py
Labels: fix

#6693 fix: DIA-1655: default budget to 0 to avoid NoneType error
  label_studio/ml_model_providers/models.py
Labels: fix

#6681 docs: Add Starter Cloud to Prompts table
  docs/source/guide/prompts_overview.md
Labels: docs

#6696 fix: OPTIC-1373: Update async import and reimport to be on by default and amend locust tests
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: fix, Confirmed

#6698 fix: OPTIC-1248: Fixed error message that pops up when user checks heidi notifications checkbox at account settings
  label_studio/users/templates/users/user_account.html
Labels: fix

#6697 fix: OPTIC-972: Hover effect over selected filter element is not applied
  web/libs/datamanager/src/components/Common/Select/Select.scss
Labels: fix, Confirmed

#6713 ci: PLT-567: fix docker builds
  .github/workflows/docker-build-ontop.yml
  .github/workflows/docker-build.yml
  .github/workflows/docker-release-promote.yml
  Dockerfile
  Dockerfile.redhat
Labels: ci

#6722 feat: DIA-1686: [chore] bump SDK version to 1.0.8
  poetry.lock
  pyproject.toml
Labels: feat

#6717 docs: Restore LSF.init.md doc from LSF
  web/libs/editor/LSF.init.md
Labels: docs

#6727 refactor: LEAP-1322: Remove Stale Feature Flag - ff_back_2070_inner_id_12052022_short
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/data_manager/functions.py
  label_studio/tasks/models.py
Labels: refactor

#6719 feat: OPTIC-1337: Collect usage metrics internally
  label_studio/core/all_urls.json
  label_studio/core/urls.py
  label_studio/core/utils/contextlog.py
  label_studio/core/views.py
  label_studio/templates/base.html
  web/apps/labelstudio/src/main.tsx
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/PeoplePage.jsx
  web/libs/core/.babelrc
  web/libs/core/README.md
  web/libs/core/jest.config.ts
  web/libs/core/project.json
  web/libs/core/src/index.ts
  web/libs/core/src/lib/utils/analytics.test.ts
  web/libs/core/src/lib/utils/analytics.ts
  web/libs/core/tsconfig.json
  web/libs/core/tsconfig.lib.json
  web/libs/core/tsconfig.spec.json
  web/tsconfig.base.json
Labels: feat, Confirmed
