Repository HumanSignal/label-studio, pull requests merged in 2024-09, with the labels that each got.

#6284 refactor: optic 929: remove stale feature flags
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/datamanager/src/utils/feature-flags.js
  web/libs/editor/src/core/feature-flags/flags.json
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/tags/control/Polygon.js
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/tests/image.transformer.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-zoom-position.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-zoom-transform.test.js
  web/libs/editor/tests/e2e/tests/sync/multiple-audio.test.js
  web/libs/editor/tests/e2e/tests/unfinished-polygons.test.js
  web/libs/editor/tests/integration/e2e/control_tags/classification/per-item.cy.ts
  web/libs/editor/tests/integration/feature-flags.ts
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor

#6314 ci: PLT-481: Use pretty branch name in docker command
  .github/workflows/docker-build.yml
Labels: ci

#6308 refactor: OPTIC-1070: restore stale ff 'ff_front_dev_2432_auto_save_polygon_draft_210622_short': True,
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6315 docs: Fix release notes for 2.15.0
  docs/source/guide/release_notes/onprem/2.15.0.md
Labels: docs

#6306 docs: DOC-235: Reviewer workflow updates
  docs/source/guide/quality.md
Labels: docs

#6327 fix: OPTIC-1080: buttons failure in review annotations
  web/libs/editor/src/components/BottomBar/CurrentTask.scss
  web/libs/editor/src/components/TopBar/CurrentTask.scss
Labels: fix

#6326 fix: OPTIC-1079: Converted Stylus to SCSS included invalid usages of some css variables follow up
  web/apps/labelstudio/src/components/Modal/Modal.scss
  web/apps/labelstudio/src/components/Spinner/Spinner.scss
  web/libs/editor/src/common/Button/Button.scss
  web/libs/editor/src/common/Tag/Tag.scss
  web/libs/editor/src/components/SidePanels/PanelBase.scss
  web/libs/editor/src/components/SidePanels/TabPanels/PanelTabsBase.scss
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.scss
Labels: fix

#6259 ci: PLT-472: add migrations linter
  .github/workflows/test_migrations.yml
  label_studio/core/settings/base.py
  label_studio/data_manager/migrations/0001_squashed_0005_view_user.py
  label_studio/io_storages/migrations/0001_squashed_0002_auto_20210302_1827.py
  label_studio/ml/migrations/0001_initial.py
  label_studio/projects/migrations/0001_squashed_0065_auto_20210223_2014.py
  poetry.lock
  pyproject.toml
Labels: ci

#6328 fix: OPTIC-1081: BigInteger support in Data Manager
  web/libs/datamanager/src/utils/api-proxy/index.js
Labels: fix

#6332 fix: Fix update_ml_tutorials script to support line separators
  scripts/update_ml_tutorials.py
Labels: fix

#6317 chore: Remove404s
  docs/source/guide/install_enterprise_k8s.md
  docs/source/guide/install_k8s.md
  docs/source/guide/setup_project.md
  docs/source/guide/tasks.md
  docs/source/templates/multi-page-document-annotation.md
  docs/source/templates/taxonomy.md
  docs/themes/v2/layout/partials/footer.ejs
Labels: chore

#6333 fix: Fix for update_ml_tutorials.py
  scripts/update_ml_tutorials.py
Labels: fix

#6280 chore: OPTIC-1060: Hot Module Reload support for frontend development
  .env.development
  Makefile
  README.md
  docker-compose.override.example.yml
  label_studio/core/settings/base.py
  label_studio/templates/base.html
  label_studio/templates/simple.html
  web/README.md
  web/apps/labelstudio/src/app/App.jsx
  web/package.json
  web/webpack.config.js
Labels: chore, Confirmed

#6335 fix: Update tutorials script try 2
  scripts/update_ml_tutorials.py
Labels: fix

#6349 fix: Linter in update_ml_tutorials script
  scripts/update_ml_tutorials.py
Labels: fix

#6191 feat: LEAP-1367: Add TimelineLabels to mark parts of the video
  docs/source/tags/timelinelabels.md
  docs/source/tags/video.md
  docs/source/tags/videorectangle.md
  docs/themes/v2/source/images/timelinelabels.png
  web/libs/editor/src/components/Timeline/Timeline.tsx
  web/libs/editor/src/components/Timeline/Types.ts
  web/libs/editor/src/components/Timeline/Views/Frames/Controls.tsx
  web/libs/editor/src/components/Timeline/Views/Frames/Frames.tsx
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.scss
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.tsx
  web/libs/editor/src/components/Timeline/Views/Frames/Minimap.tsx
  web/libs/editor/src/regions/Area.js
  web/libs/editor/src/regions/Result.js
  web/libs/editor/src/regions/TimelineRegion.js
  web/libs/editor/src/regions/index.js
  web/libs/editor/src/tags/control/Label.jsx
  web/libs/editor/src/tags/control/TimelineLabels.js
  web/libs/editor/src/tags/control/index.js
  web/libs/editor/src/tags/object/Video/HtxVideo.jsx
  web/libs/editor/src/tags/object/Video/Video.js
  web/libs/editor/src/tags/object/Video/VideoRegions.jsx
  web/libs/editor/src/tags/visual/View.jsx
  web/libs/editor/tests/e2e/tests/regression-tests/video-timeline-seek-indicator.test.js
Labels: feat, Confirmed

#6344 fix: LEAP-1456: CSRF - use $http_host instead of nginx $host so port will be included
  deploy/default.conf
Labels: fix

#6350 docs: Fix video links in YOLO tutorial
  docs/source/tutorials/yolo.md
Labels: docs

#6244 feat: Add duration time in info tab
  web/libs/editor/src/common/Label/Label.scss
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionEditor.tsx
  web/libs/editor/src/components/TimeDurationControl/TimeBox.scss
  web/libs/editor/src/components/TimeDurationControl/TimeBox.tsx
  web/libs/editor/src/components/TimeDurationControl/TimeDurationControl.scss
  web/libs/editor/src/components/TimeDurationControl/TimeDurationControl.tsx
Labels: feat

#6323 feat: DIA-1360: Add token cost KPI to the Prompt aggregate-level subset metrics
  label_studio/tasks/migrations/0049_auto_20240905_1602.py
  label_studio/tasks/models.py
  label_studio/tests/test_predictions.py
  poetry.lock
  pyproject.toml
Labels: feat

#6359 fix: DIA-1360: Revert prediction serialization
  label_studio/tasks/models.py
Labels: fix

#6263 feat: LEAP-1341: Build schema.json in create-docs script
  docs/source/tags/timelinelabels.md
  web/apps/labelstudio/src/pages/CreateProject/Config/schema.json
  web/libs/editor/scripts/create-docs.js
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.scss
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.tsx
  web/libs/editor/src/regions/TimelineRegion.js
  web/libs/editor/src/tags/control/TimelineLabels.js
  web/package.json
Labels: feat, Confirmed

#6367 fix: DIA-1360: Fix error on deleting predictions
  label_studio/ml_models/models.py
Labels: fix

#6319 docs: Refine exact metric on stats page
  docs/source/guide/stats.md
Labels: docs

#6368 fix: LEAP-1367: Revert mistakenly removed styles for timeline regions
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.scss
Labels: fix

#6325 fix: OPTIC-1072: Update SVGs to have currentColor instead of black fill to allow overwrite using css
  label_studio/core/static/icons/github.svg
  web/apps/labelstudio/src/assets/icons/book.svg
  web/apps/labelstudio/src/assets/icons/door.svg
  web/apps/labelstudio/src/assets/icons/folder.svg
  web/apps/labelstudio/src/assets/icons/github.svg
  web/apps/labelstudio/src/assets/icons/person-circle.svg
  web/apps/labelstudio/src/assets/icons/pin.svg
  web/apps/labelstudio/src/assets/icons/settings.svg
  web/apps/labelstudio/src/assets/icons/terminal.svg
  web/libs/datamanager/src/assets/icons/gear_new_menu.svg
  web/libs/datamanager/src/assets/icons/gear_new_ui.svg
  web/libs/editor/src/assets/icons/filter.svg
  web/libs/editor/src/assets/icons/sort-up-new.svg
  web/libs/editor/src/assets/icons/timeline/config.svg
  web/libs/editor/src/assets/icons/timeline/eye_closed.svg
  web/libs/editor/src/assets/icons/timeline/eye_opened.svg
  web/libs/editor/src/assets/icons/timeline/info.svg
  web/libs/editor/src/assets/icons/timeline/sound.svg
  web/libs/editor/src/assets/icons/timeline/sound_muted.svg
  web/libs/editor/src/assets/icons/tools/expand-tool.svg
  web/libs/editor/src/assets/icons/tools/move-tool.svg
  web/libs/editor/src/assets/icons/tools/rotate-left-tool.svg
  web/libs/editor/src/assets/icons/tools/rotate-right-tool.svg
  web/libs/editor/src/assets/icons/tree/arrow.svg
Labels: fix, Confirmed

#6373 fix: FF naming with feat_ for env override
  label_studio/core/feature_flags/base.py
Labels: fix

#6343 docs: DOC-243: Update task agreements page
  docs/source/guide/stats.md
Labels: docs

#6374 fix: DIA-1419: RunTime error occurs on trying to delete certain prompts
  label_studio/tasks/models.py
Labels: fix

#6376 chore: Ensure the one time dev build does not incorrectly default to using the HMR frontend host
  web/webpack.config.js
Labels: chore

#6377 feat: DIA-1422: Relationship between prompt version and provider conn…
  label_studio/ml_models/migrations/0011_thirdpartymodelversion_model_provider_connection.py
  label_studio/ml_models/models.py
  poetry.lock
  pyproject.toml
Labels: feat

#6389 fix: DIA-1428: Update lock with the latest sdk
  poetry.lock
  pyproject.toml
Labels: fix

#6393 chore: TRIAG-851: Resolve a development dependency to satisfy dependabot issue
  web/package.json
Labels: chore

#6375 ci: PLT-464: Unstage Frontend Static Before Commit
  .pre-commit-config.yaml
  .pre-commit-dev.yaml
Labels: ci

#6396 docs: Update YOLO image for tutorials
  docs/source/tutorials/yolo.png
Labels: docs

#6390 docs: Add multiple values in whenChoiceValue and whenLabelValue
  docs/source/tags/choices.md
  docs/source/tags/view.md
  web/libs/editor/src/tags/control/Choices.jsx
  web/libs/editor/src/tags/visual/View.jsx
Labels: docs

#6405 docs: Update YOLO images
  docs/source/tutorials/yolo-video-classification.png
  docs/source/tutorials/yolo.png
Labels: docs

#6381 fix: OPTIC-1087: Label Config Preview not handling editor lifecycle correctly for updates
  web/apps/labelstudio/src/pages/CreateProject/Config/Preview.jsx
Labels: fix, Confirmed

#6407 chore: TRIAG-851: Resolve a development dependency to satisfy dependabot issue in test dependencies
  web/libs/editor/tests/e2e/package.json
Labels: chore

#6397 docs: Include video links in documentation
  docs/source/guide/dashboards.md
  docs/source/guide/ml_create.md
  docs/source/guide/quality.md
  docs/source/guide/scripts.md
  docs/source/guide/setup_project.md
Labels: docs

#6409 chore: OPTIC-1124: Refactor the classification tests to separate files to stabilize chromium session
  web/libs/editor/tests/integration/e2e/control_tags/classification/choices.cy.ts
  web/libs/editor/tests/integration/e2e/control_tags/classification/common.ts
  web/libs/editor/tests/integration/e2e/control_tags/classification/datetime.cy.ts
  web/libs/editor/tests/integration/e2e/control_tags/classification/number.cy.ts
  web/libs/editor/tests/integration/e2e/control_tags/classification/per-item.cy.ts
  web/libs/editor/tests/integration/e2e/control_tags/classification/rating.cy.ts
  web/libs/editor/tests/integration/e2e/control_tags/classification/taxonomy.cy.ts
  web/libs/editor/tests/integration/e2e/control_tags/classification/textarea.cy.ts
Labels: chore

#6395 feat: LEAP-1469: Implement universal linking modes
  web/libs/editor/src/components/Entity/Entity.jsx
  web/libs/editor/src/components/ImageView/ImageView.jsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionItem.tsx
  web/libs/editor/src/core/Constants.ts
  web/libs/editor/src/mixins/HighlightMixin.js
  web/libs/editor/src/mixins/KonvaRegion.js
  web/libs/editor/src/mixins/Regions.js
  web/libs/editor/src/mixins/SpanText.js
  web/libs/editor/src/regions/AudioRegion/AudioRegionModel.js
  web/libs/editor/src/regions/AudioRegion/AudioUltraRegionModel.js
  web/libs/editor/src/regions/BrushRegion.jsx
  web/libs/editor/src/regions/EllipseRegion.jsx
  web/libs/editor/src/regions/ImageRegion.js
  web/libs/editor/src/regions/KeyPointRegion.jsx
  web/libs/editor/src/regions/PolygonRegion.jsx
  web/libs/editor/src/regions/RectRegion.jsx
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/stores/Annotation/LinkingModes.js
  web/libs/editor/src/stores/Annotation/LinkingModes/CommentMode.js
  web/libs/editor/src/stores/Annotation/LinkingModes/RelationMode.js
  web/libs/editor/src/stores/AppStore.js
  web/libs/editor/src/stores/Comment/Comment.js
  web/libs/editor/src/tags/object/Image/Image.js
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/src/tags/object/Video/VideoRegions.jsx
  web/libs/editor/tests/integration/data/linked_modes/to_comments.ts
  web/libs/editor/tests/integration/e2e/linking_modes/to_comments.cy.ts
Labels: feat

#6316 docs: DOC-242: Add NER type to Prompts doc
  docs/source/guide/prompts_create.md
  docs/source/guide/prompts_overview.md
Labels: docs

#6148 Chore: Update README.md
  README.md
Labels: title needs formatting

#6351 docs: DOC-241: Add troubleshooting page to Community docs
  docs/source/guide/ml.md
  docs/source/guide/predictions.md
  docs/source/guide/storage.md
  docs/source/guide/troubleshooting.md
  docs/themes/v2/layout/partials/toc.ejs
Labels: docs

#6410 fix: OPTIC-447: Filters don't pass to label stream in DM
  web/libs/datamanager/src/stores/AppStore.js
Labels: fix, Confirmed

#6281 feat: DIA-1362: Custom LLM URL support
  label_studio/ml_model_providers/migrations/0004_auto_20240830_1206.py
  label_studio/ml_model_providers/models.py
  label_studio/ml_models/migrations/0012_alter_thirdpartymodelversion_provider.py
Labels: feat

#6400 feat: LEAP-1440: Allow to attach a region to a new comment
  web/libs/datamanager/src/sdk/comments-sdk.js
  web/libs/editor/src/assets/icons/comment/index.ts
  web/libs/editor/src/assets/icons/comment/link-to.svg
  web/libs/editor/src/assets/icons/index.tsx
  web/libs/editor/src/common/TextArea/TextArea.tsx
  web/libs/editor/src/components/Comments/Comment/CommentForm.scss
  web/libs/editor/src/components/Comments/Comment/CommentForm.tsx
  web/libs/editor/src/components/Comments/Comment/LinkState.scss
  web/libs/editor/src/components/Comments/Comment/LinkState.tsx
  web/libs/editor/src/components/Comments/CommentFormBase.tsx
  web/libs/editor/src/components/Comments/Comments.tsx
  web/libs/editor/src/components/Comments/OldComment/CommentForm.scss
  web/libs/editor/src/components/Comments/OldComment/CommentForm.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/RegionLabel.tsx
  web/libs/editor/src/stores/Comment/Anchor.js
  web/libs/editor/src/stores/Comment/Comment.js
  web/libs/editor/src/stores/Comment/CommentStore.js
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/src/utils/utilities.ts
Labels: feat, Confirmed

#6403 feat: LEAP-1448: Add support of rejected+cancelled in skipped queue
  label_studio/tasks/mixins.py
  label_studio/tasks/models.py
Labels: feat

#6433 fix: OPTIC-858: Removing 'model_' from AllPermissions' protected_namespaces
  label_studio/core/permissions.py
Labels: fix

#6426 fix: LEAP-1258: prevent dropdown from opening upward when viewport short
  web/libs/datamanager/src/components/Common/Dropdown/DropdownComponent.jsx
  web/libs/datamanager/src/components/Common/FieldsButton.jsx
  web/libs/datamanager/src/components/Common/FiltersPane.jsx
  web/libs/datamanager/src/components/Common/Tabs/Tabs.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/ActionsButton.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/OrderButton.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/instruments.jsx
  web/libs/datamanager/src/utils/dom.js
Labels: fix, Confirmed

#6417 fix: OPTIC-1125: Label config preview always showing a step behind when making updates
  web/apps/labelstudio/src/pages/CreateProject/Config/Preview.jsx
  web/libs/editor/src/tags/object/Image/ImageEntity.js
  web/libs/editor/tests/integration/e2e/image_segmentation/tools/rect3point.cy.ts
Labels: fix

#6428 fix: DIA-1428: RunTime error occurs on trying to delete certain prompts
  label_studio/tasks/migrations/0050_alter_predictionmeta_failed_prediction_and_more.py
  label_studio/tasks/models.py
Labels: fix

#6406 fix: OPTIC-1120: Draft lead time incorrectly calculated which can cause annotation lead time to be wrong
  web/libs/datamanager/src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#6434 docs: DOC-246: Updates to Prompts docs
  docs/source/guide/prompts_create.md
  docs/source/guide/prompts_overview.md
  docs/source/guide/saas.md
Labels: docs

#6413 feat: LEAP-1467: Adapt Textarea result container to new style
  web/libs/editor/src/assets/icons/edit.svg
  web/libs/editor/src/assets/icons/index.tsx
  web/libs/editor/src/assets/icons/trash-alt.svg
  web/libs/editor/src/components/HtxTextBox/HtxTextBox.jsx
  web/libs/editor/src/regions/TextAreaRegion.jsx
  web/libs/editor/src/regions/TextAreaRegion/TextAreaRegion.module.scss
  web/libs/editor/src/regions/TextAreaRegion/TextAreaRegion.scss
  web/libs/frontend-test/src/helpers/LSF/Textarea.ts
Labels: feat, Confirmed

#6404 feat: LEAP-1439: Display link in existing comment and allow linking
  web/libs/editor/public/styles/main.css
  web/libs/editor/src/components/Comments/Comment/CommentForm.scss
  web/libs/editor/src/components/Comments/Comment/CommentForm.tsx
  web/libs/editor/src/components/Comments/Comment/CommentItem.scss
  web/libs/editor/src/components/Comments/Comment/CommentItem.tsx
  web/libs/editor/src/components/Comments/Comment/CommentsList.tsx
  web/libs/editor/src/components/Comments/Comment/LinkState.scss
  web/libs/editor/src/components/Comments/CommentFormBase.tsx
  web/libs/editor/src/components/Comments/Comments.tsx
  web/libs/editor/src/components/Comments/OldComment/CommentItem.scss
  web/libs/editor/src/components/Comments/OldComment/CommentItem.tsx
  web/libs/editor/src/components/Comments/OldComment/CommentsList.tsx
  web/libs/editor/src/stores/Comment/Comment.js
  web/libs/editor/src/stores/Comment/CommentStore.js
Labels: feat, Confirmed

#6437 refactor: OPTIC-888: Stale feature flag
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6445 refactor: OPTIC-1165: stale fflag_feat_front_prod_292_archive_workspa…
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6451 docs: DOCS-252: Update Prompts for multi-class selection
  docs/source/guide/prompts_create.md
  docs/source/guide/prompts_overview.md
Labels: docs
