Repository HumanSignal/label-studio, pull requests merged in 2024-07, with the labels that each got.

#6043 fix: LEAP-1200: Add ssl support for ldclient redis connection
  label_studio/core/feature_flags/base.py
  label_studio/core/settings/base.py
Labels: fix

#6031 docs: fixed forgotten docker registry organization names
  docs/source/tutorials/tesseract.md
Labels: docs

#6022 test: LEAP-1141: Add test for concurrent saving annotation and draft
  web/libs/editor/tests/integration/e2e/drafts/submit.cy.ts
  web/libs/frontend-test/src/helpers/LSF/ToolBar.ts
Labels: Confirmed, test

#6046 docs: swapped starter cloud links for enterprise
  docs/themes/v2/layout/page.ejs
Labels: docs

#6047 docs: DOC-226: Add note about backslashes in Windows directories
  docs/source/guide/storage.md
Labels: docs

#5825 docs: DOC-209: Remove LSE params from the community helm chart page
  docs/source/guide/helm_values.md
Labels: Stale, docs

#6040 docs: DOC-224: Fix commands under SDK version
  docs/source/guide/sdk.md
Labels: docs

#6051 chore: LEAP-1127: bump requests to secure version
  poetry.lock
  pyproject.toml
Labels: chore

#6053 docs: DOC-132: Update button on comparison page
  docs/source/guide/label_studio_compare.md
  docs/themes/v2/layout/page.ejs
Labels: docs

#6052 docs: Fix export.md with export path
  docs/source/guide/export.md
Labels: docs

#6048 feat: LEAP-1173: Disable the postpone option if the skip interface isn't set
  web/libs/editor/src/components/BottomBar/CurrentTask.jsx
  web/libs/editor/src/components/BottomBar/__tests__/CurrentTask.test.tsx
  web/libs/editor/src/components/TopBar/CurrentTask.jsx
  web/libs/editor/src/components/TopBar/__tests__/CurrentTask.test.tsx
  web/libs/editor/src/utils/bem.ts
  web/libs/editor/src/utils/feature-flags.ts
Labels: feat, fix, Confirmed

#6049 fix: dia-1248: [BE] handle any table row deletions which have predictions as foreign key before deleting predictions in modelrun delete
  label_studio/ml_models/models.py
Labels: fix

#6058 docs: DOC-227: Elaborate on pre-annotation setting
  docs/source/guide/project_settings_lse.md
Labels: docs

#6055 fix: OPTIC-849: style updates and tooltip edits
  label_studio/core/static/css/users.css
  label_studio/users/templates/users/new-ui/user_tips.html
  label_studio/users/templates/users/user_account.html
  web/apps/labelstudio/src/assets/icons/pencil.svg
  web/apps/labelstudio/src/assets/images/heidi-speaking.svg
  web/apps/labelstudio/src/components/Badges/Enterprise.styl
  web/apps/labelstudio/src/components/Button/Button.styl
  web/apps/labelstudio/src/components/Caption/Caption.styl
  web/apps/labelstudio/src/components/Form/Elements/Label/Label.styl
  web/apps/labelstudio/src/components/Form/Elements/Select/Select.styl
  web/apps/labelstudio/src/components/Form/Elements/Toggle/Toggle.styl
  web/apps/labelstudio/src/components/Form/Form.styl
  web/apps/labelstudio/src/components/Form/Validation/Validation.styl
  web/apps/labelstudio/src/components/HeidiTips/content.ts
  web/apps/labelstudio/src/components/Modal/Modal.styl
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.styl
  web/apps/labelstudio/src/pages/ExportPage/ExportPage.styl
  web/apps/labelstudio/src/pages/Settings/AnnotationSettings.jsx
  web/apps/labelstudio/src/pages/Settings/DangerZone.jsx
  web/apps/labelstudio/src/pages/Settings/GeneralSettings.jsx
  web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningList.styl
  web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningSettings.jsx
  web/apps/labelstudio/src/pages/Settings/settings.styl
  web/apps/labelstudio/src/pages/WebhookPage/WebhookDetail.jsx
  web/apps/labelstudio/src/pages/WebhookPage/WebhookList.jsx
  web/apps/labelstudio/src/pages/WebhookPage/WebhookPage.styl
  web/apps/labelstudio/src/themes/default/variables.styl
  web/dist/apps/labelstudio/heidi-speaking.1eeb172f5b8c1cc84891154d1d4bde02.svg
  web/dist/apps/labelstudio/heidi-speaking.1f9b76453658cf4d10fcf0b9ded0b281.svg
  web/dist/apps/labelstudio/heidi-speaking.9124839ce2f466ebf54676f72dc31dfb.svg
  web/dist/apps/labelstudio/heidi-speaking.b4b04eb325f6216a1569e4a85e659fe3.svg
  web/dist/apps/labelstudio/heidi-speaking.d9fddc455e3e1f2c04f57bda6f883d9e.svg
  web/dist/apps/labelstudio/heidi-speaking.ee7707fabaf8a2d6e3ac8aeeb50e5c7b.svg
  web/dist/apps/labelstudio/pencil.ff26e7bf928eb95754cbcfa1069ff4e5.svg
  web/libs/datamanager/src/components/Common/Range/Range.styl
  web/libs/datamanager/src/themes/default/colors.styl
  web/libs/editor/src/common/Range/Range.styl
  web/libs/editor/src/components/CurrentEntity/CurrentEntity.styl
  web/libs/editor/src/components/Timeline/Controls/Slider.styl
  web/libs/editor/src/tags/control/Choice/Choice.styl
  web/libs/editor/src/themes/default/colors.styl
Labels: fix

#6066 docs: DOC-132: Fix typo on ML page
  docs/source/guide/ml.md
Labels: docs

#6071 ci: PLT-409: Skip Docker image push for external contributors
  .github/workflows/docker-build-ontop.yml
  .github/workflows/docker-build-ubi.yml
  .github/workflows/docker-build.yml
Labels: ci

#6074 fix: LEAP-1175: Add logging for export duration
  label_studio/data_export/mixins.py
Labels: fix

#6078 fix: OPTIC-875,OPTIC-876,OPTIC-877,OPTIC-878,OPTIC-879: Visual conflicts due to design updates
  label_studio/users/templates/users/new-ui/user_login.html
  web/apps/labelstudio/src/components/Button/Button.styl
  web/apps/labelstudio/src/pages/Projects/Projects.styl
  web/libs/datamanager/src/components/DataManager/Toolbar/instruments.jsx
Labels: fix

#6081 fix: OPTIC-875,OPTIC-876,OPTIC-877,OPTIC-878,OPTIC-879: Visual conflicts due to design updates
  label_studio/users/templates/users/new-ui/user_login.html
  web/apps/labelstudio/src/components/Button/Button.styl
  web/apps/labelstudio/src/pages/Projects/Projects.styl
  web/libs/datamanager/src/components/DataManager/Toolbar/instruments.jsx
Labels: fix

#6084 fix: OPTIC-882: Docs Icon has visual artifact on DataManager
  web/apps/labelstudio/src/assets/icons/book.svg
Labels: fix, Confirmed

#6085 fix: OPTIC-883: Export data modal footer not visible when scrollable
  web/apps/labelstudio/src/components/Modal/Modal.styl
  web/apps/labelstudio/src/pages/ExportPage/ExportPage.styl
Labels: fix, Confirmed

#6088 fix: OPTIC-882,OPTIC-883: Redesign visual issues with release 1.13.0
  web/apps/labelstudio/src/assets/icons/book.svg
  web/apps/labelstudio/src/components/Modal/Modal.styl
  web/apps/labelstudio/src/pages/ExportPage/ExportPage.styl
Labels: fix

#6067 fix: LEAP-1209: Make displaying of resolve comment button dependent on interfaces
  web/apps/labelstudio/src/pages/CreateProject/Config/Preview.jsx
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/editor/src/components/Comments/CommentItem.tsx
  web/libs/editor/src/stores/Comment/Comment.js
Labels: fix, Confirmed

#6089 fix: OPTIC-884: Incorrect block style name for prediction card
  web/apps/labelstudio/src/pages/Settings/PredictionsSettings/PredictionsList.styl
Labels: fix

#6096 ci: PLT-412: Integrate Jira fix version
  .github/workflows/cicd_pipeline.yml
  .github/workflows/release-pipeline.yml
Labels: ci

#6097 fix: OPTIC-885: Links not clickable from within Radio Button
  web/apps/labelstudio/src/components/Form/Elements/RadioGroup/RadioGroup.jsx
Labels: fix, Confirmed

#6102 fix: OPTIC-885: Links not clickable from within Radio Button (#6097)
  web/apps/labelstudio/src/components/Form/Elements/RadioGroup/RadioGroup.jsx
Labels: fix

#6104 docs: Fix on-prem release notes
  docs/source/guide/release_notes/onprem/2.13.0.md
Labels: docs

#6110 docs: Show 10 search results instead of the default 5
  docs/themes/v2/source/js/header.js
Labels: docs

#6109 fix: OPTIC-765: TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
  web/libs/datamanager/src/components/Common/Tooltip/Tooltip.jsx
Labels: fix, Confirmed

#6111 fix: OPTIC-683: Detect and convert large integers automatically in API responses before parsing as JSON to retain precision
  web/libs/datamanager/src/utils/__tests__/helpers.test.ts
  web/libs/datamanager/src/utils/api-proxy/index.js
  web/libs/datamanager/src/utils/helpers.ts
Labels: fix, Confirmed

#6108 feat: DIA-1267: Allow support for Azure OpenAI connections
  label_studio/core/settings/base.py
  label_studio/ml_model_providers/migrations/0002_auto_20240722_2054.py
  label_studio/ml_model_providers/models.py
  label_studio/ml_models/migrations/0009_alter_thirdpartymodelversion_provider.py
  label_studio/ml_models/models.py
Labels: feat

#6079 feat: LEAP-1199: Add drag and drop functionality on DM tabs
  label_studio/core/all_urls.json
  label_studio/data_manager/api.py
  label_studio/data_manager/migrations/0011_auto_20240718_1355.py
  label_studio/data_manager/models.py
  label_studio/data_manager/serializers.py
  label_studio/tests/data_manager/test_views_api.py
  web/libs/datamanager/src/components/Common/Tabs/Tabs.jsx
  web/libs/datamanager/src/components/Common/Tabs/Tabs.styl
  web/libs/datamanager/src/components/DataManager/DataManager.jsx
  web/libs/datamanager/src/sdk/api-config.js
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/stores/Tabs/store.js
  web/libs/datamanager/src/utils/api-proxy/index.js
Labels: feat, Confirmed

#5903 ci: enable some rules in biome
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/Config/TemplatesList.jsx
  web/biome.json
  web/libs/datamanager/src/components/DataManager/Toolbar/LabelButton.jsx
  web/libs/editor/src/components/RelationsOverlay/RelationsOverlay.jsx
  web/libs/editor/src/mixins/Regions.js
  web/libs/editor/src/stores/RelationStore.js
  web/libs/editor/src/utils/debounce.js
  web/libs/editor/src/utils/html.js
  web/libs/editor/src/utils/scissors.js
Labels: ci

#6130 docs: Fix contextual_scrolling.png image path
  docs/source/templates/gallery_asr.ejs
Labels: docs

#6128 ci: enable some rules in biome
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/biome.json
  web/libs/datamanager/src/components/Common/Form/Elements/Select/Select.jsx
  web/libs/datamanager/src/stores/Tabs/tab_column.jsx
  web/libs/datamanager/src/stores/Tabs/tab_filter.js
  web/libs/editor/src/components/DraftPanel/DraftPanel.jsx
  web/libs/editor/src/components/ImageView/Image.jsx
  web/libs/editor/src/components/Ranker/Column.tsx
  web/libs/editor/src/components/Settings/TagSettings/SettingsRenderer.tsx
  web/libs/editor/src/components/SidePanels/Components/RegionControlButton.tsx
  web/libs/editor/src/components/Taxonomy/Taxonomy.tsx
  web/libs/editor/src/components/Timeline/Plugins/Timeline.tsx
  web/libs/editor/src/utils/selection-tools.js
Labels: ci

#6117 fix: LEAP-1265: Display index on regions with empty labels
  web/libs/editor/src/components/ImageView/LabelOnRegion.jsx
  web/libs/editor/src/mixins/HighlightMixin.js
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/src/utils/selection-tools.js
Labels: fix, Confirmed

#6131 docs: OPTIC-753: Updating README.md to reflect information pertaining to linting of frontend code
  web/README.md
  web/package.json
Labels: docs

#6056 fix: LEAP-1191: Fix drawing tools scenarios with ctrl pressed
  web/libs/editor/src/components/ImageView/ImageView.jsx
  web/libs/editor/src/mixins/DrawingTool.js
  web/libs/editor/src/mixins/Tool.js
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/tools/Selection.js
  web/libs/editor/src/tools/Zoom.jsx
  web/libs/editor/tests/integration/data/image_segmentation/ctrl.ts
  web/libs/editor/tests/integration/e2e/image_segmentation/ctrl.cy.ts
  web/libs/frontend-test/src/helpers/LSF/ImageView.ts
Labels: fix, Confirmed

#6123 fix: OPTIC-954: Project card default color change broke the text color
  web/apps/labelstudio/src/pages/Projects/ProjectsList.jsx
Labels: fix

#6138 fix: OPTIC-954: Project card default color change broke the text color (#6123)
  web/apps/labelstudio/src/pages/Projects/ProjectsList.jsx
Labels: fix

#6132 fix: LEAP-552: Hide the comments tab on preview
  web/apps/labelstudio/src/pages/CreateProject/Config/Preview.jsx
Labels: fix, Confirmed

#6133 refactor: Remove unused code on helper.js
  label_studio/core/static/js/helpers.js
Labels: refactor

#6136 refactor: OPTIC-931: Remove Stale Feature Flag - ff_back_1614_rejecte…
  label_studio/core/feature_flags/stale_feature_flags.py
  web/apps/labelstudio/src/utils/feature-flags.ts
Labels: refactor

#6151 fix: RND-70: Little fix for experimental action Cache labels
  label_studio/data_manager/actions/cache_labels.py
Labels: fix

#6147 docs: DOC-232: New LLM templates and reorganizing
  docs/source/templates/gallery_generative_ai.ejs
  docs/source/templates/gallery_llm_evals.ejs
  docs/source/templates/gallery_rns.html
  docs/source/templates/gallery_videos.ejs
  docs/source/templates/generative-chatbot-assessment.md
  docs/source/templates/generative-llm-ranker.md
  docs/source/templates/generative-pairwise-human-preference.md
  docs/source/templates/generative-supervised-llm.md
  docs/source/templates/generative-visual-ranker.md
  docs/source/templates/index.ejs
  docs/source/templates/llm_rag_human_feedback.md
  docs/source/templates/llm_ragas.md
  docs/source/templates/llm_response_grading.md
  docs/source/templates/llm_response_moderation.md
  docs/source/templates/llm_side_by_side.md
  docs/themes/v2/layout/partials/toc.ejs
  label_studio/core/static/templates/evaluate-rag-automated-metrics.png
  label_studio/core/static/templates/evaluate-rag-human-feedback.png
  label_studio/core/static/templates/generative-pairwise-human-preference.png
  label_studio/core/static/templates/generative-supervised-llm.png
  label_studio/core/static/templates/llm-ranker.png
  label_studio/core/static/templates/response-grading.png
  label_studio/core/static/templates/response-moderation.png
  label_studio/core/static/templates/side-by-side-comparison.png
  label_studio/core/static/templates/visual-ranker.png
Labels: docs
