Repository HumanSignal/label-studio, pull requests merged in 2024-05, with the labels that each got.

#5809 docs: DOC-212: Added updated_at definitions to JSON property descriptions
  docs/source/guide/export.md
  docs/source/includes/task_format.md
Labels: docs

#5815 docs: DOC-210: Add information about ML backend data access
  docs/source/guide/ml.md
  docs/source/guide/ml_create.md
Labels: docs

#5792 fix: LEAP-851: Fix security vulnerability
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/version.json
  web/package.json
Labels: fix, Confirmed

#5816 docs: Add data discovery tip to import page
  docs/source/guide/tasks.md
Labels: docs

#5819 fix: pre-commit when --all-files is use on manual, for example in 'make fmt-al'
  .pre-commit-dev.yaml
Labels: fix

#5831 docs: GliNER image for tutorial
  docs/source/tutorials/gliner.png
Labels: docs

#5842 fix: #5787 Support uppercased version of "COLLECT_ANALYTICS" env var
  .github/workflows/test_migrations.yml
  .github/workflows/tests.yml
  docs/source/guide/security.md
  label_studio/core/settings/base.py
Labels: fix

#5844 fix: LEAP-889: remove env_vars from context log
  label_studio/core/settings/base.py
  label_studio/core/utils/contextlog.py
  label_studio/tests/conftest.py
  label_studio/tests/test_contextlog.py
Labels: fix

#5859 docs: Fix link color on mobile nav on Label Studio
  docs/themes/v2/source/css/styles.css
Labels: docs

#5862 docs: Fix playground condition issue
  docs/themes/v2/layout/partials/header.ejs
Labels: docs

#5868 docs: fix width of playground
  docs/source/guide/release_notes.md
  docs/source/playground/index.ejs
Labels: docs

#5869 ci: PLT-348: Automerge DependaBot PRs
  .github/workflows/cicd_pipeline.yml
Labels: ci

#5877 fix: RND-56: Fix some errors with api schema
  label_studio/io_storages/all_api.py
  label_studio/organizations/api.py
  label_studio/projects/api.py
Labels: fix

#5823 docs: OPTIC-528: Docs for annotator dashboards
  docs/source/guide/dashboard_annotator.md
  docs/source/guide/dashboard_project.md
  docs/source/guide/dashboards.md
  docs/themes/v2/source/images/project/annotator_dashboard.png
  docs/themes/v2/source/images/project/annotator_dashboard_graph.png
  docs/themes/v2/source/images/project/annotator_dashboard_summary.png
  docs/themes/v2/source/images/project/user_report.png
Labels: docs

#5887 docs: Update source storage diagrams
  docs/themes/v2/source/images/source-storages-treat-off.png
  docs/themes/v2/source/images/source-storages-treat-on.png
Labels: docs

#5889 docs: Add word break to avoid layout bug
  docs/themes/v2/source/css/styles.css
Labels: docs

#5882 fix: DIA-1116: Deleting predictions timing out
  label_studio/ml_models/models.py
Labels: fix

#5861 feat: LEAP-1026: Add option for including annotation history
  label_studio/data_export/mixins.py
  label_studio/data_export/serializers.py
Labels: feat, Confirmed

#5895 ci: Keep biome version sync
  .pre-commit-config.yaml
  .pre-commit-dev.yaml
  web/biome.json
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/version.json
Labels: ci

#5908 feat: RND-72: Add vendor extensions support in openapi autoschema
  label_studio/core/settings/base.py
  label_studio/core/utils/openapi_extensions.py
  label_studio/data_import/api.py
  label_studio/ml/api.py
  label_studio/tasks/api.py
  label_studio/users/api.py
Labels: feat

#5886 feat: LEAP-1063: Support history in csv
  poetry.lock
  pyproject.toml
Labels: feat, Confirmed

#5909 feat: RND-70: Add experimental action to cache labels and search over cached data field
  label_studio/data_manager/actions/cache_labels.py
  label_studio/data_manager/actions/experimental.py
  label_studio/tests/data_manager/test_api_actions.py
Labels: feat

#5911 fix: RND-74: Generate swagger.json
  Makefile
  label_studio/core/settings/base.py
  label_studio/projects/api.py
  label_studio/tasks/api.py
Labels: fix

#5891 feat: LEAP-1060: Add event to allow control annotations submitting
  web/libs/editor/src/stores/AppStore.js
Labels: feat

#5893 fix: LEAP-1089: Adjust SENTRY_RATE for LSO
  label_studio/core/settings/base.py
Labels: fix

#5919 docs: DOC-216: Move LDAP sections to a separate page
  docs/source/guide/auth_ldap.md
  docs/source/guide/auth_setup.md
Labels: docs

#5915 fix: RND-75: Add paginated response schema for tasks
  label_studio/projects/api.py
  label_studio/projects/serializers.py
  label_studio/tasks/api.py
Labels: fix

#5924 docs: Add Discourse link in the sidebar
  docs/themes/v2/layout/partials/toc.ejs
Labels: docs

#5936 feat: DIA-978: [BE] Deprecate S3-based Adala inference workflow
  label_studio/ml_models/models.py
Labels: feat
