Repository HumanSignal/label-studio, pull requests merged in 2024-10, with the labels that each got.

#6408 feat: OPTIC-1095: Send the started_at time of when annotation work had began
  web/libs/datamanager/src/sdk/lsf-sdk.js
Labels: feat, Confirmed

#6424 chore: OPTIC-1151: Extract font family to a constant
  label_studio/core/static/css/main.css
  web/apps/labelstudio/src/app/App.scss
  web/apps/labelstudio/src/components/Button/Button.scss
  web/apps/labelstudio/src/components/Error/Error.scss
  web/apps/labelstudio/src/components/Form/Elements/Select/Select.scss
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.scss
  web/apps/labelstudio/src/pages/CreateProject/Config/codemirror.css
  web/apps/labelstudio/src/pages/DataManager/DataManager.scss
  web/apps/labelstudio/src/themes/default/typography.scss
  web/libs/datamanager/public/index.html
  web/libs/editor/src/assets/styles/global.scss
  web/libs/editor/src/components/Settings/Settings.scss
  web/libs/editor/src/components/SidePanels/DetailsPanel/DetailsPanel.scss
  web/libs/editor/src/components/Taxonomy/Taxonomy.module.scss
  web/libs/editor/src/mixins/HighlightMixin.js
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/src/utils/__tests__/canvas.test.js
  web/libs/editor/src/utils/canvas.js
Labels: chore, Confirmed

#6469 fix: OPTIC-1179: Removing org_membership nested in user from membership API response
  label_studio/organizations/serializers.py
Labels: fix

#6473 feat: OPTIC-1183: Improve is_delete flow
  label_studio/users/models.py
  label_studio/users/serializers.py
Labels: feat

#6474 fix: OPTIC-1184: Using deleted_organization_members from context if available
  label_studio/users/serializers.py
Labels: fix

#6454 feat: LEAP-1492: More flexible Custom buttons
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/editor/src/components/BottomBar/Controls.tsx
  web/libs/editor/src/components/BottomBar/__tests__/Controls.test.tsx
  web/libs/editor/src/components/BottomBar/buttons.tsx
  web/libs/editor/src/stores/AppStore.js
  web/libs/editor/src/stores/CustomButton.ts
  web/libs/editor/src/stores/types.d.ts
  web/libs/editor/src/utils/__tests__/utilities.test.js
  web/libs/editor/src/utils/utilities.ts
Labels: feat, Confirmed

#6459 feat: LEAP-1445: Add comments overlay
  web/libs/editor/src/components/App/App.jsx
  web/libs/editor/src/components/Comments/Comment/CommentForm.scss
  web/libs/editor/src/components/Comments/Comment/CommentItem.scss
  web/libs/editor/src/components/Comments/Comment/CommentItem.tsx
  web/libs/editor/src/components/Comments/Comment/CommentsList.tsx
  web/libs/editor/src/components/Comments/Comment/LinkState.scss
  web/libs/editor/src/components/Comments/Comment/LinkState.tsx
  web/libs/editor/src/components/Comments/Comments.tsx
  web/libs/editor/src/components/InteractiveOverlays/BoundingBox.js
  web/libs/editor/src/components/InteractiveOverlays/CommentsOverlay.module.scss
  web/libs/editor/src/components/InteractiveOverlays/CommentsOverlay.tsx
  web/libs/editor/src/components/InteractiveOverlays/Geometry.js
  web/libs/editor/src/components/InteractiveOverlays/NodesConnector.js
  web/libs/editor/src/components/InteractiveOverlays/RelationShape.js
  web/libs/editor/src/components/InteractiveOverlays/RelationsOverlay.jsx
  web/libs/editor/src/components/InteractiveOverlays/watchers/DOMWatcher.js
  web/libs/editor/src/components/InteractiveOverlays/watchers/PropertyWatcher.js
  web/libs/editor/src/components/InteractiveOverlays/watchers/index.js
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  web/libs/editor/src/regions/BrushRegion.jsx
  web/libs/editor/src/stores/Comment/Anchor.js
  web/libs/editor/src/stores/Comment/Comment.js
  web/libs/editor/src/stores/Comment/CommentStore.js
  web/libs/editor/src/stores/types.d.ts
Labels: feat, Confirmed

#6489 refactor: OPTIC-1200: stale ff fflag_feat_all_optic_114_soft_delete_f…
  label_studio/core/feature_flags/base.py
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6490 docs: DOC-254: Prompts updates
  docs/source/guide/prompts_draft.md
Labels: docs

#6486 feat: LEAP-1441: Allow to connect comments to classifications
  web/libs/editor/src/components/Comments/Comment/CommentForm.tsx
  web/libs/editor/src/components/Comments/Comment/CommentItem.scss
  web/libs/editor/src/components/Comments/Comment/CommentItem.tsx
  web/libs/editor/src/components/Comments/Comment/LinkState.scss
  web/libs/editor/src/components/Comments/Comment/LinkState.tsx
  web/libs/editor/src/components/InteractiveOverlays/BoundingBox.js
  web/libs/editor/src/components/InteractiveOverlays/CommentsOverlay.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionDetails.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/TreeView.scss
  web/libs/editor/src/regions/Area.js
  web/libs/editor/src/stores/Annotation/LinkingModes.js
  web/libs/editor/src/stores/Annotation/LinkingModes/CommentMode.js
  web/libs/editor/src/stores/Comment/Anchor.js
  web/libs/editor/src/stores/Comment/Comment.js
  web/libs/editor/src/stores/Comment/CommentStore.js
  web/libs/editor/src/stores/types.d.ts
  web/libs/editor/src/tags/control/Choices.jsx
  web/libs/editor/src/tags/control/ClassificationBase.js
  web/libs/editor/src/tags/control/DateTime.jsx
  web/libs/editor/src/tags/control/Number.jsx
  web/libs/editor/src/tags/control/Rating.jsx
  web/libs/editor/src/tags/control/Taxonomy/Taxonomy.jsx
  web/libs/editor/src/tags/control/TextArea/TextArea.jsx
Labels: feat, Confirmed

#6212 feat: add region:visibility-all shortcut (ctrl+h)
  web/libs/editor/src/core/settings/keymap.json
  web/libs/editor/src/stores/AppStore.js
Labels: feat

#6501 ci: LEAP-1553: Fix path-to-regexp CVE
  web/yarn.lock
Labels: ci

#6470 feat: LEAP-1474: Create and display comments with classifications
  web/libs/datamanager/src/sdk/comments-sdk.js
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/editor/src/components/Comments/Comment/CommentForm.scss
  web/libs/editor/src/components/Comments/Comment/CommentForm.tsx
  web/libs/editor/src/components/Comments/Comment/CommentFormButtons.scss
  web/libs/editor/src/components/Comments/Comment/CommentFormButtons.tsx
  web/libs/editor/src/components/Comments/Comment/CommentItem.scss
  web/libs/editor/src/components/Comments/Comment/CommentItem.tsx
  web/libs/editor/src/components/NewTaxonomy/NewTaxonomy.tsx
  web/libs/editor/src/stores/AppStore.js
  web/libs/editor/src/stores/Comment/Comment.js
  web/libs/editor/src/stores/Comment/CommentStore.js
  web/libs/editor/src/utils/commentClassification.ts
Labels: feat

#6504 fix: LEAP-1583: Fix comment overlay displaying conditions
  web/libs/editor/src/components/App/App.jsx
Labels: fix, Confirmed

#6496 fix: LEAP-1494: Padding in new textarea is missing in LSO
  web/apps/labelstudio/src/themes/default/colors.scss
  web/apps/labelstudio/src/themes/default/layout.scss
  web/apps/labelstudio/src/themes/default/variables.scss
  web/libs/editor/src/regions/TextAreaRegion/TextAreaRegion.scss
  web/libs/ui/src/tokens/layout.scss
  web/webpack.config.js
Labels: fix, Confirmed

#6505 docs: Clarify reviewer setting
  docs/source/guide/project_settings_lse.md
Labels: docs

#6519 ci: LEAP-1417 LEAP-1544 LEAP-1546: CVE fixes
  web/yarn.lock
Labels: ci

#6523 fix: LEAP-1586: Fix CommentsOverlay display without preloading image functionality
  web/libs/editor/src/components/InteractiveOverlays/CommentsOverlay.tsx
Labels: fix, Confirmed

#6521 docs: DOC-258: Add new reject setting for reviewers
  docs/source/guide/project_settings_lse.md
Labels: docs

#6531 docs: Add OpenAI signup link to Prompts docs
  docs/source/guide/prompts_create.md
Labels: docs

#6532 feat: LEAP-1476: Add ability to edit classifications on existing comments
  web/libs/editor/src/components/Comments/Comment/CommentForm.tsx
  web/libs/editor/src/components/Comments/Comment/CommentItem.scss
  web/libs/editor/src/components/Comments/Comment/CommentItem.tsx
  web/libs/editor/src/components/Comments/Comment/CommentsList.tsx
  web/libs/editor/src/components/Comments/CommentFormBase.tsx
  web/libs/editor/src/stores/Comment/Comment.js
  web/libs/editor/src/utils/commentClassification.ts
Labels: feat

#6514 feat: RND-124: Make clear error descriptions in Sent Test Request for ML backend
  label_studio/ml/api.py
Labels: feat

#6535 fix: LEAP-1596: Missed check for review_settings
  web/libs/datamanager/src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#6530 fix: OPTIC-1229: Remove if getattr(settings, 'CLOUD_INSTANCE', False)
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/users/models.py
  label_studio/users/serializers.py
Labels: fix, Confirmed

#6534 chore: LEAP-1275: Bump sentry-sdk to fix vulnerability, py3.13 compatibility, remove py3.8 support
  .github/workflows/tests.yml
  label_studio/core/utils/windows_sqlite_fix/__init__.py
  label_studio/data_import/uploader.py
  label_studio/server.py
  poetry.lock
  pyproject.toml
Labels: chore

#6533 docs: DOC-256: Comments page rewrite
  docs/source/guide/comments_notifications.md
  docs/themes/v2/source/images/review/comment_actions.png
  docs/themes/v2/source/images/review/comment_links.gif
  docs/themes/v2/source/images/review/comment_panel.png
  docs/themes/v2/source/images/review/comments.png
  docs/themes/v2/source/images/review/comments_columns.png
Labels: docs

#6522 fix: LEAP-1449: Don't highlight instructions button
  web/libs/datamanager/src/components/Label/LabelButtons.js
  web/libs/datamanager/src/components/Label/Toolbar/Toolbar.jsx
  web/libs/datamanager/src/components/Label/Toolbar/Toolbar.scss
  web/libs/editor/src/components/BottomBar/Actions.jsx
Labels: fix, Confirmed

#6526 feat: LEAP-1592: Hide task navigation arrow based on setting
  web/libs/datamanager/src/sdk/lsf-sdk.js
Labels: feat, Confirmed

#6541 fix: LEAP-1577: Fix saving linked results at backend
  web/libs/editor/src/stores/Comment/Comment.js
Labels: fix, Confirmed

#6537 fix: LEAP-1581: Improve styles in new comments
  web/libs/editor/src/components/Comments/Comment/CommentForm.scss
  web/libs/editor/src/components/Comments/Comment/CommentItem.scss
  web/libs/editor/src/components/Comments/Comment/LinkState.scss
  web/libs/editor/src/components/InteractiveOverlays/CommentsOverlay.module.scss
Labels: fix, Confirmed

#6538 chore: OPTIC-1234: add examples of how to mock the api endpoint for runtime
  web/apps/labelstudio/src/config/ApiConfig.example.js
  web/apps/labelstudio/src/pages/DataManager/api-config.example.js
  web/apps/labelstudio/src/utils/api-proxy.js
  web/libs/datamanager/src/utils/api-proxy/index.js
Labels: chore, Confirmed

#6546 fix: LEAP-1579: LEAP-1576: LEAP-1582: Improve comment icons usability
  web/libs/editor/src/components/InteractiveOverlays/CommentsOverlay.tsx
  web/libs/editor/src/components/InteractiveOverlays/NodesConnector.js
  web/libs/editor/src/regions/Result.js
  web/libs/editor/src/stores/Comment/Anchor.js
  web/libs/editor/src/tags/control/ClassificationBase.js
Labels: fix, Confirmed

#6561 docs: Add more about anchor point in Rectangles
  docs/source/tags/rectangle.md
  docs/source/tags/rectanglelabels.md
  docs/source/templates/image_bbox.md
  web/libs/editor/src/tags/control/Rectangle.js
  web/libs/editor/src/tags/control/RectangleLabels.jsx
Labels: docs

#6529 docs: DOC-255: Custom models for Prompts
  docs/source/guide/prompts_create.md
  docs/source/guide/prompts_overview.md
  docs/themes/v2/source/images/prompts/base_models.png
  docs/themes/v2/source/images/prompts/model_keys.png
Labels: docs

#6539 feat: LEAP-1533: Make Quick View readonly by condition
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/stores/AppStore.js
Labels: feat, Confirmed

#6574 refactor: OPTIC-1269: Clean stale flags file
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6544 feat: LEAP-1515: Hide PII by condition
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/editor/src/components/AnnotationTabs/AnnotationTabs.jsx
  web/libs/editor/src/components/AnnotationsCarousel/AnnotationButton.scss
  web/libs/editor/src/components/AnnotationsCarousel/AnnotationButton.tsx
  web/libs/editor/src/components/Comments/Comment/CommentItem.tsx
  web/libs/editor/src/components/CurrentEntity/AnnotationHistory.tsx
Labels: feat, Confirmed

#6576 refactor: OPTIC-1270: Remove Stale Feature Flag - fflag_feat_front_prod_309_choice_hint_080523_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/Taxonomy/Taxonomy.tsx
  web/libs/editor/src/tags/control/Choice.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/integration/feature-flags.ts
Labels: refactor

#6572 feat: LEAP-1601: Add custom_task_lock_ttl field
  label_studio/projects/migrations/0027_project_custom_task_lock_ttl.py
  label_studio/projects/models.py
Labels: feat

#6573 feat: OPTIC-1232: Customize the display of notifications form block in user settings
  label_studio/users/templates/users/user_account.html
Labels: feat, Confirmed

#6584 refactor: OPTIC-915: Remove Stale Feature Flag - fflag_feat_front_lsdv_3025_outliner_filter_short
  web/libs/editor/src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/integration/e2e/outliner/filter.cy.ts
Labels: refactor
