Repository HumanSignal/label-studio, pull requests merged in 2024-04, with the labels that each got.

#5536 docs: DOC-164: Updates for task agreement threshold settings
  docs/source/guide/project_settings_lse.md
  docs/source/guide/stats.md
Labels: docs

#5674 fix: OPTIC-514: Dashboards page crashes when opened on project with no imported tasks
  label_studio/data_manager/managers.py
Labels: fix

#5679 docs: Fix README with poetry
  README.md
Labels: docs

#5658 fix: LEAP-919: Add script to update ML backend tutorials from readme
  scripts/update_ml_tutorials.py
Labels: fix

#5678 fix: LEAP-824: Postfixes for remove duplicates
  label_studio/data_manager/actions/remove_duplicates.py
  label_studio/tests/data_manager/test_api_actions.py
Labels: fix, Confirmed

#5683 docs: DOC-205: Uploading image files for ML tutorials
  docs/source/tutorials/bert.png
  docs/source/tutorials/create-simple-ml-backend.png
  docs/source/tutorials/easyocr.png
  docs/source/tutorials/flair.png
  docs/source/tutorials/grounding-dino.png
  docs/source/tutorials/hf-llm.png
  docs/source/tutorials/hf-ner.png
  docs/source/tutorials/huggingface.png
  docs/source/tutorials/langchain.png
  docs/source/tutorials/llm-interactive.png
  docs/source/tutorials/nvidia.png
  docs/source/tutorials/openai.png
  docs/source/tutorials/openmmlab.png
  docs/source/tutorials/pytorch.png
  docs/source/tutorials/scikit-learn.png
  docs/source/tutorials/segment-anything.png
  docs/source/tutorials/spacy.png
  docs/source/tutorials/tesseract.png
Labels: docs

#5682 docs: DOC-207: Add a warning about importing files through the LS UI
  docs/source/guide/tasks.md
Labels: docs

#5686 fix: RND-9: Local File Storage doesn't work with token and raises 403
  label_studio/core/views.py
  scripts/update_ml_tutorials.py
Labels: fix

#5697 fix: LEAP-930: Autoselect model as prelabeler when its added
  label_studio/ml/api.py
  label_studio/projects/serializers.py
  label_studio/tests/ml/test_api.py
  label_studio/tests/predictions.model.tavern.yml
Labels: fix

#5684 fix: OPTIC-391: Tasks rendered incomplete by low agreement should not count on project cards
  label_studio/projects/models.py
Labels: fix, Confirmed

#5713 fix: LEAP-930: Improve ML related texts in settings
  web/apps/labelstudio/src/pages/Settings/AnnotationSettings.js
  web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningList.js
  web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningList.styl
  web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningSettings.js
  web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningSettings.styl
Labels: fix

#5719 feat: DIA-957: Delete predictions when ModelVersion updated or ModelR…
  label_studio/ml_models/models.py
Labels: feat

#5720 feat: OPTIC-650: Add feature flag to enable task format in export storages
  label_studio/io_storages/base_models.py
  label_studio/io_storages/s3/models.py
Labels: feat

#5744 docs: Changes to 3 tutorial images
  docs/source/tutorials/flair.png
  docs/source/tutorials/langchain.png
  docs/source/tutorials/openmmlab.png
Labels: docs

#5750 ci: PLT-76: Remove Aha! leftovers from GH workflows
  .github/helpers/gh_changelog_generator/gh_changelog_generator.py
  .github/workflows/cicd_pipeline.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/validator-pull-request-labeler.yml
Labels: ci

#5642 docs: DOC-205: Document changes to ML backend
  docs/source/guide/active_learning.md
  docs/source/guide/ml.md
  docs/source/guide/ml_create.md
  docs/source/guide/project_settings.md
  docs/source/guide/project_settings_lse.md
Labels: docs

#5758 fix: LEAP-1023: Fix misspelled LocalFilesImportStorageLink in remove_duplicates
  label_studio/data_manager/actions/remove_duplicates.py
  label_studio/tests/data_manager/test_api_actions.py
Labels: fix

#5718 fix: LEAP-999: Fix E2E tests on LSO
  .github/workflows/tests-yarn-e2e.yml
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/main.js
  web/dist/libs/editor/version.json
  web/libs/editor/tests/e2e/codecept.conf.js
  web/libs/editor/tests/e2e/yarn.lock
Labels: fix

#5756 docs: DOC-211: Note Data Discovery search result limits
  docs/source/guide/dataset_overview.md
  docs/source/guide/dataset_search.md
Labels: docs

#5763 chore: OPTIC-590: Bump express from 4.17.1 to 4.19.2 in /web/libs/editor/tests/e2e
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/version.json
  web/libs/editor/tests/e2e/yarn.lock
Labels: chore

#5764 fix: OPTIC-650: Add feature flag to enable task format in export storages, postfixes
  label_studio/io_storages/base_models.py
Labels: fix

#5772 fix: LEAP-1029: Unify an approach of processing requests for suggestions
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/version.json
  web/libs/editor/tests/e2e/tests/smart-tools.history.test.js
Labels: fix, Confirmed

#5612 fix: LEAP-884: avoid reading entire files to memory in export api
  label_studio/core/utils/io.py
  label_studio/data_export/api.py
  label_studio/data_export/mixins.py
  label_studio/data_export/models.py
  label_studio/tasks/functions.py
Labels: fix

#5785 chore: LEAP-1017: bump sqlparse for security (and psycopg2 to unblock 3.12)
  poetry.lock
  pyproject.toml
Labels: chore

#5801 docs: Add image for ML backend example
  docs/source/tutorials/interactive-substring-matching.png
Labels: docs

#5761 fix: DIA-1061: Start Training should send START_TRAINING event as webhook instead of PROJECT_UPDATE
  docs/source/guide/webhook_reference.md
  label_studio/ml/api_connector.py
  label_studio/tests/webhooks/test_webhooks.py
Labels: fix

#5806 ci: PLT-340: Fix ChatOps Validate command step
  .github/workflows/slash-command-dispatch.yml
Labels: ci
