Repository HumanSignal/label-studio, pull requests merged in 2024-03, with the labels that each got.

#5516 feat: DIA-858: Endpoint for getting tasks for prompter workflow
  label_studio/core/all_urls.json
  label_studio/projects/api.py
  label_studio/projects/urls.py
  label_studio/tests/test_projects.tavern.yml
  label_studio/tests/test_suites/samples/three_tasks_two_gts.json
Labels: feat

#5496 feat: OPTIC-478: Implement Feature Flag to Control Visibility and Access of Cloud Storage Connectors for Managers
  label_studio/core/settings/base.py
  label_studio/io_storages/all_api.py
  label_studio/io_storages/api.py
  label_studio/io_storages/permissions.py
  web/apps/labelstudio/src/pages/Settings/StorageSettings/StorageSettings.js
  web/apps/labelstudio/src/pages/Settings/index.js
  web/apps/labelstudio/src/utils/feature-flags.js
  web/apps/labelstudio/src/utils/feature-flags.ts
  web/apps/labelstudio/src/utils/helpers.ts
  web/apps/labelstudio/src/utils/license-flags.ts
  web/dist/apps/labelstudio/main.js
Labels: feat, Confirmed

#5523 feat: DIA-881: Only allow owner and admin to create/modify provider c…
  label_studio/ml_model_providers/models.py
Labels: feat

#5534 docs: DOC-197: Doc updates for project-level roles in the UI
  docs/source/guide/project_settings_lse.md
  docs/source/guide/setup_project.md
  docs/themes/v2/source/images/project/member_roles.png
Labels: docs

#5542 docs: Add info about task formatting in Redis Source Storage
  docs/source/guide/storage.md
Labels: docs

#5547 docs: DOC-199: Update main README for monorepo changes
  README.md
Labels: docs

#5551 docs: DOC-200: Add note about LSF standalone repo deprecation
  docs/source/guide/frontend.md
  docs/source/guide/frontend_reference.md
Labels: docs

#5562 feat: LEAP-818: Add X-Api-Key support
  label_studio/core/middleware.py
  label_studio/core/settings/base.py
  label_studio/tests/test_api.py
Labels: feat

#5576 docs: DOC-202: Update steps for installing from source
  docs/source/guide/install.md
Labels: docs

#5574 fix: OPTIC-513: Handle task assignment with priority for low agreement where available
  label_studio/projects/functions/next_task.py
Labels: fix, Confirmed

#5561 feat: DIA-939: Trigger Adala inference from ModelRun creation
  label_studio/ml_models/migrations/0004_modelrun_job_id.py
  label_studio/ml_models/models.py
Labels: feat

#5581 docs: DOC-203: Fix collected information section
  docs/source/guide/security.md
Labels: docs

#5572 feat: LEAP-824: Remove duplicated tasks with moving of annotations
  label_studio/data_manager/actions/experimental.py
  label_studio/data_manager/actions/remove_duplicates.py
  label_studio/tests/data_manager/test_api_actions.py
Labels: feat

#5567 feat: DIA-940: Read Adala predictions back in once they are completed
  label_studio/ml_models/models.py
  label_studio/tasks/migrations/0046_prediction_model_run.py
  label_studio/tasks/models.py
Labels: feat

#5564 feat: LEAP-819: Add 3 labeling config templates about interactive ml backend
  label_studio/annotation_templates/computer-vision/segment-anything/config.yml
  label_studio/annotation_templates/generative-ai/prompt-engineering-chat/config.yml
  label_studio/annotation_templates/generative-ai/prompt-engineering-text/config.yml
  label_studio/core/static/templates/chat-completion.jpg
  label_studio/core/static/templates/prompt-engineering.jpg
  label_studio/core/static/templates/segment-anything.jpg
Labels: feat

#5597 ci: fix typo in e2e.ts
  web/libs/frontend-test/src/bin/assets/e2e.ts
Labels: title needs formatting

#5602 ci: PLT-248: fix codecov fixes path
  codecov.yml
Labels: ci

#5603 fix: OPTIC-553: Import fails when user.active_organization is None
  label_studio/tasks/serializers.py
Labels: fix

#5605 fix: LEAP-868: Reinstate google cloud logging dependency
  poetry.lock
  pyproject.toml
Labels: fix

#5593 fix: OPTIC-509: Per project role does not work with low agreement annotator assignment
  label_studio/projects/functions/next_task.py
  label_studio/users/mixins.py
Labels: fix, Confirmed

#5606 chore: LEAP-770: Update some vulnerable deps
  poetry.lock
Labels: chore

#5604 feat: DIA-980: Stream results from Adala into LSE
  label_studio/ml_models/migrations/0005_auto_20240319_1738.py
  label_studio/ml_models/models.py
Labels: feat

#5617 ci: PLT-213: Generate frontend version files inside Docker
  .dockerignore
  .github/workflows/build_pypi.yml
  .github/workflows/frontend-build.yml
  Dockerfile
  web/dist/apps/labelstudio/main.js
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/version.json
Labels: ci

#5621 fix: OPTIC-572: The Retrieve Predictions modal is not formatted prop…
  label_studio/data_manager/actions/basic.py
Labels: fix

#5631 fix: OPTIC-574: Inconsistent behavior on Create Annotations From Predictions
  label_studio/data_manager/actions/predictions_to_annotations.py
  label_studio/projects/models.py
  label_studio/tests/data_manager/actions/test_predictions_to_annotations.py
Labels: fix

#5613 feat: DIA-974: add predictions info to results
  label_studio/core/all_urls.json
  label_studio/projects/api.py
  label_studio/projects/urls.py
  label_studio/tests/test_projects.tavern.yml
Labels: feat

#5628 feat: LEAP-219: Update LSF E2E with recent changes
  web/dist/apps/labelstudio/version.json
  web/dist/libs/datamanager/version.json
  web/dist/libs/editor/main.js
  web/dist/libs/editor/version.json
  web/libs/editor/tests/e2e/examples/data/sample-sin.json
  web/libs/editor/tests/e2e/examples/image-keypoints.js
  web/libs/editor/tests/e2e/fragments/AtImageView.js
  web/libs/editor/tests/e2e/fragments/AtOutliner.js
  web/libs/editor/tests/e2e/fragments/AtPanels.js
  web/libs/editor/tests/e2e/fragments/AtTaxonomy.js
  web/libs/editor/tests/e2e/fragments/AtTimeSeries.js
  web/libs/editor/tests/e2e/fragments/Modals.js
  web/libs/editor/tests/e2e/plugins/errorsCollector.js
  web/libs/editor/tests/e2e/plugins/featureFlags.js
  web/libs/editor/tests/e2e/plugins/stepLogsModifier.js
  web/libs/editor/tests/e2e/tests/audio/audio-errors.test.js
  web/libs/editor/tests/e2e/tests/helpers.js
  web/libs/editor/tests/e2e/tests/history.test.js
  web/libs/editor/tests/e2e/tests/image.gestures.test.js
  web/libs/editor/tests/e2e/tests/image.magic-wand.test.js
  web/libs/editor/tests/e2e/tests/image.selected-region.test.js
  web/libs/editor/tests/e2e/tests/image.test.js
  web/libs/editor/tests/e2e/tests/image.transformer.test.js
  web/libs/editor/tests/e2e/tests/maxUsage.test.js
  web/libs/editor/tests/e2e/tests/ner-text.test.js
  web/libs/editor/tests/e2e/tests/nested-choices.test.js
  web/libs/editor/tests/e2e/tests/ocr.test.js
  web/libs/editor/tests/e2e/tests/outliner.test.js
  web/libs/editor/tests/e2e/tests/paragraphs-filter.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/brush-relations.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/dynamic-choices.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/hotkey.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-ctrl-drawing.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-draw-undo.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-width.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-zoom-position.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-zoom-transform.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/numpad-hotkeys.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/outliner-regions-dnd.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/preselected-choices.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/richtext.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/video-meta.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/wrong-results-order.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/zoomed-image-displaying.test.js
  web/libs/editor/tests/e2e/tests/repeater-paginate-scroll.test.js
  web/libs/editor/tests/e2e/tests/shortcuts.test.js
  web/libs/editor/tests/e2e/tests/smart-tools.history.test.js
  web/libs/editor/tests/e2e/tests/table.test.js
  web/libs/editor/tests/e2e/tests/taxonomy.test.js
  web/libs/editor/tests/e2e/tests/text-area.test.js
  web/libs/editor/tests/e2e/tests/textarea.skip-duplicates.test.js
  web/libs/editor/tests/e2e/tests/timeseries.test.js
  web/libs/editor/tests/e2e/tests/toggle-visibility.test.js
  web/libs/editor/tests/e2e/tests/unfinished-polygons.test.js
Labels: feat

#5636 docs: Add Starter cloud redirect
  docs/netlify.toml
Labels: docs

#5619 docs: DIA-963: Add README to the ml_models, lse_ml_models and lse_ml_providers sub-package in LSE
  label_studio/ml_model_providers/README.md
  label_studio/ml_models/README.md
Labels: docs

#5637 Remove interactive templates
  label_studio/annotation_templates/computer-vision/segment-anything/config.yml
  label_studio/annotation_templates/generative-ai/prompt-engineering-chat/config.yml
  label_studio/annotation_templates/generative-ai/prompt-engineering-text/config.yml
  label_studio/core/static/templates/chat-completion.jpg
  label_studio/core/static/templates/prompt-engineering.jpg
  label_studio/core/static/templates/segment-anything.jpg
Labels: title needs formatting

#5641 fix: DIA-1005: Remove unused property from ModelRun
  label_studio/ml_models/models.py
Labels: fix

#5647 ci: PLT-288: Add codecov flags
  .github/workflows/tests.yml
Labels: ci
