Repository HumanSignal/label-studio, pull requests merged in 2024-08, with the labels that each got.

#6135 fix: LEAP-762: Fix offsets in domManager for emojis
  web/libs/editor/src/tags/object/RichText/domManager.md
  web/libs/editor/src/tags/object/RichText/domManager.ts
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/tests/integration/data/ner/emoji.ts
  web/libs/editor/tests/integration/e2e/ner/emoji.cy.ts
  web/libs/frontend-test/src/helpers/LSF/LabelStudio.ts
  web/libs/frontend-test/src/helpers/LSF/RichText.ts
Labels: fix, Confirmed, test

#6100 feat: LEAP-1198: Add labeling unsaved changes warning
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/app/AsyncPage/AsyncPage.jsx
  web/apps/labelstudio/src/components/LeaveBlocker/LeaveBlocker.tsx
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/Config/UnsavedChanges.tsx
  web/apps/labelstudio/src/pages/Settings/LabelingSettings.jsx
  web/apps/labelstudio/src/providers/ApiProvider.d.ts
  web/apps/labelstudio/src/providers/ProjectProvider.tsx
  web/apps/labelstudio/src/utils/api-proxy.js
  web/apps/labelstudio/src/utils/feature-flags.ts
Labels: feat, Confirmed

#6129 docs: Remove Beta tags and notes
  docs/source/guide/dataset_overview.md
  docs/source/guide/prompts_overview.md
  docs/themes/v2/layout/partials/toc.ejs
Labels: docs

#6160 chore: LEAP-1261: bump setuptools
  poetry.lock
Labels: chore

#6165 docs: Update SDK link
  docs/source/guide/sdk.md
Labels: docs

#6171 docs: Add alerts
  docs/.gitignore
  docs/scripts/alert.js
  docs/scripts/checkIfFileExists.js
  docs/themes/v2/layout/partials/header.ejs
  docs/themes/v2/source/css/styles.css
  docs/yarn.lock
Labels: docs

#6154 docs: DOC-230: Documentation for custom scripts
  docs/source/guide/label_studio_compare.md
  docs/source/guide/script_examples.md
  docs/source/guide/scripts.md
  docs/themes/v2/source/images/project/autolabeling.gif
  docs/themes/v2/source/images/project/bulk_actions.gif
  docs/themes/v2/source/images/project/plotly.png
  docs/themes/v2/source/images/project/script_json.png
  docs/themes/v2/source/images/project/script_validation.png
  docs/themes/v2/source/images/project/scripts.png
Labels: docs

#6159 refactor: OPTIC-912: Remove Stale Feature Flag - fflag_feat_front_prod_e_111_annotator_workflow_control_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/BottomBar/Controls.jsx
  web/libs/editor/src/utils/feature-flags.ts
Labels: feat, refactor

#6158 refactor: OPTIC-910: Remove Stale Feature Flag - fflag_feat_front_lsdv_5518_snap_to_pixel_130923_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/tags/control/Base.js
  web/libs/editor/src/utils/feature-flags.ts
Labels: feat, refactor

#6164 fix: LEAP-1358: Update config for relevant hasChanges value after prettifying
  web/apps/labelstudio/src/pages/Settings/LabelingSettings.jsx
Labels: fix, Confirmed

#6179 ci: Fix typo
  .github/workflows/release-pipeline.yml
Labels: ci

#6156 fix: OPTIC-310: Make sure database support multiple export storages of the same kind
  label_studio/io_storages/base_models.py
  label_studio/io_storages/migrations/0017_auto_20240731_1638.py
Labels: fix, Confirmed

#5896 chore: LEAP-1090: django 4.2 upgrade (WIP)
  docker-compose.yml
  docs/source/guide/email_setup.md
  label_studio/core/middleware.py
  label_studio/core/settings/base.py
  label_studio/core/utils/mail.py
  label_studio/core/utils/static_serve.py
  label_studio/data_manager/managers.py
  label_studio/data_manager/migrations/0012_alter_view_user.py
  label_studio/io_storages/migrations/0018_alter_azureblobexportstorage_project_and_more.py
  label_studio/projects/models.py
  label_studio/pytest.ini
  label_studio/tasks/api.py
  label_studio/tasks/models.py
  label_studio/users/urls.py
  label_studio/users/views.py
  poetry.lock
  pyproject.toml
Labels: chore

#6189 feat: DIA-1122: Add ability to store FailedPredictions
  label_studio/ml_models/models.py
  label_studio/tasks/migrations/0048_failedprediction.py
  label_studio/tasks/models.py
Labels: feat

#6209 fix: OPTIC-1013: Adding fast_first_or_create util function
  label_studio/core/utils/db.py
Labels: fix

#6214 chore: LEAP-1368: switch to git version of NLTK 3.8.2
  poetry.lock
Labels: chore

#6220 chore: LEAP-1378: bump nltk to 3.9.1 to get off git tag version
  poetry.lock
Labels: chore

#6201 feat: DIA-1321: [BE] Create Prompt with the NER problem type
  label_studio/ml_models/migrations/0010_modelinterface_skill_name.py
  label_studio/ml_models/models.py
Labels: feat

#6222 docs: edit enterprise note style in docs
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/images/design/enterprise-icon.svg
Labels: docs

#6224 refactor: OPTIC-1024: Clean code TableOld
  web/libs/datamanager/src/components/Common/Table/Table.jsx
  web/libs/datamanager/src/components/Common/Table/Table.scss
  web/libs/datamanager/src/components/Common/Table/TableCheckbox.jsx
  web/libs/datamanager/src/components/Common/Table/TableHead/TableHead.jsx
  web/libs/datamanager/src/components/Common/Table/TableHead/TableHead.scss
  web/libs/datamanager/src/components/Common/Table/TableRow/TableRow.jsx
  web/libs/datamanager/src/components/Common/Table/TableRow/TableRow.scss
  web/libs/datamanager/src/components/Common/TableOld/Table.jsx
  web/libs/datamanager/src/components/Common/TableOld/Table.scss
  web/libs/datamanager/src/components/Common/TableOld/TableCell/TableCell.jsx
  web/libs/datamanager/src/components/Common/TableOld/TableCheckbox.jsx
  web/libs/datamanager/src/components/Common/TableOld/TableContext.js
  web/libs/datamanager/src/components/Common/TableOld/TableHead/TableHead.jsx
  web/libs/datamanager/src/components/Common/TableOld/TableHead/TableHead.scss
  web/libs/datamanager/src/components/Common/TableOld/TableRow/TableRow.jsx
  web/libs/datamanager/src/components/Common/TableOld/TableRow/TableRow.scss
  web/libs/datamanager/src/components/Common/TableOld/utils.js
  web/libs/datamanager/src/components/MainView/DataView/Table.jsx
Labels: refactor

#6215 docs: DOC-233: Doc updates for adding Azure API keys
  docs/source/guide/prompts_create.md
  docs/source/guide/prompts_draft.md
  docs/source/guide/prompts_overview.md
  docs/themes/v2/source/images/prompts/azure_deployment.png
  docs/themes/v2/source/images/prompts/base_models.png
  docs/themes/v2/source/images/prompts/model_keys.png
Labels: docs

#6190 fix: LEAP-1363: View all is loading even when value is empty for RichText
  web/libs/editor/src/mixins/HighlightMixin.js
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/src/tags/object/RichText/view.jsx
Labels: fix, Confirmed

#6231 fix: DIA-1350: Fallback to saved models incase provider is down
  label_studio/ml_model_providers/migrations/0003_modelproviderconnection_cached_available_models.py
  label_studio/ml_model_providers/models.py
Labels: fix

#6208 fix: OPTIC-1011: Making OneToOne to ForeignKey migration better
  label_studio/io_storages/migrations/0017_auto_20240731_1638.py
  label_studio/io_storages/migrations/0018_alter_azureblobexportstorage_project_and_more.py
Labels: fix

#6236 refactor: OPTIC-1031: Remove Stale Feature Flag - ff_front_DEV_1507_stuck_userpic_210122_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/common/Userpic/Userpic.tsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor

#6238 refactor: OPTIC-1033: Remove Stale Feature Flag - ff_front_dev_1598_empty_toname_240222_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor

#6235 refactor: OPTIC-1030: Remove Stale Feature Flag - ff_back_1587_email_notifications_310122_long
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#6041 docs: Fix playground links
  docs/themes/v2/source/js/code-blocks-enhancements.js
Labels: docs

#6234 refactor: OPTIC-1029: Remove Stale Feature Flag - ff_front_dev_1285_crosshair_wrong_zoom_140122_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/ImageView/ImageView.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor

#6241 refactor: OPTIC-1028: Remove Stale Feature Flag - ff_front_dev_1372_visible_when_choice_unselected_11022022_short
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: Confirmed, refactor

#6188 refactor: OPTIC-989: Removed unused stylus files
  web/libs/editor/src/themes/default/scrollbar.styl
  web/libs/editor/src/themes/default/tools/scrollbar.styl
  web/libs/editor/src/themes/default/tools/waiting.styl
Labels: fix, Confirmed, refactor

#6227 chore: LEAP-1201: djangorestframework package update
  label_studio/core/all_urls.json
  label_studio/labels_manager/serializers.py
  poetry.lock
  pyproject.toml
Labels: chore

#6250 ci: Fix RichText docs to unblock docs auto-generation
  web/libs/editor/src/tags/object/RichText/model.js
Labels: ci

#6255 fix: RND-120: Redis storage doesn't have db field and redis target misses validation_connection()
  label_studio/io_storages/redis/form_layout.yml
  label_studio/io_storages/redis/models.py
Labels: fix

#6257 chore: OPTIC-990: Remove Stylus and supporting libraries
  web/libs/editor/jest.config.js
  web/package.json
  web/webpack.config.js
  web/yarn.lock
Labels: chore, Confirmed

#6260 refactor: OPTIC 932 remove stale feature flags
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/HtxTextBox/HtxTextBox.jsx
  web/libs/editor/src/regions/TextAreaRegion.jsx
  web/libs/editor/src/tags/control/Shortcut.jsx
  web/libs/editor/src/tags/control/TextArea/TextArea.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/tests/shortcuts.test.js
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor

#6268 fix: grid-css fix
  web/libs/datamanager/src/components/MainView/GridView/GridView.styl
Labels: fix

#6248 docs: DOC-239: Add information about rectangle rotation
  docs/source/tags/rectangle.md
  docs/source/tags/rectanglelabels.md
  docs/source/templates/image_bbox.md
  docs/themes/v2/source/images/rectangle_db_rotation.jpg
  docs/themes/v2/source/images/rectangle_ui_rotation.jpg
  web/libs/editor/src/tags/control/Rectangle.js
  web/libs/editor/src/tags/control/RectangleLabels.jsx
Labels: docs

#6269 fix: grid-css fix
  web/libs/datamanager/src/components/MainView/GridView/GridView.styl
Labels: fix

#6278 fix: OPTIC-1058: Ensure all css variables converted from stylus to scss are valid properties.
  web/apps/labelstudio/src/components/Modal/Modal.scss
  web/apps/labelstudio/src/components/Spinner/Spinner.scss
  web/libs/editor/src/common/Button/Button.scss
  web/libs/editor/src/common/Tag/Tag.scss
  web/libs/editor/src/components/SidePanels/DetailsPanel/DetailsPanel.scss
  web/libs/editor/src/components/SidePanels/PanelBase.scss
  web/libs/editor/src/components/SidePanels/TabPanels/PanelTabsBase.scss
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.scss
Labels: fix

#6163 fix: OPTIC-960: Improve the bundling strategy and ship a single entrypoint with a common vendor chunk across all libs
  web/libs/editor/src/utils/feature-flags.ts
Labels: fix, Confirmed

#6285 docs: DOC-240: Update regex custom script example
  docs/source/guide/script_examples.md
Labels: docs
