Repository HumanSignal/label-studio, pull requests merged in 2025-08, with the labels that each got.

#8037 feat: BROS-199: Enhanced paragraph annotation with auto-selection
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/defaults.js
  web/libs/editor/src/core/settings/keymap.json
  web/libs/editor/src/mixins/HighlightMixin.js
  web/libs/editor/src/stores/SettingsStore.js
  web/libs/editor/src/tags/object/Paragraphs/HtxParagraphs.jsx
  web/libs/editor/src/tags/object/Paragraphs/Paragraphs.module.scss
  web/libs/editor/src/tags/object/Paragraphs/Phrases.jsx
  web/libs/editor/src/tags/object/Paragraphs/__tests__/Phrases.test.tsx
  web/libs/editor/src/tags/object/Paragraphs/model.js
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/fragments/AtParagraphs.js
  web/libs/editor/tests/e2e/helpers/PlaywrightAddon.js
  web/libs/editor/tests/e2e/tests/maxUsage.test.js
  web/libs/editor/tests/e2e/tests/paragraphs-enhanced.test.js
  web/libs/editor/tests/e2e/tests/paragraphs-filter.test.js
  web/libs/editor/tests/integration/e2e/sync/audio_paragraphs.cy.ts
Labels: feat

#8073 fix: BROS-269: Ensure page refresh is not required when changing hotkeys
  web/libs/app-common/src/pages/AccountSettings/hooks/useHotkeys.ts
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/utils.ts
  web/libs/editor/src/LabelStudio.tsx
Labels: fix

#8087 chore: 2.27.0 cherry-pick fix: BROS-274: Update hotkeys.ts (#8085)
  web/libs/datamanager/src/sdk/hotkeys.ts
Labels: fix, chore

#8079 fix: PLT-842: Check if sync is already queued
  label_studio/io_storages/base_models.py
Labels: fix

#8092 fix: BROS-277: Fix DM crash with empty shortcut
  web/libs/editor/src/core/Hotkey.ts
Labels: fix

#8093 fix: BROS-277: Fix page crash with undefined hotkey
  web/libs/editor/src/core/Hotkey.ts
Labels: fix

#8100 chore: ROOT-67: use new version of Poetry in all workflows + docker
  .github/workflows/build_pypi.yml
  .github/workflows/docker-build.yml
  .github/workflows/follow-merge-upstream-repo-sync-v2.yml
  .github/workflows/test_conda.yml
  .github/workflows/test_migrations.yml
  .github/workflows/tests.yml
  .github/workflows/update_pip_dependency.yml
  Dockerfile
  Dockerfile.development
Labels: chore

#8098 fix: Add beta tag for hotkeys
  web/libs/app-common/src/pages/AccountSettings/AccountSettings.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/index.tsx
Labels: fix

#8114 fix: Optimize prediction import for memory efficiency
  label_studio/core/settings/base.py
  label_studio/data_import/api.py
Labels: fix

#8123 docs: Fixes for storage.md and azure spi
  docs/source/guide/storage.md
Labels: docs

#8138 fix: BROS-202: Fix for the cursor state on waveform
  web/libs/editor/src/lib/AudioUltra/Interaction/InteractionManager.ts
Labels: fix

#8143 fix: ROOT-72: stop serializing List filters as lists for now
  Dockerfile
  web/libs/datamanager/src/stores/Tabs/filter_utils.ts
Labels: fix

#8154 feat: FIT-493: Make left column of User Assigner infinitely paginated and searchable
  web/libs/ui/src/lib/select/select.tsx
Labels: feat

#8160 chore: ROOT-74: use HOSTNAME to set servers in fern
  label_studio/core/settings/base.py
Labels: chore

#8210 fix: FIT-554: Searching for an item in filters duplicates the previously selected item (#8202)
  web/libs/ui/src/lib/select/select.tsx
Labels: fix

#8226 fix: FIT-570: Async task assignments user feedback (#8206)
  poetry.lock
  pyproject.toml
Labels: fix

#8241 fix: Prevent duplicate ImageEntity IDs in React StrictMode
  web/libs/editor/src/tags/object/Image/Image.js
Labels: fix

#8265 docs: Update Prompts section in comparison page
  docs/source/guide/label_studio_compare.md
Labels: docs

#8264 docs: Add page for embeds
  docs/source/guide/embed.md
  docs/themes/v2/source/images/embed-demo.png
  docs/themes/v2/source/images/org-id.png
Labels: docs

#8296 docs fix
  docs/source/templates/html_ner_tagging_person_and_organization.md
  docs/source/templates/two_level_sentiment_analysis_of_x_twitter_posts.md
  label_studio/annotation_templates/community-contributions/ner-tagging-invoices-bio-format/config.xml
  label_studio/annotation_templates/community-contributions/ner-tagging-invoices-bio-format/config.yml
Labels: title needs formatting
