Repository HumanSignal/label-studio, pull requests merged in 2025-03, with the labels that each got.

#7161 chore: rewrite LSO PR template
  .github/pull_request_template.md
Labels: chore

#7162 remove unnecessary newlines
  .github/pull_request_template.md
Labels: title needs formatting

#7172 fix: OPTIC-1780: Ignoring PermissionDenied exceptions in Sentry
  label_studio/core/settings/base.py
  label_studio/core/utils/sentry.py
Labels: fix, Confirmed

#7163 fix: DIA-1982: update agreement when converting preds to annots
  label_studio/data_manager/actions/predictions_to_annotations.py
Labels: fix

#7182 fix: DIA-2022: UI&UX | Issue with zoom functionality in Label Studio labelling UI
  web/libs/editor/src/components/ImageView/Image.jsx
  web/libs/editor/src/components/ImageView/ImageView.module.scss
Labels: fix

#7186 fix: DIA-2024: [lso][re-opened-via-tailwind] Fix body-parser vulnerable to denial of service when url encoding is enabled
  web/package.json
  web/yarn.lock
Labels: fix

#7100 fix: DIA-1927: [FE] Data on organization section are incorrect on new account settings page
  label_studio/users/serializers.py
  poetry.lock
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/utils/query-client.ts
  web/libs/core/src/blocks/TokenSettingsModal/styles.module.scss
  web/libs/core/src/pages/AccountSettings/AccountSettings.module.scss
  web/libs/core/src/pages/AccountSettings/sections/MembershipInfo.tsx
  web/libs/core/src/types/user.ts
Labels: fix

#7173 refactor: LEAP-1907: Migrate EnterpriseBadge to UI library
  web/apps/labelstudio/src/components/Badges/Enterprise.scss
  web/apps/labelstudio/src/components/Badges/Enterprise.tsx
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/apps/labelstudio/src/pages/Settings/GeneralSettings.jsx
  web/libs/ui/src/assets/icons/index.ts
  web/libs/ui/src/assets/icons/spark.svg
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/enterprise-badge/enterprise-badge.module.scss
  web/libs/ui/src/lib/enterprise-badge/enterprise-badge.stories.tsx
  web/libs/ui/src/lib/enterprise-badge/enterprise-badge.tsx
Labels: Confirmed, refactor

#7203 fix: DIA-2028: [BE] Membership API call for organization with ID=2574 results in ERROR 500 on develop
  label_studio/users/serializers.py
Labels: fix

#7207 fix: DIA-2028: [BE] Membership API call for organization with ID=2574 results in ERROR 500 on develop
  label_studio/users/serializers.py
Labels: fix

#7196 feat: OPTIC-1265: Improve error pages
  label_studio/core/static/css/error.css
  label_studio/core/static/images/heidi-403.svg
  label_studio/core/static/images/heidi-404.svg
  label_studio/core/static/images/heidi-500.svg
  label_studio/core/urls.py
  label_studio/core/views.py
  label_studio/templates/401.html
  label_studio/templates/403.html
  label_studio/templates/404.html
  label_studio/templates/500.html
Labels: feat, FM Stale

#7208 fix: DIA-2026: allow annotators/reviewers to view jwt settings
  label_studio/jwt_auth/models.py
  label_studio/jwt_auth/views.py
  label_studio/tests/jwt_auth/test_models.py
Labels: fix

#7209 fix: OPTIC-1749: Limit only sentry_force error logs to go to Sentry
  label_studio/core/utils/sentry.py
  label_studio/projects/functions/next_task.py
Labels: fix, FM Stale

#7178 feat: DIA-1926: return annots/preds in sample data
  label_studio/projects/api.py
  label_studio/projects/tests/test_project_sample_task.py
  poetry.lock
  pyproject.toml
Labels: feat

#7165 feat: LEAP-1896: Add scrollbar support to Visualizer
  web/libs/editor/src/lib/AudioUltra/Common/Utils.ts
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
  web/libs/editor/src/lib/AudioUltra/Waveform.ts
  web/libs/editor/src/tags/object/AudioUltra/model.js
  web/libs/frontend-test/src/helpers/LSF/AudioView.ts
Labels: feat, Confirmed

#7210 fix: OPTIC-1794: Improve handling of missing tasks and projects when fetching data within DataManager
  web/apps/labelstudio/src/pages/DataManager/DataManager.jsx
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/stores/DataStores/tasks.js
Labels: fix, Confirmed, FM Stale

#7166 feat: LEAP-1893: LEAP-1900: Add setting to toggle region looping and autoplay
  web/libs/core/src/lib/hooks/usePersistentState.test.ts
  web/libs/core/src/lib/hooks/usePersistentState.ts
  web/libs/editor/src/components/Timeline/Controls/AudioControl.scss
  web/libs/editor/src/components/Timeline/Controls/ConfigControl.scss
  web/libs/editor/src/components/Timeline/Controls/ConfigControl.tsx
  web/libs/editor/src/components/Timeline/Controls/Info.scss
  web/libs/editor/src/components/Timeline/Controls/Info.tsx
  web/libs/editor/src/components/Timeline/Controls/Slider.scss
  web/libs/editor/src/components/Timeline/Controls/Slider.tsx
  web/libs/editor/src/components/Timeline/Types.ts
  web/libs/editor/src/lib/AudioUltra/Controls/Player.ts
  web/libs/editor/src/lib/AudioUltra/Regions/Regions.ts
  web/libs/editor/src/lib/AudioUltra/Waveform.ts
  web/libs/editor/src/lib/AudioUltra/react/index.ts
  web/libs/editor/src/tags/object/AudioUltra/view.tsx
  web/libs/ui/src/lib/label/label.module.scss
  web/libs/ui/src/lib/label/label.tsx
  web/libs/ui/src/lib/toggle/toggle.tsx
  web/package.json
  web/yarn.lock
Labels: feat, Confirmed, FM Stale

#7183 fix: OPTIC-1785: Validate S3 bucket name on storage connection form
  label_studio/io_storages/s3/serializers.py
Labels: fix, FM Stale

#7217 feat: OPTIC-1749: Only send 5XX API Exceptions to Sentry
  label_studio/core/label_config.py
  label_studio/core/settings/base.py
  label_studio/core/utils/common.py
  label_studio/core/utils/exceptions.py
  label_studio/data_import/api.py
  label_studio/projects/models.py
Labels: feat, FM Stale

#7180 fix: LEAP-1892: [FE] Deeply nested Choices are visible when their parents are hidden
  web/libs/editor/src/mixins/Visibility.js
  web/libs/editor/src/regions/Result.js
  web/libs/editor/tests/integration/data/control_tags/visibility.ts
  web/libs/editor/tests/integration/e2e/control_tags/visibility.cy.ts
  web/libs/frontend-test/src/helpers/LSF/Choices.ts
Labels: fix, Confirmed, FM Stale

#7239 docs: Fix parent ID reference
  docs/source/includes/task_format.md
Labels: docs

#7240 docs: Fix parent ID reference, try 2
  docs/source/includes/task_format.md
Labels: docs

#7213 refactor: LEAP-1289: Remove outliner FF_OUTLINER_OPTIM feature flag
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerPanel.scss
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/TreeView.scss
  web/libs/editor/src/components/SidePanels/TabPanels/Tabs.scss
  web/libs/editor/src/components/SidePanels/TabPanels/Tabs.tsx
  web/libs/editor/src/tags/control/TextArea/TextArea.scss
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/setup/feature-flags.js
  web/libs/editor/tests/integration/e2e/outliner/region_tree.cy.ts
  web/libs/editor/tests/integration/feature-flags.ts
Labels: Confirmed, refactor

#7218 refactor: LEAP-1290: remove feature flag FF_LOPS_E_10 and related code
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/datamanager/src/assets/icons/index.js
  web/libs/datamanager/src/assets/icons/refresh2.svg
  web/libs/datamanager/src/components/Common/Button/Button.jsx
  web/libs/datamanager/src/components/Common/Button/Button.scss
  web/libs/datamanager/src/components/Common/FiltersPane.jsx
  web/libs/datamanager/src/components/Common/Form/Elements/Input/Input.jsx
  web/libs/datamanager/src/components/Common/Form/Elements/Input/Input.scss
  web/libs/datamanager/src/components/Common/RadioGroup/RadioGroup.jsx
  web/libs/datamanager/src/components/Common/RadioGroup/RadioGroup.scss
  web/libs/datamanager/src/components/Common/Table/Table.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/ActionsButton.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/ActionsButton.scss
  web/libs/datamanager/src/components/DataManager/Toolbar/RefreshButton.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/TabPanel.scss
  web/libs/datamanager/src/components/DataManager/Toolbar/Toolbar.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/instruments.jsx
  web/libs/datamanager/src/utils/feature-flags.js
Labels: Confirmed, refactor

#7241 chore: OPTIC-1632: Convert Figma design tokens to CSS and Tailwind
  web/apps/labelstudio/src/themes/default/tokens.scss
  web/design-tokens.json
  web/libs/ui/project.json
  web/libs/ui/src/styles.scss
  web/libs/ui/src/tailwind.config.js
  web/libs/ui/src/tokens/colors.scss
  web/libs/ui/src/tokens/tokens.js
  web/libs/ui/src/tokens/tokens.scss
  web/package.json
  web/tools/design-tokens-converter/README.md
  web/tools/design-tokens-converter/design-tokens-converter
  web/tools/design-tokens-converter/design-tokens-converter.mjs
  web/tools/design-tokens-converter/package.json
Labels: chore, Confirmed, FM Stale

#7243 chore: OPTIC-1714: Update esbuild to a non vulnerable version
  web/package.json
  web/yarn.lock
Labels: chore, Confirmed, FM Stale

#7228 refactor: LEAP-1300: Remove outdated FF_LSDV_4620_3
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/InteractiveOverlays/BoundingBox.js
  web/libs/editor/src/core/feature-flags/flags.json
  web/libs/editor/src/mixins/HighlightMixin.js
  web/libs/editor/src/regions/RichTextRegion.js
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/src/tags/object/RichText/view.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/src/utils/selection-tools.js
  web/libs/editor/tests/e2e/setup/feature-flags.js
  web/libs/editor/tests/e2e/tests/regression-tests/richtext.test.js
  web/libs/editor/tests/e2e/tests/rich-text/rich-text-basic-functional.test.js
  web/libs/editor/tests/e2e/tests/rich-text/rich-text-edge-cases.test.js
  web/libs/editor/tests/e2e/tests/rich-text/rich-text-perfomance.test.js
  web/libs/editor/tests/e2e/tests/rich-text/rich-text-regions-displaying.test.js
  web/libs/editor/tests/e2e/tests/rich-text/rich-text-regions-interactions.test.js
  web/libs/editor/tests/integration/e2e/ner/emoji.cy.ts
  web/libs/editor/tests/integration/feature-flags.ts
Labels: Confirmed, refactor

#7211 refactor: LEAP-1772: Remove FF_OPTIC_2 feature flag and associated logic
  label_studio/core/feature_flags/stale_feature_flags.py
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/components/DraftGuard/DraftGuard.jsx
  web/apps/labelstudio/src/pages/DataManager/DataManager.jsx
  web/libs/core/src/lib/utils/feature-flags.ts
  web/libs/datamanager/src/components/MainView/DataView/Table.jsx
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/datamanager/src/utils/feature-flags.js
Labels: Confirmed, refactor, FM Stale

#7254 fix: OPTIC-1832: Missing tokens scss variables import (#7253)
  web/apps/labelstudio/src/themes/default/variables.scss
Labels: fix

#7242 chore: OPTIC-1725: Update cryptography to a non vulnerable version
  poetry.lock
  pyproject.toml
Labels: chore, Confirmed, FM Stale

#7258 fix: DIA-1942: Fix Information exposure through an exception
  label_studio/jwt_auth/views.py
Labels: fix

#7216 fix: OPTIC-1809: Adding option to only update last_activity after a significant difference
  label_studio/core/settings/base.py
  label_studio/users/models.py
Labels: fix

#7212 fix: LEAP-649: Saving draft on task switching
  web/libs/datamanager/src/sdk/lsf-sdk.js
Labels: fix, Confirmed, FM Stale

#7244 fix: LEAP-1931: Correct frame offset calculation in Timeline
  web/libs/editor/src/components/Timeline/Views/Frames/Frames.tsx
Labels: fix, Confirmed, FM Stale

#7220 refactor: LEAP-1296: remove FF_LOPS_86 feature flag
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/datamanager/src/components/MainView/DataView/Table.jsx
  web/libs/datamanager/src/utils/feature-flags.js
Labels: Confirmed, refactor

#7248 fix: LEAP-1913: Update axios to v1.8.2
  web/libs/editor/tests/e2e/package.json
  web/libs/editor/tests/e2e/yarn.lock
Labels: fix, Confirmed

#7250 fix: LEAP-1868: Update serialize-javascript version
  web/package.json
  web/yarn.lock
Labels: fix, Confirmed

#7249 fix: LEAP-1925: Update axios and dependencies
  web/package.json
  web/yarn.lock
Labels: fix, Confirmed

#7259 fix: OPTIC-1835: Address issue affecting OCR region panel visualization
  web/libs/editor/src/components/Comments/Comment/CommentFormButtons.scss
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/TreeView.scss
  web/libs/editor/src/tags/control/TextArea/TextArea.scss
  web/libs/editor/src/tags/control/TextArea/TextAreaRegionView.jsx
Labels: fix, FM Stale

#7226 feat: DIA-1925: [FE] “View sample raw json” ability in the Data Import page
  label_studio/projects/api.py
  label_studio/projects/tests/test_project_sample_task.py
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/ImportModal.jsx
  web/apps/labelstudio/src/pages/CreateProject/utils/atoms.ts
  web/apps/labelstudio/src/pages/CreateProject/utils/useDraftProject.js
  web/apps/labelstudio/src/providers/ProjectProvider.tsx
  web/libs/core/src/lib/utils/feature-flags.ts
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/code-block/code-block.tsx
  web/libs/ui/src/lib/simple-card/index.tsx
Labels: feat, FM Stale

#7247 chore: OPTIC-1825: Update project to use React 18
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/Config/TemplatesList.jsx
  web/apps/labelstudio/src/pages/Settings/AnnotationSettings/ModelVersionSelector.jsx
  web/libs/editor/src/components/AnnotationsCarousel/__tests__/AnnotationButton.test.tsx
  web/libs/editor/src/components/AnnotationsCarousel/__tests__/AnnotationsCarousel.test.tsx
  web/libs/editor/src/components/AnnotationsCarousel/__tests__/sampleData.js
  web/libs/editor/src/components/Hint/Hint.test.js
  web/libs/editor/src/components/Hint/__snapshots__/Hint.test.js.snap
  web/libs/editor/src/components/SidePanels/__tests__/PanelBase.test.tsx
  web/libs/editor/src/regions/BrushRegion.jsx
  web/libs/editor/src/setupTests.js
  web/libs/editor/src/tags/visual/__tests__/Header.test.jsx
  web/package.json
  web/tsconfig.base.json
  web/yarn.lock
Labels: chore, Confirmed, FM Stale

#7251 feat: LEAP-1924: Allow to edit Timeline span by drag-n-drop
  web/libs/editor/src/components/SidePanels/DetailsPanel/TimelineRegionEditor.tsx
  web/libs/editor/src/components/Timeline/Timeline.tsx
  web/libs/editor/src/components/Timeline/Types.ts
  web/libs/editor/src/components/Timeline/Views/Frames/Frames.tsx
  web/libs/editor/src/components/Timeline/Views/Frames/Keypoints.tsx
  web/libs/editor/src/regions/TimelineRegion.js
  web/libs/editor/src/tags/object/Video/Video.js
Labels: feat, Confirmed, FM Stale

#7268 fix: OPTIC-1809: Revert "Adding option to only update last_activity after a significant difference"
  label_studio/core/settings/base.py
  label_studio/users/models.py
Labels: fix

#7206 feat: DIA-1924: "Import sample data" ability in the Data Import page
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.scss
  web/apps/labelstudio/src/pages/CreateProject/Import/ImportModal.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/samples.json
  web/apps/labelstudio/src/pages/CreateProject/Import/useImportPage.js
  web/apps/labelstudio/src/pages/CreateProject/Import/utils.ts
  web/apps/labelstudio/src/utils/feature-flags.ts
  web/libs/core/src/blocks/SampleDatasetSelect/SampleDatasetSelect.tsx
  web/libs/core/src/index.ts
  web/libs/core/src/lib/utils/feature-flags/ff.ts
  web/libs/core/src/lib/utils/feature-flags/flags.ts
  web/libs/core/src/pages/AccountSettings/sections/index.tsx
  web/libs/ui/src/shad/components/ui/select.tsx
  web/libs/ui/src/tailwind.config.js
Labels: feat, FM Stale

#7273 fix: OPTIC-1850: 'n is not a function' RUNTIME error occur on ls-develop when user tries to create a project
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/libs/core/src/pages/AccountSettings/sections/PersonalInfo.tsx
  web/libs/editor/src/components/CurrentEntity/AnnotationHistory.tsx
Labels: fix, Confirmed, FM Stale

#7276 fix: DIA-1925: fix payload for sample task in data import
  web/apps/labelstudio/src/pages/CreateProject/utils/atoms.ts
Labels: fix

#7284 test: DIA-2103: update project path for test
  label_studio/feature_flags.json
  label_studio/tests/users.tavern.yml
Labels: test

#7280 fix: OPTIC-1857: User can NOT import data from Import modal from DataManager page
  web/apps/labelstudio/src/pages/CreateProject/Import/ImportModal.jsx
Labels: fix, Confirmed, FM Stale

#7269 chore: OPTIC-1842: Update the css variables for colors to support RGB and drop the primitive prefixes on all variables
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/Home/HomePage.tsx
  web/libs/core/src/blocks/SampleDatasetSelect/SampleDatasetSelect.tsx
  web/libs/storybook/.storybook/preview.scss
  web/libs/ui/src/shad/components/ui/badge.tsx
  web/libs/ui/src/shad/components/ui/button.tsx
  web/libs/ui/src/tailwind.config.js
  web/libs/ui/src/tailwind.css
  web/libs/ui/src/tokens/colors.scss
  web/libs/ui/src/tokens/tokens.js
  web/libs/ui/src/tokens/tokens.scss
  web/libs/ui/src/tokens/tokens.stories.tsx
  web/libs/ui/src/typography/sub.tsx
  web/package.json
  web/tools/design-tokens-converter/README.md
  web/tools/design-tokens-converter/design-tokens-converter.mjs
  web/yarn.lock
Labels: chore

#7229 refactor: OPTIC-927: remove FF_DEV_2432 feature flag
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/regions/PolygonRegion.jsx
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/tools/Polygon.js
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/examples/image-polygons.js
  web/libs/editor/tests/e2e/fragments/AtSidebar.js
  web/libs/editor/tests/e2e/tests/image-labels.test.js
  web/libs/editor/tests/e2e/tests/image.gestures.test.js
  web/libs/editor/tests/e2e/tests/image.transformer.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-ctrl-drawing.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-draw-undo.test.js
  web/libs/editor/tests/e2e/tests/unfinished-polygons.test.js
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor, FM Stale

#7291 fix: OPTIC-1858: Avoid the possible condition which would destroy the LSF instance right before it requires it to load a task
  web/libs/datamanager/src/components/Label/Label.jsx
Labels: fix

#7285 fix: DIA-2103: re-enable jwt token FF
  label_studio/feature_flags.json
  label_studio/tests/conftest.py
  label_studio/tests/drafts.tavern.yml
  label_studio/tests/webhooks/organizations.tavern.yml
Labels: fix

#7296 fix: OPTIC-1858: Wait for LSF to be initialized
  web/libs/datamanager/src/stores/AppStore.js
Labels: fix

#7297 fix: OPTIC-1858: Wait for LSF and currentAnnotation to be available before completing task init
  web/libs/datamanager/src/stores/AppStore.js
Labels: fix

#7286 chore: OPTIC-1337 Update tooltips
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore

#7272 fix: DIA-2097: [FE] Create Project modal closes automatically when user is at Home Page
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/CreateProject/utils/useDraftProject.js
  web/apps/labelstudio/src/pages/Home/HomePage.tsx
Labels: fix, FM Stale

#7301 fix: DIA-2116: Export storages can be incorrectly retrieved as import storages
  label_studio/projects/models.py
  label_studio/tasks/models.py
Labels: fix

#7299 fix: OPTIC-1858: Wait for the store and currentAnnotation before proceeding to complete task initialization in Datamanager Quickview
  web/apps/labelstudio/src/pages/DataManager/DataManager.jsx
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/datamanager/src/stores/AppStore.js
Labels: fix, Confirmed, FM Stale

#7304 fix: DIA-2096: don't use is_owner in LSO (#7277)
  label_studio/jwt_auth/models.py
Labels: fix

#7290 ci: OPTIC-1873: Update biome to last version
  .pre-commit-config.yaml
  .pre-commit-dev.yaml
  web/apps/labelstudio/src/components/Modal/ModalPopup.jsx
  web/biome.json
  web/libs/core/src/lib/hooks/usePersistentState.ts
  web/libs/datamanager/src/components/Common/Button/Button.jsx
  web/libs/datamanager/src/components/Common/Modal/ModalPopup.jsx
  web/libs/datamanager/src/components/Filters/types/List.jsx
  web/libs/editor/src/common/Modal/ModalPopup.jsx
  web/libs/editor/src/components/AnnotationTabs/AnnotationTabs.jsx
  web/libs/editor/src/components/SidePanels/PanelBase.tsx
  web/libs/editor/src/components/SidePanels/SidePanels.tsx
  web/libs/editor/src/components/SidePanels/TabPanels/PanelTabsBase.tsx
  web/libs/editor/src/components/SidePanels/TabPanels/SideTabsPanels.tsx
  web/libs/editor/src/core/Hotkey.ts
  web/libs/editor/src/core/Tree.tsx
  web/libs/editor/src/hooks/useLocalStorageState.ts
  web/libs/editor/src/lib/AudioUltra/Timeline/Timeline.ts
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
  web/libs/editor/src/lib/AudioUltra/Waveform.ts
  web/libs/editor/src/regions/KeyPointRegion.jsx
  web/libs/editor/src/stores/RegionStore.js
  web/libs/editor/src/tags/object/Paragraphs/model.js
  web/package.json
  web/yarn.lock
Labels: ci
