Repository HumanSignal/label-studio, pull requests merged in 2025-06, with the labels that each got.

#7664 chore: FIT-174: Refactor DataManager Table out into reusable component
  web/libs/datamanager/src/components/Common/Table/Table.jsx
  web/libs/datamanager/src/components/Common/Table/TableHead/TableHead.scss
  web/libs/datamanager/src/components/Label/Label.scss
  web/libs/datamanager/src/components/MainView/DataView/Table.scss
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/auto-sizer-table/auto-sizer-table.tsx
  web/package.json
  web/yarn.lock
Labels: chore

#7674 fix: Update feature_flags.json for playground
  label_studio/feature_flags.json
Labels: fix

#7673 docs: OPTIC-2125: Docs for sync between TimeSeries, Video, Audio
  docs/source/templates/gallery_timeseries.ejs
  docs/source/templates/timeseries_audio_video.md
  label_studio/core/static/templates/timeseries_audio_video.png
Labels: docs

#7678 docs: Update ts+video.md
  docs/source/guide/ts+video.md
Labels: docs

#7672 feat: UTC-67: Cherry-picking Fixes into Version 2.24
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/libs/app-common/src/pages/AccountSettings/sections/EmailPreferences.tsx
  web/libs/datamanager/src/components/Common/Form/Elements/Select/Select.jsx
  web/libs/datamanager/src/components/Filters/FilterDropdown.jsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionEditor.tsx
  web/libs/ui/src/lib/select/select.tsx
  web/libs/ui/src/lib/select/types.ts
Labels: feat

#7682 fix: BROS-66: Update SyncableMixin mixin to respect FF_DEV_3391
  web/libs/editor/src/mixins/Syncable.ts
Labels: fix

#7695 fix: BROS-76: Revert "fix: BROS-66: Update SyncableMixin mixin to respect FF_DEV_3391
  web/libs/editor/src/mixins/Syncable.ts
Labels: fix, FM Stale

#7663 docs: Add default eval functions and new diagram
  docs/source/guide/stats.md
  docs/themes/v2/source/images/stats-agreement-example.png
Labels: docs

#7690 fix: UTC-74: [FE] Error Message on Numeric Value Field
  web/libs/editor/src/tags/control/Number.jsx
Labels: fix

#7699 feat: BROS-81: Toggle for proxy. Enhanced control for enabling storage proxy
  docs/source/guide/storage.md
  label_studio/core/settings/base.py
  label_studio/io_storages/serializers.py
Labels: feat

#7712 fix: UTC-90: Cherry-pick ui fixes for 2.25.0
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/libs/app-common/src/pages/AccountSettings/sections/EmailPreferences.tsx
  web/libs/datamanager/src/components/Common/Form/Elements/Select/Select.jsx
  web/libs/datamanager/src/components/Filters/FilterDropdown.jsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionEditor.tsx
  web/libs/ui/src/lib/select/select.tsx
  web/libs/ui/src/lib/select/types.ts
Labels: fix

#7720 fix: FIT-195: Playground breaks on certain Timeseries configurations
  web/apps/playground/src/utils/generateSampleTask.ts
Labels: fix

#7742 docs: Better API key example for PAT
  docs/source/guide/access_tokens.md
Labels: docs

#7704 feat: FIT-207: Fix text and layout data of import page
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.scss
Labels: feat

#7700 feat: ROOT-29: Build control tags dropdown for filtering labels within a specific tag
  web/libs/datamanager/src/components/DataManager/Toolbar/OrderButton.jsx
  web/libs/datamanager/src/components/Filters/FilterLine/FilterLine.jsx
  web/libs/datamanager/src/components/Filters/FilterLine/FilterOperation.jsx
  web/libs/datamanager/src/stores/Tabs/store.js
  web/libs/datamanager/src/stores/Tabs/tab.js
  web/libs/datamanager/src/stores/Tabs/tab_column.jsx
  web/libs/datamanager/src/stores/Tabs/tab_filter.js
  web/libs/datamanager/src/utils/feature-flags.js
Labels: feat, FM Stale

#7694 feat: BROS-73: [FE] Create empty states for panels: info, regions, relations, history
  web/libs/editor/jest.setup.js
  web/libs/editor/src/components/CurrentEntity/AnnotationHistory.scss
  web/libs/editor/src/components/CurrentEntity/AnnotationHistory.tsx
  web/libs/editor/src/components/SidePanels/Components/EmptyState.tsx
  web/libs/editor/src/components/SidePanels/Components/__tests__/EmptyState.test.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/DetailsPanel.scss
  web/libs/editor/src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/__tests__/DetailsPanel.test.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/__tests__/OutlinerPanel.test.tsx
  web/libs/editor/src/utils/docs.ts
  web/libs/editor/tests/e2e/fragments/AtOutliner.js
  web/libs/editor/tests/e2e/tests/helpers.js
  web/libs/editor/tests/e2e/tests/toggle-visibility.test.js
  web/libs/editor/tsconfig.spec.json
  web/libs/ui/src/assets/icons/history-rewind.svg
  web/libs/ui/src/assets/icons/polygon-tool.svg
  web/libs/ui/src/assets/icons/rectangle-tool.svg
Labels: feat, FM Stale

#7743 docs: ROOT-13: Annotation Results Filtering
  docs/source/guide/manage_data.md
  docs/themes/v2/source/images/data-manager-filters-lse.png
  docs/themes/v2/source/images/data-manager-filters.png
Labels: docs

#7796 fix: Revert "feat: BROS-87: Bitmask (#7766)"
  docs/source/includes/tags/bitmask.md
  docs/source/includes/tags/bitmasklabels.md
  web/libs/core/src/lib/utils/feature-flags/ff.ts
  web/libs/core/src/lib/utils/feature-flags/flags.ts
  web/libs/editor/src/components/ImageView/Image.jsx
  web/libs/editor/src/components/ImageView/ImageView.jsx
  web/libs/editor/src/components/InteractiveOverlays/BoundingBox.js
  web/libs/editor/src/components/Node/Node.tsx
  web/libs/editor/src/components/TaskSummary/labelings.tsx
  web/libs/editor/src/regions/Area.js
  web/libs/editor/src/regions/BitmaskRegion.jsx
  web/libs/editor/src/regions/BitmaskRegion/contour.ts
  web/libs/editor/src/regions/BitmaskRegion/utils.ts
  web/libs/editor/src/regions/Result.js
  web/libs/editor/src/regions/index.js
  web/libs/editor/src/tags/control/Bitmask.js
  web/libs/editor/src/tags/control/BitmaskLabels.jsx
  web/libs/editor/src/tags/control/Label.jsx
  web/libs/editor/src/tags/control/index.js
  web/libs/editor/src/tags/object/Image/Image.js
  web/libs/editor/src/tags/object/Image/ImageEntity.js
  web/libs/editor/src/tags/object/PagedView.jsx
  web/libs/editor/src/tags/visual/Collapse.jsx
  web/libs/editor/src/tags/visual/View.jsx
  web/libs/editor/src/tools/Bitmask.jsx
  web/libs/editor/src/tools/BitmaskErase.jsx
  web/libs/editor/src/tools/index.js
  web/libs/editor/tests/e2e/tests/regression-tests/bitmask.test.js
  web/package.json
  web/yarn.lock
Labels: fix

#7810 fix: Misspell in 0028_auto_20241107_1031.py
  label_studio/projects/migrations/0028_auto_20241107_1031.py
Labels: fix

#7782 feat: BROS-86: Task Summary follow-ups
  web/libs/editor/src/components/TaskSummary/DataSummary.tsx
  web/libs/editor/src/components/TaskSummary/LabelingSummary.tsx
  web/libs/editor/src/components/TaskSummary/TaskSummary.tsx
  web/libs/editor/src/components/TaskSummary/labelings.tsx
  web/libs/editor/src/stores/types.d.ts
Labels: feat

#7802 fix: BROS-95: Incorrect draft is loaded during task history navigation in label stream
  web/libs/datamanager/src/stores/DataStores/tasks.js
Labels: fix

#7800 fix: BROS-128: Fix large data multichannel displaying
  web/libs/editor/src/components/TimeSeries/TimeSeriesVisualizer.jsx
  web/libs/editor/tests/e2e/tests/toggle-visibility.test.js
Labels: fix

#7803 feat: UTC-121: As a user, I want to be able to publicly share a project so others can join HS with a copy of the project already created by clicking a button
  web/libs/ui/src/assets/icons/globe.svg
  web/libs/ui/src/assets/icons/index.ts
  web/libs/ui/src/assets/icons/pin.svg
  web/libs/ui/src/assets/icons/settings.svg
Labels: feat

#7806 fix: FIT-256: Upload limitations multi-image labeling hyperlinks data import modal do not open a new tab
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
Labels: fix, FM Stale

#7824 fix: FIT-250: SplitChannel audio with spectrogram displaying blank space on waveform (#7820)
  web/libs/editor/src/lib/AudioUltra/Visual/Renderer/WaveformRenderer.ts
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
Labels: fix

#7825 fix: FIT-250: SplitChannel audio with spectrogram displaying blank space on waveform (#7820)
  web/libs/editor/src/lib/AudioUltra/Visual/Renderer/WaveformRenderer.ts
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
Labels: fix

#7805 fix: BROS-109: Import Dropzone content area moved beyond fold if JSON preview is too large
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.scss
  web/libs/ui/src/lib/code-block/code-block.tsx
  web/libs/ui/src/lib/simple-card/index.tsx
Labels: fix, FM Stale

#7842 fix: FIT-263: Audio region start and end editor inputs not updating on change (#7829)
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionEditor.tsx
Labels: fix

#7855 fix: FIT-291,FIT-306: SplitChannel audio regions not covering the whole height, Zooming out the page breaks audio rendering of the wave form
  web/libs/editor/src/lib/AudioUltra/Visual/Layer.ts
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
Labels: fix

#7845 feat: UTC-137: Create a Typography component for Spark
  web/apps/labelstudio/src/pages/Home/HomePage.tsx
  web/jest.config.ts
  web/libs/storybook/.storybook/preview.scss
  web/libs/storybook/addons/theme-toggle/register.ts
  web/libs/ui/package.json
  web/libs/ui/project.json
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/typography/typography.module.scss
  web/libs/ui/src/lib/typography/typography.stories.tsx
  web/libs/ui/src/lib/typography/typography.tsx
  web/libs/ui/src/tailwind.config.js
  web/libs/ui/src/typography/heading.tsx
  web/libs/ui/src/typography/index.ts
  web/libs/ui/src/typography/sub.tsx
  web/tsconfig.base.json
Labels: feat

#7818 feat: FIT-222: Improve UX on Add/Update Source storage
  docs/source/guide/storage.md
  label_studio/io_storages/azure_blob/form_layout.yml
  label_studio/io_storages/gcs/form_layout.yml
  label_studio/io_storages/localfiles/form_layout.yml
  label_studio/io_storages/redis/form_layout.yml
  label_studio/io_storages/s3/form_layout.yml
  web/apps/labelstudio/src/components/Form/Elements/Input/Input.jsx
  web/apps/labelstudio/src/components/Form/Elements/Label/Label.jsx
  web/apps/labelstudio/src/components/Form/Elements/Label/Label.scss
  web/apps/labelstudio/src/pages/Settings/StorageSettings/StorageSet.jsx
Labels: feat

#7879 docs: fix mobile menu button color
  docs/themes/v2/source/css/styles.css
Labels: docs

#7883 docs: add blueprint buttons to templates
  docs/source/guide/release_notes.md
  docs/source/templates/generative-supervised-llm.md
  docs/source/templates/image_bbox.md
  docs/source/templates/image_classification.md
  docs/source/templates/image_keypoints.md
  docs/source/templates/image_polygons.md
  docs/source/templates/image_segmentation.md
  docs/source/templates/multi-page-document-annotation.md
  docs/source/templates/named_entity.md
  docs/source/templates/optical_character_recognition.md
  docs/source/templates/video_object_detector.md
Labels: docs
