Repository HumanSignal/label-studio, pull requests merged in 2025-02, with the labels that each got.

#7002 refactor: OPTIC-1621: Remove Stale Feature Flag - fflag_perf_back_lsdv_4695_update_prediction_query_to_use_direct_project_relation
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/projects/functions/__init__.py
  label_studio/projects/models.py
  label_studio/tasks/api.py
  label_studio/tasks/models.py
Labels: refactor

#7012 refactor: OPTIC-1621: Revert "Remove Stale Feature Flag - fflag_perf_back_lsdv_4695_update_prediction_query_to_use_direct_project_relation"
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/projects/functions/__init__.py
  label_studio/projects/models.py
  label_studio/tasks/api.py
  label_studio/tasks/models.py
Labels: refactor

#7014 refactor: OPTIC-1621: Remove Stale Feature Flag - fflag_perf_back_lsd…
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/projects/functions/__init__.py
  label_studio/projects/models.py
  label_studio/tasks/api.py
  label_studio/tasks/models.py
Labels: refactor

#7015 fix: LEAP-1805: revisit S3 exceptions behavior
  label_studio/core/settings/base.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/s3/utils.py
  label_studio/tests/io_storages/s3/test_utils.py
  poetry.lock
  pyproject.toml
Labels: fix

#6997 refactor: OPTIC-1557: Remove Stale Feature Flag - fflag_fix_front_lsd…
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/ViewControls.scss
  web/libs/editor/src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/integration/feature-flags.ts
Labels: refactor

#7018 fix: LEAP-1806: deprecate unused upload-example behavior
  label_studio/projects/views.py
Labels: fix

#7019 chore: set ls sdk to published version for release
  poetry.lock
  pyproject.toml
Labels: chore

#7004 fix: OPTIC-1509: Fix information exposure when tasks import failed
  label_studio/data_import/models.py
Labels: feat, fix, Confirmed

#7026 fix: make pyproject include includes into wheel too
  pyproject.toml
Labels: fix

#7023 fix: LEAP-1815: Fix initial image tool selection logic
  web/libs/editor/src/mixins/Tool.js
  web/libs/editor/src/tools/Manager.js
  web/libs/editor/tests/integration/data/image_segmentation/initial_tool.ts
  web/libs/editor/tests/integration/e2e/image_segmentation/initial_tool.cy.ts
Labels: fix, Confirmed

#7030 refactor: OPTIC-1637: add dia old ff to stale
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#7033 fix: LEAP-1818: try to fix failing failure callback
  label_studio/data_export/api.py
Labels: fix

#7017 fix: LEAP-1742: Update description for Sequential sampling method
  web/apps/labelstudio/src/pages/Settings/GeneralSettings.jsx
Labels: fix

#7027 fix: OPTIC-1608: Seeking video frame by frame sometimes produces duplicated or skipped frames visually
  web/libs/editor/public/files/fps_24_frames_24_video.webm
  web/libs/editor/src/components/VideoCanvas/VideoCanvas.tsx
  web/libs/editor/src/tags/object/Video/Video.js
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/integration/e2e/video/frame_seeking.cy.ts
  web/libs/editor/tests/integration/e2e/video/regions.cy.ts
  web/libs/frontend-test/src/helpers/LSF/VideoView.ts
Labels: fix, Confirmed

#7039 fix: LEAP-1741: Prevent comment category from overflow
  web/libs/editor/src/components/Comments/Comment/CommentForm.scss
Labels: fix, Confirmed

#7041 refactor: OPTIC-1644: Remove another set of FF
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#7060 chore: Cherrypicking fixes for 2.20.0 release
  label_studio/core/settings/base.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/s3/utils.py
  label_studio/projects/views.py
  label_studio/tests/io_storages/s3/test_utils.py
  poetry.lock
  pyproject.toml
Labels: fix, chore

#6996 feat: DIA-1839: Add JWT auth for API tokens
  label_studio/core/all_urls.json
  label_studio/core/middleware.py
  label_studio/core/settings/base.py
  label_studio/core/urls.py
  label_studio/jwt_auth/admin.py
  label_studio/jwt_auth/apps.py
  label_studio/jwt_auth/auth.py
  label_studio/jwt_auth/middleware.py
  label_studio/jwt_auth/migrations/0001_initial.py
  label_studio/jwt_auth/migrations/__init__.py
  label_studio/jwt_auth/models.py
  label_studio/jwt_auth/serializers.py
  label_studio/jwt_auth/urls.py
  label_studio/jwt_auth/views.py
  label_studio/organizations/functions.py
  label_studio/tests/jwt_auth/__init__.py
  label_studio/tests/jwt_auth/test_auth.py
  label_studio/tests/jwt_auth/test_middleware.py
  label_studio/tests/jwt_auth/test_models.py
  label_studio/tests/jwt_auth/test_views.py
  label_studio/tests/jwt_auth/utils.py
  label_studio/tests/utils.py
  poetry.lock
  pyproject.toml
Labels: feat

#7055 fix: LEAP-1661: Don't allow to review skipped annotations
  web/libs/editor/src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#7068 chore: cherry pick fixes into 2.20.1
  label_studio/core/settings/base.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/s3/utils.py
  label_studio/projects/views.py
  label_studio/tests/io_storages/s3/test_utils.py
  poetry.lock
  pyproject.toml
Labels: chore

#7067 fix: LEAP-1829: Fix "No LabelModel in NodeView" error in Sentry
  web/libs/editor/src/components/Node/Node.tsx
Labels: fix

#7073 fix: DIA-1888: Followup permission fix
  web/libs/core/src/pages/AccountSettings/atoms/index.ts
  web/libs/core/src/pages/AccountSettings/sections/PersonalJWTToken.tsx
Labels: fix

#6880 feat: OPTIC-1553: Add URL-based region visibility, hiding all but the specified region on load
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/utils/feature-flags.js
  web/libs/editor/src/stores/RegionStore.js
  web/libs/editor/tests/integration/data/outliner/hide-all.ts
  web/libs/editor/tests/integration/e2e/outliner/hide-all.cy.ts
  web/libs/frontend-test/src/helpers/LSF/Sidebar.ts
  web/webpack.config.js
Labels: feat

#7075 chore: bump twine to newer version
  poetry.lock
  pyproject.toml
Labels: chore

#6998 fix: OPTIC-1438: Extra logging in get_all_columns and reset function
  label_studio/data_manager/actions/basic.py
  label_studio/data_manager/actions/experimental.py
  label_studio/data_manager/functions.py
  label_studio/projects/api.py
  label_studio/projects/functions/utils.py
  label_studio/projects/models.py
Labels: fix

#7077 refactor: OPTIC-1678: ff clean up left overs
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/core/feature-flags/flags.json
Labels: refactor

#6615 feat: block sentry in frontend side
  label_studio/templates/base.html
  web/apps/labelstudio/src/config/Sentry.ts
Labels: feat

#7079 fix: OPTIC-1679: Sentry still triggered even when the env var is falsey
  label_studio/templates/base.html
Labels: fix

#7082 fix: IPv6 issues for nginx
  deploy/docker-entrypoint.d/common/10-configure-nginx.sh
Labels: fix

#7086 feat: OPTIC-1480: Adding env variable redirect on logout
  label_studio/core/settings/base.py
  label_studio/users/views.py
Labels: feat, Confirmed

#7101 chore: OPTIC-1561: Upgrade Django to 5.1.6
  poetry.lock
  pyproject.toml
Labels: chore

#7107 fix: DIA-1934: [FE] Popup warning is missing when user clicks 'Revoke' button on account settings page
  web/libs/core/src/pages/AccountSettings/sections/PersonalJWTToken.tsx
Labels: fix

#7113 fix: DIA-1928: [FE] User is able to create multiple tokens by multiple clicks on 'Create new token' button
  web/libs/core/src/pages/AccountSettings/sections/PersonalJWTToken.tsx
Labels: fix

#7119 chore: DIA-1935: add debug logging
  label_studio/jwt_auth/middleware.py
Labels: title needs formatting, chore

#7121 fix: OPTIC-1709: Ensure checks for feature flag enablement are done correctly
  web/apps/labelstudio/src/utils/helpers.ts
  web/apps/labelstudio/src/utils/license-flags.ts
  web/libs/core/src/lib/utils/helpers.ts
Labels: fix, Confirmed

#7084 fix: LEAP-1819: Prevent drawing actions outside the stage area
  web/libs/editor/src/mixins/DrawingTool.js
  web/libs/editor/src/tools/Brush.jsx
  web/libs/editor/src/tools/Erase.jsx
  web/libs/editor/src/tools/KeyPoint.js
  web/libs/editor/tests/integration/data/image_segmentation/stage_interactions.ts
  web/libs/editor/tests/integration/e2e/image_segmentation/stage_interactions.cy.ts
  web/libs/frontend-test/src/helpers/LSF/Hotkeys.ts
  web/libs/frontend-test/src/helpers/LSF/ImageView.ts
Labels: fix, Confirmed

#7125 fix: LEAP-1856: Fix filters not being sent to Bulk API
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/stores/Tabs/tab.js
Labels: fix

#7106 fix: DIA-1916: [FE] User is NOT able to upload profile image on new account page
  web/libs/core/src/lib/api-proxy/index.ts
  web/libs/core/src/lib/hooks/useCurrentUser.ts
  web/libs/core/src/pages/AccountSettings/sections/PersonalInfo.tsx
  web/libs/core/src/types/user.ts
  web/libs/ui/src/lib/InputFile/InputFile.tsx
Labels: fix

#7114 feat: DIA-1917: don't allow users to create multiple api keys
  label_studio/jwt_auth/views.py
  label_studio/tests/jwt_auth/test_views.py
Labels: feat

#7083 fix: LEAP-1792: Prevent empty tooltip for ControlButton
  web/libs/editor/src/components/BottomBar/Controls.tsx
Labels: fix, Confirmed

#7120 feat: OPTIC-1607: More analytics event tracking
  web/apps/labelstudio/src/pages/Organization/PeoplePage/PeoplePage.jsx
  web/apps/labelstudio/src/pages/Projects/Projects.jsx
Labels: feat

#7127 fix: OPTIC-1438: Locking summary for update before reset
  label_studio/data_import/functions.py
  label_studio/projects/models.py
Labels: fix, Confirmed

#7118 chore: Remove fflag_fix_back_leap_24_tasks_api_optimization_05092023_short
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/data_manager/api.py
Labels: chore

#7122 feat: OPTIC-1643: Copy Data Manager Quick View link to annotation or region
  web/libs/datamanager/src/sdk/lsf-sdk.js
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/editor/jest.config.js
  web/libs/editor/src/assets/icons/index.tsx
  web/libs/editor/src/assets/icons/link-relation.svg
  web/libs/editor/src/assets/icons/link.svg
  web/libs/editor/src/common/Dropdown/DropdownComponent.tsx
  web/libs/editor/src/common/Dropdown/DropdownTrigger.tsx
  web/libs/editor/src/components/AnnotationsCarousel/AnnotationButton.scss
  web/libs/editor/src/components/AnnotationsCarousel/AnnotationButton.tsx
  web/libs/editor/src/components/AnnotationsCarousel/__tests__/AnnotationButton.test.tsx
  web/libs/editor/src/components/AnnotationsCarousel/__tests__/AnnotationsCarousel.test.tsx
  web/libs/editor/src/components/App/App.jsx
  web/libs/editor/src/components/ContextMenu/ContextMenu.module.scss
  web/libs/editor/src/components/ContextMenu/ContextMenu.tsx
  web/libs/editor/src/components/ContextMenu/index.ts
  web/libs/editor/src/components/SidePanels/Components/RegionContextMenu.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionItem.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  web/libs/editor/src/components/SidePanels/OutlinerPanel/TreeView.scss
  web/libs/frontend-test/src/helpers/LSF/LabelStudio.ts
  web/libs/ui/src/lib/Toast/Toast.module.scss
Labels: feat, Confirmed

#7116 feat: OPTIC-1656: Factory boy and core factories
  Dockerfile
  docker-compose.override.example.yml
  label_studio/organizations/functions.py
  label_studio/organizations/models.py
  label_studio/organizations/tests/__init__.py
  label_studio/organizations/tests/factories.py
  label_studio/projects/tests/__init__.py
  label_studio/projects/tests/factories.py
  label_studio/projects/tests/test_api.py
  label_studio/tests/test_project.py
  label_studio/users/tests/__init__.py
  label_studio/users/tests/factories.py
  poetry.lock
  pyproject.toml
Labels: feat

#7128 fix: DIA-1935: fix JWT feature flag
  label_studio/jwt_auth/middleware.py
Labels: title needs formatting, fix

#7138 fix: DIA-1972: [FE] Updating TTL for an org doesn't seem to update the org settings
  web/apps/labelstudio/src/pages/Organization/PeoplePage/@components/auth-token-settings/index.tsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/PeoplePage.jsx
  web/libs/core/src/blocks/TokenSettingsModal/index.tsx
  web/libs/core/src/blocks/TokenSettingsModal/styles.module.scss
  web/libs/core/src/pages/AccountSettings/atoms/index.ts
  web/libs/core/src/pages/AccountSettings/types/index.ts
Labels: fix

#7135 chore: LEAP-1293: Remove fflag_feat_back_lsdv_5035_use_created_at_fro…
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/tasks/api.py
  web/libs/datamanager/src/sdk/lsf-utils.ts
  web/libs/datamanager/src/utils/feature-flags.js
Labels: chore

#7145 docs: Add example for Custom endpoint connection
  docs/source/guide/prompts_keys.md
Labels: docs

#7134 chore: LEAP-1292: Remove fflag_fix_back_lsdv_4648_annotator_filter_29…
  label_studio/data_manager/functions.py
Labels: chore

#7136 chore: LEAP-1299: Remove fflag_fix_back_lsdv_4929_limit_exports_10042…
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/data_export/api.py
Labels: chore, Confirmed
