Repository HumanSignal/label-studio, pull requests merged in 2025-05, with the labels that each got.

#7450 chore: DIA-2092: add FF
  label_studio/io_storages/base_models.py
  label_studio/io_storages/tests/test_multitask_import.py
Labels: chore, FM Stale

#7459 fix: DIA-2092: skip failing test
  label_studio/io_storages/tests/test_multitask_import.py
Labels: fix

#7448 fix: LEAP-1997: make CORS configurable via env
  deploy/default.conf
  label_studio/core/settings/base.py
  poetry.lock
  pyproject.toml
Labels: fix

#7420 fix: OPTIC-2016: Removing AntD reset to aid in UI consistency between page navigations
  web/.stylelintignore
  web/libs/editor/project.json
  web/libs/editor/public/index.html
  web/libs/editor/public/styles/main.css
  web/libs/editor/src/assets/styles/antd-no-reset.css
  web/libs/editor/src/assets/styles/global.scss
  web/libs/editor/src/standalone.js
  web/libs/editor/tests/e2e/tests/audio/audio-regions.test.js
  web/libs/editor/tests/e2e/tests/audio/audio-webaudio-decoder.test.js
  web/libs/editor/tests/e2e/tests/image.selected-region.test.js
  web/libs/editor/tests/e2e/tests/regression-tests/image-zoom-position.test.js
  web/package.json
  web/tools/extract-antd-no-reset/README.md
  web/tools/extract-antd-no-reset/extract-antd-no-reset
  web/tools/extract-antd-no-reset/extract-antd-no-reset.mjs
  web/tools/extract-antd-no-reset/package.json
  web/webpack.config.js
Labels: fix, Confirmed

#7457 fix: Resolve concurrent render warnings during audio scroll/zoom (#7456)
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
  web/libs/editor/src/lib/AudioUltra/react/index.ts
Labels: fix

#7463 chore: Allow retries on Audio Regions test suite temporarily while a fix is investigated
  web/libs/editor/tests/integration/e2e/audio/audio_regions.cy.ts
Labels: chore

#7464 fix: 7022 - docker compose postgres user error
  docker-compose.yml
Labels: fix

#7437 chore: update Minio and remove deprecated version keyword
  docker-compose.minio.yml
  docs/source/guide/storedata.md
Labels: chore

#7453 fix: LEAP-2063: LEAP-2062: No more annotations message is displayed in Review Stream when Interactive View All FF is turned ON
  web/libs/editor/src/mixins/SpanText.js
Labels: fix, Confirmed, FM Stale

#7452 feat: OPTIC-752: Filtering deleted users from DM filter
  web/libs/datamanager/src/components/CellViews/Annotators/Annotators.jsx
  web/libs/datamanager/src/components/Filters/types/List.jsx
  web/libs/datamanager/src/stores/AppStore.js
Labels: feat

#7324 feat: Add links to create issue action in GitHub
  .github/ISSUE_TEMPLATE/config.yml
Labels: feat

#7445 fix: LEAP-2065: [FE] Remove warning noise from new Select component in Spark
  web/libs/ui/src/lib/select/select.tsx
Labels: fix, Confirmed, FM Stale

#7461 feat: OPTIC-2002: Improve Organization Members endpoints performance
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/core/settings/base.py
  label_studio/io_storages/tests/factories.py
  label_studio/organizations/api.py
  label_studio/organizations/serializers.py
  label_studio/organizations/tests/factories.py
  label_studio/organizations/tests/test_api.py
  label_studio/tasks/tests/__init__.py
  label_studio/tasks/tests/factories.py
Labels: feat, FM Stale

#7470 feat: OPTIC-1970: Improve the usage of organization membership api requests on the client
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/utils/query-client.ts
  web/libs/core/src/lib/utils/feature-flags/flags.ts
  web/libs/core/src/lib/utils/feature-flags/index.ts
  web/libs/core/src/lib/utils/query-client.ts
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/utils/api-proxy/index.js
Labels: feat, Confirmed, FM Stale

#7477 fix: OPTIC-2153: UI Bug: Screen Goes Blank When Filtering by Predicted Model Version in Label Studio Projects
  web/libs/datamanager/src/components/Filters/FilterDropdown.jsx
  web/libs/datamanager/src/components/Filters/types/List.jsx
Labels: fix

#7468 fix: LEAP-2060: Dynamic choices are not displayed when Interactive View All FF is turned ON
  web/libs/editor/src/mixins/DynamicChildrenMixin.js
Labels: fix, Confirmed

#7481 fix: OPTIC-1916: Filter Tag is Not Working on Label Studio
  web/libs/editor/src/tags/control/Choice/Choice.scss
Labels: fix, Confirmed, FM Stale

#7472 fix: OPTIC-2120: LSO: All Projects navigation bar is transparent
  web/apps/labelstudio/src/pages/Projects/Projects.scss
Labels: fix, Confirmed

#7479 fix: OPTIC-2157: Actions Menu Disappears at High Browser Zoom Levels
  web/libs/core/src/lib/utils/dom.ts
  web/libs/datamanager/src/components/Common/Dropdown/DropdownComponent.jsx
Labels: fix, Confirmed, FM Stale

#7475 fix: LEAP-2056: Make sure tools added once per ToolManager
  web/libs/editor/src/tags/object/Image/Image.js
Labels: fix, Confirmed, FM Stale

#7489 fix: OPTIC-2002: Fix expensive query on memberships contributed projects
  label_studio/organizations/api.py
Labels: fix

#7491 feat: OPTIC-1658: Add searchable select as an input for Set Ground Truth action
  web/libs/datamanager/src/stores/Action.js
Labels: feat

#7488 fix: LEAP-2064: Choices on imported annotations are not displayed in View All on initial load
  web/libs/editor/src/stores/Annotation/store.js
  web/libs/editor/src/tags/control/Choice/Choice.scss
Labels: fix

#7484 fix: LEAP-2028: Fix brush cursor updating and visibility
  web/libs/editor/src/mixins/KonvaRegion.js
  web/libs/editor/src/regions/BrushRegion.jsx
  web/libs/editor/src/regions/EllipseRegion.jsx
  web/libs/editor/src/regions/KeyPointRegion.jsx
  web/libs/editor/src/regions/PolygonRegion.jsx
  web/libs/editor/src/regions/RectRegion.jsx
  web/libs/editor/src/tools/Brush.jsx
  web/libs/editor/src/tools/Erase.jsx
  web/libs/editor/src/utils/canvas.js
Labels: fix, Confirmed

#7458 feat: DIA-2202: Support imported tasks that point to different buckets
  label_studio/io_storages/README.md
  label_studio/io_storages/base_models.py
  label_studio/io_storages/functions.py
  label_studio/io_storages/s3/serializers.py
  label_studio/tasks/models.py
Labels: feat, FM Stale

#7498 chore: FIT-12: Datamanager App.jsx to App.tsx
  web/libs/datamanager/src/components/App/App.tsx
Labels: chore

#7499 chore: FIT-30: Multi select selected options shouldn't be highlighted along with having the checkboxes
  web/libs/ui/src/lib/select/select.tsx
Labels: chore

#7500 Potential fix for code scanning alert no. 792: Incomplete string escaping or encoding
  web/tools/design-tokens-converter/design-tokens-converter.mjs
Labels: title needs formatting

#7492 fix: OPTIC-2155: Info tab is not optimized for dark mode for TimeSeriesLabel with underlying Choices
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionDetails.scss
Labels: fix, FM Stale

#7490 fix: OPTIC-2152: Zoom presets option hotkeys not optimized for dark mode
  web/libs/editor/src/components/Toolbar/FlyoutMenu.scss
  web/libs/editor/src/components/Toolbar/Tool.scss
Labels: fix

#7495 chore: Add CODEOWNERS for `editor`
  .github/CODEOWNERS
Labels: chore

#7485 fix: OPTIC-2144: Toggle interpolation button is not optimized dark mode
  web/libs/ui/src/assets/icons/interpolation-add.svg
Labels: fix, Confirmed, FM Stale

#7486 chore: OPTIC-2163: Allow inclusion of all libs related frontend code for Tailwind classes
  web/libs/ui/src/tailwind.config.js
Labels: chore

#7504 fix: OPTIC-2149: Accept and Reject buttons in Quick View footer are not adapted to Dark Mode
  web/libs/editor/src/components/AnnotationTab/AutoAcceptToggle.scss
Labels: fix

#7503 fix: FIT-35: LSO: Annotated by column user pic is always faded
  web/libs/datamanager/src/components/CellViews/Annotators/Annotators.jsx
Labels: fix

#7512 fix: OPTIC-2142: Fix sticky side panels back
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  web/libs/editor/src/components/SidePanels/TabPanels/SideTabsPanels.tsx
Labels: fix, FM Stale

#7511 fix: FIT-41: Background of Prompts Beta modal is not optimized for Dark mode
  web/libs/ui/src/lib/ThemeToggle/ThemeToggle.tsx
Labels: fix

#7513 fix: OPTIC-2146: PerRegion TextArea input is barely visible in dark mode
  web/libs/editor/src/tags/control/TextArea/TextArea.scss
Labels: fix

#7514 fix: OPTIC-2145: Audio tracker line is not visible in dark mode
  web/libs/editor/src/lib/AudioUltra/Cursor/Cursor.ts
Labels: fix

#7510 chore: FIT-38: Setup code ownership for FIT
  .github/CODEOWNERS
Labels: chore

#7518 fix: FIT-42: LSO-1.18.0: Screen Goes Blank When Filtering by Predicted Model Version in Label Studio Projects
  web/libs/datamanager/src/components/Filters/types/List.jsx
Labels: fix

#7515 fix: BROS-4: Sentry adds Baggage header to presigned urls and it breaks CORS for storages
  label_studio/io_storages/proxy_api.py
Labels: fix

#7522 feat: UTC-1: Using less expensive MD5 password hasher for tests
  label_studio/tests/conftest.py
Labels: feat

#7523 ci: PLT-743: optimize pytests job
  .github/workflows/tests.yml
  poetry.lock
  pyproject.toml
Labels: ci

#7460 feat: DIA-2214: Add new Pdf object tag
  poetry.lock
  pyproject.toml
  web/libs/editor/src/tags/object/Pdf.jsx
  web/libs/editor/src/tags/object/index.js
  web/libs/editor/src/tags/visual/View.jsx
Labels: feat

#7531 chore: Update the base tailwind config to only target src directories of main libraries
  web/libs/ui/src/tailwind.config.js
Labels: chore

#7528 fix: BROS-4: Sentry adds Baggage header to presigned urls and it breaks CORS for storages. Fix Sentry.ts
  web/apps/labelstudio/src/config/Sentry.ts
Labels: fix, FM Stale

#7534 feat: ROOT-1: Add offset to storage link model to support storage link to task within file of tasks on cloud storage
  label_studio/io_storages/base_models.py
  label_studio/io_storages/migrations/0019_azureblobimportstoragelink_row_group_and_more.py
Labels: feat, FM Stale

#7542 chore: UTC-5: Using load_func for loading OrganizationFactory
  label_studio/core/settings/base.py
  label_studio/projects/tests/factories.py
Labels: chore

#7539 feat: FIT-49: Popover component initialization
  web/libs/ui/src/lib/popover/index.ts
  web/libs/ui/src/lib/popover/popover.module.scss
  web/libs/ui/src/lib/popover/popover.stories.tsx
  web/libs/ui/src/lib/popover/popover.tsx
Labels: feat

#7541 chore: FIT-34: Refactor DataManager Table out into reusable component
  web/libs/datamanager/src/components/Common/Table/Table.jsx
  web/libs/datamanager/src/components/Common/Table/TableHead/TableHead.scss
  web/libs/datamanager/src/components/Label/Label.scss
  web/libs/datamanager/src/components/MainView/DataView/Table.scss
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/auto-sizer-table/auto-sizer-table.tsx
  web/package.json
  web/yarn.lock
Labels: chore

#7383 feat: Cache Labels for Taxonomy
  label_studio/data_manager/actions/cache_labels.py
Labels: feat, fix

#7550 fix: OPTIC-2142: Fix sticky side panels back (#7512)
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  web/libs/editor/src/components/SidePanels/TabPanels/SideTabsPanels.tsx
Labels: fix

#7552 fix: UTC-12: Fix Ask AI Tour not found
  web/libs/core/src/lib/Tour/Tour.tsx
  web/libs/core/src/lib/Tour/TourProvider.tsx
Labels: fix

#7540 feat: ROOT-9: Allow reading multiple tasks from a JSON file in source cloud storage
  label_studio/data_manager/actions/remove_duplicates.py
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/localfiles/models.py
  label_studio/io_storages/redis/models.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/tests/test_multitask_import.py
  label_studio/tests/data_manager/test_api_actions.py
Labels: feat, FM Stale

#7545 feat: BROS-15: Change the AI assistant button on the top navigation to a help icon
  web/libs/ui/hooks/hooks.ts
  web/libs/ui/src/assets/icons/ai-assistant.svg
  web/libs/ui/src/assets/icons/index.ts
  web/libs/ui/src/assets/icons/sparkle.svg
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/sparkles/index.ts
  web/libs/ui/src/lib/sparkles/sparkles.module.scss
  web/libs/ui/src/lib/sparkles/sparkles.spec.tsx
  web/libs/ui/src/lib/sparkles/sparkles.stories.tsx
  web/libs/ui/src/lib/sparkles/sparkles.tsx
  web/libs/ui/src/lib/sparkles/types.ts
  web/libs/ui/src/lib/sparkles/utils.ts
Labels: feat, fix

#7557 docs: Update Video.js
  web/libs/editor/src/tags/object/Video/Video.js
Labels: docs

#7527 fix: BROS-5: Last fixes for Interactive View All
  web/libs/editor/src/mixins/ToolManagerMixin.js
  web/libs/editor/src/regions/PolygonPoint.jsx
  web/libs/editor/src/regions/TimeSeriesRegion.js
  web/libs/editor/src/regions/VideoRegion.js
  web/libs/editor/src/tags/control/Label.jsx
  web/libs/editor/src/tags/object/TimeSeries.jsx
  web/libs/editor/src/tags/visual/Collapse.jsx
  web/libs/editor/src/tools/Manager.js
  web/libs/editor/tests/integration/data/view_all/smoke.ts
  web/libs/editor/tests/integration/e2e/view_all/smoke.cy.ts
Labels: fix

#7568 docs: fix spacing in tags in case it’s an array
  docs/themes/v2/layout/templates.ejs
Labels: docs

#7569 docs: ROOT-9: Allow reading multiple tasks from a JSON file in source cloud storage
  docs/source/guide/storage.md
  docs/source/guide/tasks.md
  docs/source/guide/troubleshooting.md
Labels: docs

#7565 chore: UTC-3: [FE] Refactor Popover components in LSE
  web/libs/datamanager/src/components/CellViews/Agreement/Agreement.jsx
  web/libs/datamanager/src/components/CellViews/Agreement/Agreement.scss
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/ui/src/lib/popover/popover.module.scss
  web/libs/ui/src/lib/popover/popover.tsx
Labels: chore

#7444 fix: DIA-1435: [FE, cust-Comet] Some errors on Prompt task list are not displayed gracefully on UI
  web/libs/ui/src/lib/Tooltip/Tooltip.module.scss
  web/libs/ui/src/lib/Tooltip/Tooltip.tsx
  web/libs/ui/src/lib/Tooltip/tooltip.stories.tsx
  web/libs/ui/src/lib/button/button.module.scss
  web/libs/ui/src/lib/button/button.stories.tsx
  web/libs/ui/src/lib/button/button.tsx
Labels: fix, FM Stale

#7575 fix: BROS-31: Inconsistent load for Pdf pages
  web/libs/editor/src/regions/PolygonPoint.jsx
  web/libs/editor/src/regions/TimeSeriesRegion.js
  web/libs/editor/src/regions/VideoRegion.js
  web/libs/editor/src/tags/object/Pdf.jsx
Labels: fix

#7570 docs: Add info about video duration
  docs/source/tags/video.md
Labels: docs

#7578 docs: DOC-295: Add docs for proxy storage
  docs/source/guide/storage.md
  docs/themes/v2/source/images/storages/storage-proxy-presigned.png
  docs/themes/v2/source/images/storages/storage-proxy.png
  docs/themes/v2/source/images/storages/use-presigned-off.png
Labels: docs

#7553 chore: FIT-124: Remove feature flag fflag_fix_front_optic_1418_cache_members_manager_apis_short
  web/libs/core/src/lib/utils/feature-flags/flags.ts
  web/libs/datamanager/src/utils/api-proxy/index.js
Labels: chore

#7554 chore: FIT-122: Remove feature flag fflag_feat_front_optic_1351_use_new_projects_counts_api_short
  web/libs/core/src/lib/utils/feature-flags/flags.ts
Labels: chore

#7589 fix: FIT-66: Chatbot Model Assessment template is not optimized for dark mode
  label_studio/annotation_templates/generative-ai/chatbot-assessment/config.yml
  web/libs/editor/src/tags/control/Choice/Choice.scss
Labels: fix

#7593 docs: Update install_enterprise_k8s.md with redis username and password
  docs/source/guide/install_enterprise_k8s.md
Labels: docs

#7595 chore: FIT-14: Ensure production deployment of playground is resolvable as a subpath redirect
  web/apps/playground/project.json
  web/package.json
  web/webpack.config.js
Labels: chore

#7596 chore: FIT-14: Fix webpack build for standalone apps
  web/webpack.config.js
Labels: chore

#7598 fix: FIT-14: Playground preview panel should not be fullscreen
  web/apps/playground/src/components/PreviewPanel/PreviewPanel.tsx
Labels: fix

#7600 chore: FIT-14: Clear any old labelStudio:settings which may conflict from the old playground
  web/apps/playground/src/components/PreviewPanel/PreviewPanel.tsx
Labels: chore

#7601 fix: FIT-14: Embedded playground fixes for preparation for docs usage
  web/apps/playground/src/components/PlaygroundApp/TopBar.tsx
  web/apps/playground/src/hooks/useCopyText.ts
  web/apps/playground/src/utils/url.ts
Labels: fix

#7602 docs: Add note about dark mode availability
  docs/source/guide/release_notes/onprem/2.24.0.md
Labels: docs

#7606 fix: UTC-45: Average Agreement Score popover does not work on LSE release 2-25-0
  web/libs/datamanager/src/utils/feature-flags.js
  web/libs/editor/src/utils/feature-flags.ts
Labels: fix

#7605 feat: FIT-155: Replace the Playground in docs
  docs/source/playground/index.ejs
  docs/source/playground/template_codes.ejs
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/js/code-blocks-enhancements.js
  web/apps/playground/src/components/PlaygroundApp/PlaygroundApp.module.scss
Labels: feat

#7609 fix: FIT-155: Followup fixes to address any issues noticed in docs
  docs/source/playground/index.ejs
  docs/source/tags/brush.md
Labels: fix

#7555 feat: ROOT-11: Support reading JSONL from source cloud storages
  label_studio/core/settings/base.py
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/base_models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/gcs/utils.py
  label_studio/io_storages/localfiles/models.py
  label_studio/io_storages/redis/models.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/tests/test_multitask_import.py
  label_studio/io_storages/utils.py
  label_studio/tests/data_export.tavern.yml
  label_studio/tests/utils.py
  poetry.lock
  pyproject.toml
Labels: feat, FM Stale

#7599 chore: UTC-40: Hypertextlabels helper constructor in AnnotationFactory
  label_studio/tasks/tests/factories.py
Labels: chore

#7610 fix: FIT-155: Better handling for config encoding/decoding in docs playground
  docs/source/playground/index.ejs
  docs/themes/v2/source/js/code-blocks-enhancements.js
Labels: fix

#7611 fix: FIT-155: Launch in playground doesn't load config from URL
  docs/source/playground/index.ejs
Labels: fix

#7607 fix: BROS-8: 504 Gateway Timeout when Fetching Tasks via API using Filters Involving "Updated at"
  label_studio/tasks/migrations/0054_add_brin_index_updated_at.py
  label_studio/tasks/models.py
Labels: fix

#7614 fix: FIT-155: Improve playground inline preview styles within docs
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/js/code-blocks-enhancements.js
  web/apps/playground/src/atoms/configAtoms.ts
  web/apps/playground/src/components/PlaygroundApp/PlaygroundApp.tsx
  web/apps/playground/src/components/PreviewPanel/PreviewPanel.tsx
Labels: fix

#7603 chore: UTC-44: ProjectFactory has is_published=True as default
  label_studio/projects/tests/factories.py
Labels: chore, FM Stale

#7597 docs: ROOT-11: Support reading JSONL from source cloud storages
  docs/source/guide/storage.md
  docs/source/guide/tasks.md
  docs/source/guide/troubleshooting.md
Labels: docs

#7617 docs: DOC-296: Separate bulk labeling docs
  docs/source/guide/label_studio_compare.md
  docs/source/guide/labeling.md
  docs/source/guide/labeling_bulk.md
  docs/source/guide/release_notes/onprem/2.21.0.md
Labels: docs

#7624 fix: FIT-153: LSO - deleting a project causes us to not be able to scroll on projects page after redirection
  web/apps/labelstudio/src/components/Modal/ModalPopup.jsx
Labels: fix

#7623 fix: FIT-136: Duration field at Info panel is not optimized for Dark mode
  web/libs/editor/src/components/SidePanels/DetailsPanel/TimelineRegionEditor.module.scss
Labels: fix

#7537 docs: DOC-294: Add info about KeyPointLabel support for COCO/YOLO
  docs/source/guide/export.md
  docs/themes/v2/source/images/import-export/keypoints.png
Labels: docs

#7618 fix: BROS-8: Async migration for updated_at index
  .cursor/rules/async_migrations.mdc
  label_studio/tasks/migrations/0054_add_brin_index_updated_at.py
  label_studio/tasks/models.py
Labels: fix

#7632 fix: ROOT-17: User can not export COCO for KeypointLabels
  poetry.lock
  pyproject.toml
Labels: fix

#7648 fix: UTC-56: Centific UI Issue: Whitelabeling on Accounts / Settings Page
  web/libs/app-common/src/pages/AccountSettings/sections/EmailPreferences.tsx
Labels: fix

#7653 docs: Fix Google WIF docs
  docs/source/guide/storage.md
  docs/themes/v2/source/images/storages/gcs-grant-access.png
Labels: docs

#7662 fix: BROS-38: Fix sentry issue (i.map is not a function) +1 more
  web/libs/datamanager/src/sdk/comments-sdk.js
  web/libs/editor/src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
Labels: fix

#7583 fix: Add activeLabelKey to generate unique key for selected labels
  web/libs/editor/src/tags/object/AudioUltra/model.js
Labels: fix
