Repository HumanSignal/label-studio, pull requests merged in 2025-01, with the labels that each got.

#6837 docs: Update citation section in README.md
  README.md
Labels: docs

#6808 feat: OPTIC-1367: Find opportunities for property cache
  label_studio/core/mixins.py
  label_studio/data_import/models.py
  label_studio/organizations/api.py
  label_studio/organizations/mixins.py
  label_studio/organizations/models.py
  label_studio/projects/api.py
  label_studio/tasks/api.py
  label_studio/users/models.py
Labels: feat

#6723 feat: OPTIC-1332: componetize Toggle and Label components
  web/apps/labelstudio/src/components/Form/Elements/Label/Label.jsx
  web/apps/labelstudio/src/components/Form/Elements/Toggle/Toggle.jsx
  web/apps/labelstudio/src/components/Form/Elements/Toggle/Toggle.scss
  web/apps/labelstudio/src/components/Form/Elements/ToggleRight/ToggleRight.jsx
  web/apps/labelstudio/src/components/Form/Elements/ToggleRight/ToggleRight.scss
  web/apps/labelstudio/src/components/Form/Elements/index.ts
  web/apps/labelstudio/src/pages/ExportPage/ExportPage.jsx
  web/apps/labelstudio/src/pages/WebhookPage/WebhookList.jsx
  web/libs/datamanager/src/components/Common/Form/Elements/Label/Label.jsx
  web/libs/datamanager/src/components/Common/Form/Elements/Toggle/Toggle.jsx
  web/libs/datamanager/src/components/Label/Label.jsx
  web/libs/editor/src/common/Toggle/Toggle.jsx
  web/libs/editor/src/common/Toggle/Toggle.scss
  web/libs/editor/src/components/AnnotationTab/AutoAcceptToggle.jsx
  web/libs/editor/src/components/AnnotationTab/DynamicPreannotationsToggle.jsx
  web/libs/editor/src/components/Settings/Settings.jsx
  web/libs/editor/src/tags/object/Paragraphs/HtxParagraphs.jsx
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/label/label.module.scss
  web/libs/ui/src/lib/label/label.tsx
  web/libs/ui/src/lib/toggle/toggle.module.scss
  web/libs/ui/src/lib/toggle/toggle.tsx
Labels: feat, Confirmed

#6796 chore: LEAP-1700: bump pyredis and fakeredis
  label_studio/core/utils/manifest_assets.py
  poetry.lock
  pyproject.toml
Labels: chore

#6824 chore: OPTIC-1337: Update Tooltips #2
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore

#6813 fix: OPTIC-1472: Next parameter isn't being set on /user/login after failed auth
  label_studio/core/settings/base.py
  label_studio/users/templates/users/new-ui/user_login.html
  label_studio/users/templates/users/new-ui/user_signup.html
  label_studio/users/templates/users/user_login.html
  label_studio/users/templates/users/user_signup.html
  label_studio/users/views.py
Labels: fix, Confirmed

#6858 fix: LEAP-1765: upgrade django rq to fix admin page
  label_studio/core/all_urls.json
  label_studio/tests/test_endpoints.py
  poetry.lock
  pyproject.toml
Labels: fix

#6864 feat: beg-9: Updating Makefile and docker-compose.yml to latest syntax
  Makefile
  docker-compose.yml
Labels: feat

#6873 chore: Update liveContent.json
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore

#6874 chore: Update liveContent.json
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore

#6503 feat: OPTIC-1197: rearrange data manager tabs and toolbar
  web/libs/datamanager/src/components/App/App.scss
  web/libs/datamanager/src/components/Common/RadioGroup/RadioGroup.scss
  web/libs/datamanager/src/components/Common/Resizer/Resizer.scss
  web/libs/datamanager/src/components/Common/Tabs/Tabs.scss
  web/libs/datamanager/src/components/DataManager/DataManager.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/OrderButton.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/RefreshButton.jsx
  web/libs/datamanager/src/components/DataManager/Toolbar/instruments.jsx
  web/libs/datamanager/src/components/MainView/DataView/Table.scss
Labels: feat, Confirmed

#6856 fix: OPTIC-1490: Safely reference content_type of the response so it does not error
  label_studio/core/utils/contextlog.py
Labels: fix, Confirmed

#6877 refactor: LEAP-1320: Remove Stale Feature Flag - ff_front_dev_2290_draft_in_annotation_history_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/CurrentEntity/AnnotationHistory.tsx
  web/libs/editor/src/components/CurrentEntity/CurrentEntity.jsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/frontend-test/src/feature-flags.ts
  web/libs/frontend-test/src/helpers/LSF/Relations.ts
Labels: refactor

#6879 refactor: OPTIC-1501: remove a collection of ff
  label_studio/core/feature_flags/stale_feature_flags.py
  web/apps/labelstudio/src/pages/Projects/Projects.jsx
  web/apps/labelstudio/src/utils/feature-flags.ts
  web/libs/editor/src/regions/PolygonPoint.jsx
  web/libs/editor/src/tags/control/Label.jsx
  web/libs/editor/src/tags/control/TextArea/TextArea.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/tests/shortcuts.test.js
  web/libs/editor/tests/e2e/tests/sync/multiple-audio.test.js
  web/libs/editor/tests/e2e/tests/unfinished-polygons.test.js
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor

#6878 refactor: OPTIC-1506: Remove Stale Feature Flag - fflag_fix_front_dev_3350_restrict_drawing_area_short
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/core/settings/videosettings.ts
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/frontend-test/src/feature-flags.ts
Labels: Confirmed, refactor

#6884 chore: remove unsupported version of python from test matrix
  .github/workflows/tests.yml
Labels: chore

#6821 feat: LEAP-1720: distinguish annotations created using Bulk Labeling
  label_studio/tasks/migrations/0053_annotation_bulk_created.py
  label_studio/tasks/models.py
Labels: feat, Confirmed

#6857 feat: LEAP-1753: Add shortcut for toggling bulk sidebar minimization
  web/libs/datamanager/src/sdk/keymap.ts
Labels: feat, Confirmed

#6875 fix: LEAP-1708: improve styling for relation overlay
  web/libs/editor/src/components/InteractiveOverlays/RelationsOverlay.jsx
  web/libs/editor/src/components/InteractiveOverlays/RelationsOverlay.module.scss
Labels: fix, Confirmed

#6882 refactor: OPTIC-1510: remove a batch of ff
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/io_storages/functions.py
  label_studio/projects/functions/next_task.py
  web/libs/editor/src/components/Taxonomy/Taxonomy.module.scss
  web/libs/editor/src/components/Taxonomy/Taxonomy.tsx
  web/libs/editor/src/components/TreeStructure/TreeStructure.tsx
  web/libs/editor/src/core/Hotkey.ts
  web/libs/editor/src/regions/TextAreaRegion.jsx
  web/libs/editor/src/tags/control/TextArea/TextArea.jsx
  web/libs/editor/src/tags/control/TextArea/TextAreaRegionView.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/setup/feature-flags.js
  web/libs/editor/tests/e2e/tests/regression-tests/hotkey.test.js
  web/libs/editor/tests/e2e/tests/taxonomy.test.js
  web/libs/frontend-test/src/feature-flags.ts
Labels: refactor

#6892 refactor: OPTIC-1518: remove a batch of ff
  label_studio/core/feature_flags/stale_feature_flags.py
  web/libs/editor/src/components/ImageView/ImageView.jsx
  web/libs/editor/src/mixins/KonvaRegion.js
  web/libs/editor/src/regions/AliveRegion.tsx
  web/libs/editor/src/regions/VideoRegion.js
  web/libs/editor/src/tags/control/Taxonomy/Taxonomy.jsx
  web/libs/editor/src/tags/object/TimeSeries/Channel.jsx
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/setup/feature-flags.js
  web/libs/editor/tests/integration/feature-flags.ts
Labels: refactor

#6897 fix: DIA-1803: Stop using deprecated utcnow
  label_studio/core/utils/common.py
  label_studio/io_storages/azure_blob/models.py
Labels: fix

#6844 feat: OPTIC-1417: Improve projects list API usage with frontend query cache.
  web/libs/datamanager/src/components/DataManager/Toolbar/ActionsButton.jsx
Labels: feat, Confirmed

#6904 ci: PLT-628: Update poetry lock
  poetry.lock
  pyproject.toml
Labels: ci

#6909 fix: LEAP-1790: Make migration adding bulk_created field nullable
  label_studio/tasks/migrations/0053_annotation_bulk_created.py
  label_studio/tasks/models.py
Labels: fix

#6829 feat: OPTIC-1378: Track login / signup with GA client id
  label_studio/users/templates/users/new-ui/user_base.html
  label_studio/users/templates/users/new-ui/user_login.html
  label_studio/users/templates/users/new-ui/user_signup.html
  label_studio/users/templates/users/new-ui/user_tips.html
Labels: feat, Confirmed

#6787 feat: LEAP-1356: Add custom button props
  web/libs/datamanager/src/components/Common/Table/TableRow/TableRow.jsx
  web/libs/datamanager/src/components/Common/Tabs/Tabs.jsx
  web/libs/datamanager/src/components/Common/Tabs/TabsMenu.jsx
  web/libs/editor/src/components/BottomBar/Controls.tsx
  web/libs/editor/src/stores/CustomButton.ts
Labels: feat, Confirmed

#6867 fix: LEAP-1731: Bulk annotation follow-ups
  web/libs/datamanager/src/components/Common/Modal/ModalPopup.jsx
  web/libs/datamanager/src/components/MainView/GridView/GridPreview.tsx
  web/libs/datamanager/src/components/MainView/GridView/GridView.jsx
  web/libs/datamanager/src/components/MainView/GridView/ImagePreview.tsx
Labels: fix, Confirmed

#6905 fix: LEAP-1713: Enhance CSRF Token Security
  label_studio/core/settings/base.py
Labels: fix

#6912 ci: PLT-628: Update pyproject.toml
  .github/workflows/build_pypi.yml
  .github/workflows/release-set-version.yml
  poetry.lock
  pyproject.toml
  web/release.js
Labels: ci

#6916 docs: Minor format changes for image captioning example
  docs/source/guide/prompts_examples.md
  docs/source/guide/prompts_overview.md
Labels: docs

#6865 feat: DIA-1715: VertexAI Gemini model support
  label_studio/ml_model_providers/migrations/0006_modelproviderconnection_google_application_credentials_and_more.py
  label_studio/ml_model_providers/models.py
  label_studio/ml_models/migrations/0013_alter_thirdpartymodelversion_provider.py
Labels: feat

#6925 fix: OPTIC-1438: Extra logging on summary column calculation
  label_studio/projects/models.py
Labels: fix

#6919 feat: LEAP-1774: exclude starter cloud accounts from bulk labeling feature
  web/libs/editor/src/components/App/App.jsx
  web/libs/editor/src/components/BottomBar/Actions.jsx
  web/libs/editor/src/components/TopBar/Actions.jsx
  web/libs/editor/src/components/TopBar/TopBar.jsx
  web/libs/editor/src/core/Tree.tsx
  web/libs/editor/src/tags/visual/Collapse.jsx
  web/libs/editor/src/utils/billing.ts
  web/libs/editor/src/utils/feature-flags.ts
Labels: feat

#6913 chore: OPTIC-1492 Update README.md
  README.md
Labels: chore

#6899 chore: OPTIC-1337: Update Tooltips #3
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore

#6926 chore: LEAP-1743: Upgrade cross-spawn dependency versions
  web/package.json
  web/yarn.lock
Labels: chore, Confirmed

#6928 chore: LEAP-1719: update path-to-regexp to version 0.1.12
  web/libs/editor/tests/e2e/package.json
  web/libs/editor/tests/e2e/yarn.lock
Labels: chore, Confirmed

#6927 chore: LEAP-1717: update path-to-regexp to version 0.1.12
  web/package.json
  web/yarn.lock
Labels: chore, Confirmed

#6938 docs: DIA-1814: Add bucket IP filtering
  docs/source/guide/storage.md
Labels: docs

#6918 feat: DIA-1815: Add conditional dependencies in product tour
  label_studio/users/product_tours/serializers.py
  web/libs/core/src/lib/Tour/TourProvider.tsx
Labels: feat

#6948 refactor: OPTIC-1555: cleanup FF
  label_studio/core/feature_flags/stale_feature_flags.py
  web/apps/labelstudio/src/utils/feature-flags.ts
Labels: refactor

#6870 feat: DIA-1783: [FE] Prep work - Tailwind + shadcn cross integration in LSO + LSE
  Dockerfile.development
  web/.gitignore
  web/.stylelintrc.json
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/components/Menubar/Menubar.jsx
  web/components.json
  web/libs/storybook/.babelrc
  web/libs/storybook/.storybook/main.ts
  web/libs/storybook/.storybook/preview.scss
  web/libs/storybook/.storybook/preview.ts
  web/libs/storybook/button/button.stories.tsx
  web/libs/storybook/jest.config.ts
  web/libs/storybook/project.json
  web/libs/storybook/select/select.stories.tsx
  web/libs/storybook/tsconfig.json
  web/libs/storybook/tsconfig.lib.json
  web/libs/storybook/tsconfig.spec.json
  web/libs/storybook/tsconfig.storybook.json
  web/libs/ui/.storybook/main.ts
  web/libs/ui/.storybook/preview.scss
  web/libs/ui/.storybook/preview.ts
  web/libs/ui/README.md
  web/libs/ui/components.json
  web/libs/ui/src/shad/components/ui/button.tsx
  web/libs/ui/src/shad/components/ui/select.tsx
  web/libs/ui/src/shad/utils/utils.ts
  web/libs/ui/src/tailwind.config.js
  web/libs/ui/src/tailwind.css
  web/libs/ui/src/tokens/typography.scss
  web/package.json
  web/postcss.config.js
  web/tsconfig.base.json
  web/tsconfig.json
  web/webpack.config.js
  web/yarn.lock
Labels: feat

#6922 refactor: OPTIC-1540: Add stale ff new batch
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: Confirmed, refactor

#6955 fix: Enhance performance by prechecking task data uri scheme
  label_studio/io_storages/base_models.py
Labels: fix

#6930 feat: OPTIC-1479: Improve memory usage of Image tag
  web/libs/editor/src/tags/object/Image/ImageEntity.js
  web/libs/editor/src/utils/feature-flags.ts
Labels: feat, Confirmed

#6972 feat: OPTIC-1537: Update template images
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.scss
Labels: feat

#6945 docs: DIA-1776: add QnA synthetic data tutorial
  docs/source/guide/prompts_examples.md
  docs/themes/v2/source/images/prompts/example_enhance_prompt.png
  docs/themes/v2/source/images/prompts/example_enhance_prompt2.png
  docs/themes/v2/source/images/prompts/example_insert_comment_text.png
  docs/themes/v2/source/images/prompts/example_insert_image.png
  docs/themes/v2/source/images/prompts/example_subset.png
  docs/themes/v2/source/images/prompts/example_subset2.png
Labels: docs

#6965 feat: OPTIC-1581: Display prediction score on prediction tabs in editor
  web/libs/editor/src/components/AnnotationsCarousel/AnnotationButton.scss
  web/libs/editor/src/components/AnnotationsCarousel/AnnotationButton.tsx
  web/libs/editor/src/stores/Annotation/Annotation.js
Labels: feat

#6973 fix: OPTIC-1570: Update lodash to remove security issues
  web/package.json
  web/yarn.lock
Labels: fix

#6983 chore: DIA-1783: Revert Tailwind Integration
  Dockerfile.development
  web/.gitignore
  web/.stylelintrc.json
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/components/Menubar/Menubar.jsx
  web/components.json
  web/libs/storybook/.babelrc
  web/libs/storybook/.storybook/main.ts
  web/libs/storybook/.storybook/preview.scss
  web/libs/storybook/.storybook/preview.ts
  web/libs/storybook/button/button.stories.tsx
  web/libs/storybook/jest.config.ts
  web/libs/storybook/project.json
  web/libs/storybook/select/select.stories.tsx
  web/libs/storybook/tsconfig.json
  web/libs/storybook/tsconfig.lib.json
  web/libs/storybook/tsconfig.spec.json
  web/libs/storybook/tsconfig.storybook.json
  web/libs/ui/.storybook/main.ts
  web/libs/ui/.storybook/preview.scss
  web/libs/ui/.storybook/preview.ts
  web/libs/ui/README.md
  web/libs/ui/components.json
  web/libs/ui/src/shad/components/ui/button.tsx
  web/libs/ui/src/shad/components/ui/select.tsx
  web/libs/ui/src/shad/utils/utils.ts
  web/libs/ui/src/tailwind.config.js
  web/libs/ui/src/tailwind.css
  web/libs/ui/src/tokens/typography.scss
  web/package.json
  web/postcss.config.js
  web/tsconfig.base.json
  web/tsconfig.json
  web/webpack.config.js
  web/yarn.lock
Labels: chore

#6978 feat: LEAP-1778: better error display for paused user
  label_studio/core/utils/common.py
Labels: feat

#6967 docs: Update multi-page-document-annotation.md
  docs/source/templates/multi-page-document-annotation.md
Labels: docs

#6982 fix: OPTIC-1585: Change Annotations => Submitted Annotations to match its real meaning
  web/libs/datamanager/src/components/DataManager/DataManager.jsx
Labels: fix

#6959 chore: OPTIC-1548: Update the tooltips for Jan 28
  label_studio/users/templates/users/new-ui/user_tips.html
  web/apps/labelstudio/src/components/HeidiTips/content.ts
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore

#6954 refactor: OPTIC-1542: remove a buch of stale feature flags
  label_studio/core/feature_flags/stale_feature_flags.py
  web/apps/labelstudio/src/pages/CreateProject/Config/Preview.jsx
  web/apps/labelstudio/src/utils/feature-flags.ts
  web/libs/editor/src/mixins/DrawingTool.js
  web/libs/editor/src/mixins/SelectedModel.js
  web/libs/editor/src/stores/Annotation/store.js
  web/libs/editor/src/tags/control/Taxonomy/Taxonomy.jsx
  web/libs/editor/src/tags/object/Base.js
  web/libs/editor/src/tags/object/Image/Image.js
  web/libs/editor/src/tags/object/Paragraphs/model.js
  web/libs/editor/src/tools/Brush.jsx
  web/libs/editor/src/tools/KeyPoint.js
  web/libs/editor/src/utils/feature-flags.ts
  web/libs/editor/tests/e2e/tests/maxUsage.test.js
  web/libs/editor/tests/e2e/tests/taxonomy.test.js
  web/libs/frontend-test/src/feature-flags.ts
Labels: Confirmed, refactor

#6890 feat: DIA-1716: Google AI Studio (Gemini) support in Prompts
  label_studio/ml_model_providers/migrations/0007_alter_modelproviderconnection_provider.py
  label_studio/ml_model_providers/models.py
  label_studio/ml_models/migrations/0014_alter_thirdpartymodelversion_provider.py
  poetry.lock
  pyproject.toml
Labels: feat

#6999 docs: Add Django upgrade to 2.20 release notes
  docs/source/guide/release_notes/onprem/2.20.0.md
Labels: docs

#6989 feat: DIA-1783: Tailwind Integration
  Dockerfile.development
  web/.gitignore
  web/.stylelintrc.json
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/components/DescriptionList/DescriptionList.scss
  web/apps/labelstudio/src/components/Menubar/Menubar.jsx
  web/apps/labelstudio/src/components/Modal/ModalPopup.jsx
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.jsx
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.scss
  web/apps/labelstudio/src/pages/CreateProject/Config/TemplatesList.jsx
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.scss
  web/components.json
  web/libs/editor/src/components/ImageView/Image.scss
  web/libs/storybook/.babelrc
  web/libs/storybook/.storybook/main.ts
  web/libs/storybook/.storybook/preview.scss
  web/libs/storybook/.storybook/preview.ts
  web/libs/storybook/button/button.stories.tsx
  web/libs/storybook/jest.config.ts
  web/libs/storybook/project.json
  web/libs/storybook/select/select.stories.tsx
  web/libs/storybook/tsconfig.json
  web/libs/storybook/tsconfig.lib.json
  web/libs/storybook/tsconfig.spec.json
  web/libs/storybook/tsconfig.storybook.json
  web/libs/ui/.storybook/main.ts
  web/libs/ui/.storybook/preview.scss
  web/libs/ui/.storybook/preview.ts
  web/libs/ui/README.md
  web/libs/ui/components.json
  web/libs/ui/src/shad/components/ui/button.tsx
  web/libs/ui/src/shad/components/ui/select.tsx
  web/libs/ui/src/shad/utils/utils.ts
  web/libs/ui/src/tailwind.config.js
  web/libs/ui/src/tailwind.css
  web/libs/ui/src/tokens/typography.scss
  web/package.json
  web/postcss.config.js
  web/tsconfig.base.json
  web/tsconfig.json
  web/webpack.config.js
  web/yarn.lock
Labels: feat

#6885 feat: DIA-1794: [FE] Implement home page in LSO and LSE
  Dockerfile.development
  Makefile
  label_studio/core/templates/home/home.html
  label_studio/core/views.py
  label_studio/users/views.py
  web/.stylelintrc.json
  web/apps/labelstudio/src/app/App.jsx
  web/apps/labelstudio/src/components/Menubar/Menubar.jsx
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/apps/labelstudio/src/pages/Home/HomePage.tsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/InviteLink.tsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/PeoplePage.jsx
  web/apps/labelstudio/src/pages/index.js
  web/apps/labelstudio/src/providers/ApiProvider.d.ts
  web/apps/labelstudio/src/providers/ApiProvider.jsx
  web/apps/labelstudio/src/providers/RoutesProvider.jsx
  web/apps/labelstudio/src/services/breadrumbs.js
  web/apps/labelstudio/src/types/Project.d.ts
  web/apps/labelstudio/src/utils/feature-flags.ts
  web/apps/labelstudio/src/utils/jotai-store.ts
  web/jest.config.ts
  web/jest.preset.js
  web/libs/editor/jest.config.js
  web/libs/ui/package.json
  web/libs/ui/src/assets/icons/external.svg
  web/libs/ui/src/assets/icons/folder-add.svg
  web/libs/ui/src/assets/icons/folder.svg
  web/libs/ui/src/assets/icons/home.svg
  web/libs/ui/src/assets/icons/humansignal.svg
  web/libs/ui/src/assets/icons/index.ts
  web/libs/ui/src/assets/icons/ls-labeling.svg
  web/libs/ui/src/assets/icons/ls-review.svg
  web/libs/ui/src/assets/icons/user-add.svg
  web/libs/ui/src/index.ts
  web/libs/ui/src/lib/simple-card/index.tsx
  web/libs/ui/src/lib/space/Space.module.scss
  web/libs/ui/src/lib/space/index.tsx
  web/libs/ui/src/lib/space/space.module.scss
  web/libs/ui/src/lib/spinner/Spinner.module.scss
  web/libs/ui/src/lib/spinner/Spinner.tsx
  web/libs/ui/src/lib/spinner/spinner.module.scss
  web/libs/ui/src/lib/spinner/spinner.tsx
  web/libs/ui/src/lib/toast/toast.module.scss
  web/libs/ui/src/lib/toast/toast.tsx
  web/libs/ui/src/shad/components/ui/badge.tsx
  web/libs/ui/src/shad/components/ui/button.tsx
  web/libs/ui/src/shad/components/ui/card.tsx
  web/libs/ui/src/shad/components/ui/select.tsx
  web/libs/ui/src/shad/utils/index.ts
  web/libs/ui/src/tailwind.config.js
  web/libs/ui/src/tailwind.css
  web/libs/ui/src/typography/heading.tsx
  web/libs/ui/src/typography/index.ts
  web/libs/ui/src/typography/sub.tsx
  web/package.json
  web/tailwind.config.js
  web/tsconfig.base.json
  web/yarn.lock
Labels: feat
