Repository HumanSignal/label-studio, pull requests merged in 2025-07, with the labels that each got.

#7890 fix: prevent MST "not alive" errors by guarding async actions
  web/libs/editor/src/tags/object/TimeSeries.jsx
Labels: fix

#7847 chore: BROS-151: Codecov integration for LSF
  .github/workflows/tests-yarn-e2e.yml
  .github/workflows/tests-yarn-integration.yml
  web/libs/editor/.babelrc
  web/libs/editor/package.json
  web/libs/editor/tests/e2e/codecept.conf.js
  web/libs/editor/tests/e2e/tests/regression-tests/video-unmount.test.js
  web/package.json
  web/yarn.lock
Labels: chore

#7899 feat: BROS-155: Collect coverage for LSF cypress tests
  .github/workflows/tests-yarn-integration.yml
Labels: feat

#7911 fix: fit-255: Video settings on Labeling Interface Settings modal don't work
  web/libs/editor/src/components/Timeline/Timeline.tsx
  web/libs/editor/src/stores/SettingsStore.js
Labels: fix

#7919 docs: Fix multichannel example in timeseries.md
  docs/source/tags/timeseries.md
Labels: docs

#7784 feat: BROS-114: Global Custom Hotkeys
  label_studio/core/all_urls.json
  label_studio/templates/base.html
  label_studio/tests/test_endpoints.py
  label_studio/users/api.py
  label_studio/users/migrations/0011_user_custom_hotkeys.py
  label_studio/users/models.py
  label_studio/users/serializers.py
  label_studio/users/tests/test_hotkeys_api.py
  label_studio/users/tests/test_hotkeys_serializer.py
  label_studio/users/urls.py
  label_studio/users/views.py
  web/apps/labelstudio/src/components/Menubar/Menubar.jsx
  web/apps/labelstudio/src/components/Menubar/Menubar.scss
  web/apps/labelstudio/src/config/ApiConfig.js
  web/libs/app-common/src/pages/AccountSettings/AccountSettings.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Help.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Import.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Item.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Key.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Section.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/defaults.js
  web/libs/app-common/src/pages/AccountSettings/sections/index.tsx
  web/libs/datamanager/src/sdk/keymap.ts
  web/libs/editor/src/components/SidePanels/Components/LockButton.tsx
  web/libs/editor/src/components/SidePanels/DetailsPanel/RegionItem.tsx
  web/libs/editor/src/components/Toolbar/FlyoutMenu.jsx
  web/libs/editor/src/components/Toolbar/Tool.jsx
  web/libs/editor/src/components/Toolbar/Toolbar.jsx
  web/libs/editor/src/core/Hotkey.ts
  web/libs/editor/src/core/settings/keymap.json
  web/libs/editor/src/regions/TimeSeriesRegion.js
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/stores/AppStore.js
  web/libs/editor/src/tools/Bitmask.jsx
  web/libs/editor/src/tools/BitmaskErase.jsx
  web/libs/editor/src/tools/Brush.jsx
  web/libs/editor/src/tools/Ellipse.js
  web/libs/editor/src/tools/Erase.jsx
  web/libs/editor/src/tools/KeyPoint.js
  web/libs/editor/src/tools/MagicWand.jsx
  web/libs/editor/src/tools/Polygon.js
  web/libs/editor/src/tools/Rect.js
  web/libs/editor/src/tools/Rotate.jsx
  web/libs/editor/src/tools/Selection.js
  web/libs/editor/src/tools/Zoom.jsx
  web/libs/editor/tests/integration/e2e/video/regions.cy.ts
  web/libs/ui/src/assets/icons/hotkeys.svg
  web/libs/ui/src/assets/icons/index.ts
  web/libs/ui/src/shad/components/ui/alert.tsx
  web/libs/ui/src/shad/components/ui/card.tsx
  web/package.json
  web/yarn.lock
Labels: feat

#7918 fix: BROS-165: Add data generation for nested channels
  web/apps/playground/src/utils/generateSampleTask.ts
Labels: fix

#7922 docs: Add spectrogram parameter to Audio tag page
  docs/source/includes/tags/audio.md
  web/libs/editor/src/tags/object/Audio/model.js
Labels: docs

#7882 docs: BROS-157: Add Bitmask docs + update schema.json
  docs/source/tags/bitmask.md
  docs/source/tags/bitmasklabels.md
  web/libs/core/src/lib/utils/schema/tags.json
  web/libs/editor/src/tags/control/Bitmask.js
  web/libs/editor/src/tags/control/BitmaskLabels.jsx
  web/package.json
Labels: docs

#7928 fix: BROS-157: Update video size in the docs
  docs/source/tags/bitmask.md
  docs/source/tags/bitmasklabels.md
Labels: fix

#7930 docs: Fix bitmask tag pages
  docs/source/includes/tags/bitmask.md
  docs/source/tags/bitmask.md
  docs/source/tags/bitmasklabels.md
  docs/source/tags/brush.md
  docs/source/tags/brushlabels.md
Labels: docs

#7941 fix: BROS-123: Grid scroll
  web/libs/datamanager/src/components/DataManager/Toolbar/GridWidthButton.jsx
  web/libs/datamanager/src/components/MainView/GridView/GridView.jsx
  web/package.json
  web/yarn.lock
Labels: fix

#7936 fix: PLT-817: Limit max_page_size for projects api
  label_studio/projects/api.py
Labels: fix

#7949 fix: FIT-333: Email preference updates do not persist during clientside navigation (#7946)
  web/apps/labelstudio/src/providers/CurrentUser.d.ts
  web/libs/app-common/src/pages/AccountSettings/sections/EmailPreferences.tsx
Labels: fix

#7954 fix: BROS-171: Fix grid behavior
  web/libs/datamanager/src/components/MainView/GridView/GridView.jsx
Labels: fix

#7956 fix: BROS-172: Actually send a result in edge case for Fix+Accept
  web/libs/editor/src/stores/AppStore.js
Labels: fix

#7943 fix: FIT-360: Adapt hotkeys modal and settings screens to match app styles
  web/apps/labelstudio/src/components/Menubar/Menubar.jsx
  web/apps/labelstudio/src/components/Menubar/Menubar.scss
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Help.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Import.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Item.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Key.module.scss
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Key.tsx
  web/libs/ui/src/assets/icons/hotkeys.svg
  web/libs/ui/src/shad/components/ui/alert.tsx
  web/libs/ui/src/shad/components/ui/dialog.tsx
Labels: fix

#7867 fix: FIT-159: Storage error logs modal not optimized for dark mode
  web/apps/labelstudio/src/components/Card/Card.scss
  web/apps/labelstudio/src/pages/Settings/StorageSettings/StorageCard.jsx
  web/apps/labelstudio/src/pages/Settings/StorageSettings/StorageSummary.jsx
  web/libs/ui/src/lib/Card/Card.module.scss
  web/libs/ui/src/lib/code-block/code-block.tsx
Labels: fix, FM Stale

#7893 feat: BROS-155: Make test for Task Summary work
  web/libs/editor/src/components/TaskSummary/TaskSummary.test.tsx
  web/libs/editor/src/components/TaskSummary/__tests__/TaskSummary.test.tsx
Labels: feat

#7755 docs: Add clarification to PDF tag page
  docs/source/tags/pdf.md
Labels: docs

#7957 fix: FIT-363: Move hotkey management buttons to top of page
  web/apps/labelstudio/src/components/Modal/Modal.jsx
  web/libs/app-common/src/pages/AccountSettings/AccountSettings.tsx
  web/libs/app-common/src/pages/AccountSettings/hooks/useHotkeys.ts
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Help.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/Import.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/Hotkeys/utils.ts
Labels: fix, FM Stale

#7967 fix: FIT-375: Marking sync export endpoint as deprecated in API docs
  label_studio/data_export/api.py
Labels: fix

#7977 docs: Update API limits for SaaS
  docs/source/guide/saas.md
Labels: docs

#7997 docs: PLT-831: Update metrics role policy
  docs/source/guide/custom_metric.md
Labels: docs

#8032 fix: UTC-197: [FE] Stylus package removed from NPM registry
  web/package.json
  web/yarn.lock
Labels: fix

#8027 fix: default.conf to include server SNI
  deploy/default.conf
Labels: fix

#7999 docs: Enterprise features page
  docs/source/guide/enterprise_features.md
  docs/source/guide/ground_truths.md
  docs/source/guide/release_notes.md
  docs/themes/v2/source/images/lse-enterprise.png
Labels: docs

#7945 docs: Update docs for new global hotkeys
  docs/source/guide/hotkeys.md
  docs/source/guide/labeling.md
  docs/source/guide/labeling_bulk.md
  docs/source/guide/user_account.md
  docs/themes/v2/source/images/admin/account_settings.png
  docs/themes/v2/source/images/admin/account_settings_lse.png
  docs/themes/v2/source/images/admin/global-hotkeys.png
  docs/themes/v2/source/images/label/settings.png
Labels: docs

#8048 docs: update Prompts api keys note about whitelisting IP ranges
  docs/source/guide/prompts_keys.md
Labels: docs

#8038 fix: BROS-220: Fix resize handling in Video tag
  web/libs/core/src/hooks/useResizeObserver.ts
  web/libs/editor/src/components/Timeline/Views/Frames/Frames.tsx
  web/libs/editor/src/components/Timeline/Views/Frames/Minimap.tsx
  web/libs/editor/src/components/VideoCanvas/VideoCanvas.tsx
  web/libs/editor/src/components/VideoCanvas/hooks/useLoopRange.ts
Labels: fix

#8059 docs: Fix custom agreement examples
  docs/source/guide/custom_metric.md
Labels: docs

#8056 fix: BROS-200: Pad fractional seconds to 3 digits for consistent D3 parsing
  web/libs/editor/src/tags/object/TimeSeries.jsx
  web/libs/editor/src/tags/object/__tests__/TimeSeries.test.js
Labels: fix

#8063 fix: BROS-265: Layout of Pinned filter at Data Manager is broken (#8061)
  web/libs/datamanager/src/components/Filters/FiltersSidebar/FilterSidebar.jsx
Labels: fix

#8053 fix: BROS-253: Handle clicks outside the configuration modal
  web/libs/editor/src/components/Timeline/Controls/VideoConfigControl.module.scss
  web/libs/editor/src/components/Timeline/Controls/VideoConfigControl.scss
  web/libs/editor/src/components/Timeline/Controls/VideoConfigControl.tsx
  web/libs/editor/src/tags/object/Video/HtxVideo.jsx
  web/libs/frontend-test/src/helpers/LSF/VideoView.ts
Labels: fix

#8070 fix: BROS-42: LSO: Add Spacing between Labeling Interface title and Browse Templates button
  web/apps/labelstudio/src/pages/CreateProject/Config/Config.scss
Labels: fix

#8069 fix: PLT-840: Redis connection check
  label_studio/users/functions/last_activity.py
  label_studio/users/tests/test_redis_activity.py
Labels: fix

#8051 feat: UTC-205: Reduce the number of users fetched for the Annotators and Reviewers
  label_studio/data_manager/api.py
  label_studio/tasks/api.py
  label_studio/tests/sdk/test_tasks.py
  web/libs/datamanager/src/components/CellViews/Annotators/Annotators.jsx
  web/libs/datamanager/src/stores/AppStore.js
  web/libs/datamanager/src/stores/Assignee.js
  web/libs/datamanager/src/stores/DataStores/tasks.js
  web/libs/datamanager/src/utils/feature-flags.js
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/ui/src/lib/Userpic/Userpic.module.scss
Labels: feat, FM Stale

#8074 fix: UTC-205: Ensure all of feature changes are wrapped in the feature flag
  web/libs/datamanager/src/stores/DataStores/tasks.js
Labels: fix

#8075 fix: UTC-205: Ensure that DataManager Annotators CellView handles max display value correctly
  web/libs/datamanager/src/components/CellViews/Annotators/Annotators.jsx
Labels: fix
