Repository HumanSignal/label-studio, pull requests merged in 2025-10, with the labels that each got.

#8569 fix: BROS-495: Import CSV files with semicolon separator
  label_studio/data_import/models.py
Labels: fix

#8580 docs: Add citation info
  docs/source/guide/get_started.md
Labels: docs

#8586 fix: BROS-499: Ground truth queue for onboarding mode skipped when “Desired agreement threshold” is enabled
  label_studio/core/settings/base.py
  label_studio/data_manager/managers.py
  label_studio/projects/functions/next_task.md
  label_studio/projects/functions/next_task.py
  label_studio/projects/migrations/0031_alter_project_show_ground_truth_first.py
  label_studio/projects/models.py
  label_studio/tasks/models.py
Labels: fix

#8595 chore: OPTIC-1337 Live Tooltips update
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore
