Repository HumanSignal/label-studio, pull requests merged in 2025-04, with the labels that each got.

#7314 fix: DIA-2121: Project statistics on home page for LSO displays annotator's view rather than admin's view
  web/apps/labelstudio/src/pages/Home/HomePage.tsx
Labels: fix

#7281 feat: DIA-2075: [FE] Homepage projects list perf optimization
  web/libs/core/src/lib/utils/feature-flags/flags.ts
  web/libs/core/src/lib/utils/helpers.ts
  web/libs/ui/src/index.ts
  web/libs/ui/src/shad/components/ui/card.tsx
  web/libs/ui/src/shad/components/ui/skeleton.tsx
  web/libs/ui/src/shad/utils/index.ts
  web/libs/ui/src/shadcn.ts
  web/libs/ui/src/tailwind.config.js
Labels: feat, FM Stale

#7322 fix: DIA-1431: [FE] Storage type dropdown sometimes loads as blank (on Add/ Edit Source Storage modal)
  web/apps/labelstudio/src/pages/Settings/StorageSettings/StorageSet.jsx
  web/apps/labelstudio/src/pages/Settings/StorageSettings/hooks/useStorageCard.tsx
Labels: fix, FM Stale

#7323 fix: DIA-2122: allow all LSO users to modify JWT settings
  label_studio/core/utils/common.py
  label_studio/jwt_auth/models.py
  label_studio/tests/jwt_auth/test_models.py
Labels: fix

#7255 refactor: LEAP-1961: Remove stale FF_LSDV_4915
  label_studio/core/feature_flags/stale_feature_flags.py
  label_studio/data_import/api.py
  label_studio/tests/conftest.py
Labels: Confirmed, refactor

#7327 feat: OPTIC-1886: AskAi Joyride
  label_studio/users/product_tours/configs/show_ask_ai.yml
  web/apps/labelstudio/src/app/App.jsx
  web/libs/core/src/lib/Tour/Tour.tsx
Labels: feat, Confirmed

#7310 fix: OPTIC-1827: Fix information exposure through exception when validating S3 connection
  label_studio/io_storages/s3/serializers.py
Labels: fix, Confirmed, FM Stale

#7311 fix: DIA-2071: [BE,FE] AttributeError: 'AnonymousUser' object has no attribute 'active_organization'
  web/apps/labelstudio/src/providers/ApiProvider.tsx
  web/libs/core/src/lib/api-proxy/index.ts
  web/libs/core/src/lib/api-proxy/types.ts
Labels: fix, FM Stale

#7333 docs: DOC-289: Document GCS WIF storage connections
  docs/source/guide/storage.md
  docs/themes/v2/source/images/storages/gcs-grant-access.png
  docs/themes/v2/source/images/storages/gcs-principal.png
  docs/themes/v2/source/images/storages/gcs-project.png
Labels: docs

#7332 ci: Remove obsolete FM v1
  .github/workflows/follow-merge-upstream-repo-sync.yml
Labels: ci

#7315 feat: DIA-2067: Add Pages Processed task metric for pages used in MIG
  label_studio/projects/models.py
  label_studio/tasks/models.py
Labels: feat

#7312 fix: LEAP-1919: update origin on editing classifications results
  web/libs/editor/src/mixins/Regions.js
  web/libs/editor/src/tags/control/ClassificationBase.js
  web/libs/editor/tests/integration/data/control_tags/from-prediction.ts
  web/libs/editor/tests/integration/e2e/control_tags/from-prediction.cy.ts
  web/libs/frontend-test/src/helpers/LSF/LabelStudio.ts
  web/libs/frontend-test/src/helpers/LSF/ToolBar.ts
Labels: fix, Confirmed, FM Stale

#7349 fix: LEAP-1887: Add project color validation
  label_studio/projects/serializers.py
Labels: fix

#7303 fix: LEAP-1963: Ignore is_labeled for ground_truth tasks
  label_studio/projects/functions/next_task.py
  label_studio/tasks/models.py
Labels: fix, Confirmed, FM Stale

#7331 feat: DIA-2104: [FE] Sample task UI interactions
  web/apps/labelstudio/src/components/Button/Button.jsx
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/utils/bem.tsx
  web/libs/core/src/blocks/SampleDatasetSelect/SampleDatasetSelect.tsx
  web/libs/ui/src/lib/code-block/code-block.tsx
Labels: feat, FM Stale

#7357 feat: DIA-2163: Prompts models in django admin panel
  label_studio/core/all_urls.json
  label_studio/ml_model_providers/admin.py
  label_studio/ml_models/admin.py
Labels: feat

#7351 feat: DIA-2130: Add tracking to Sample datasets flow
  web/apps/labelstudio/src/pages/CreateProject/CreateProject.jsx
  web/libs/core/src/blocks/SampleDatasetSelect/SampleDatasetSelect.tsx
Labels: feat

#7309 feat: LEAP-1973: Adjustable spans for Text tag
  web/apps/labelstudio/jest.config.ts
  web/libs/core/src/lib/utils/feature-flags/flags.ts
  web/libs/core/src/pages/AccountSettings/sections/PersonalInfo.tsx
  web/libs/editor/src/mixins/HighlightMixin.js
  web/libs/editor/src/tags/object/RichText/RichText.scss
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/src/tags/object/RichText/view.jsx
Labels: feat, Confirmed, FM Stale

#7356 refactor: OPTIC-1942: clean up ff left overs
  label_studio/core/feature_flags/stale_feature_flags.py
Labels: refactor

#7358 feat: DIA-2149: Only sync new annotations in export sync cronjob
  label_studio/io_storages/base_models.py
Labels: feat, FM Stale

#7365 fix: OPTIC-1889: upgrade dependencies
  web/libs/editor/tests/e2e/package.json
  web/libs/editor/tests/e2e/yarn.lock
Labels: fix

#7367 chore: OPTIC-1956: Refactor all component blocks and pages from core to app-common lib
  .cursorrules/react.mdc
  .cursorrules/tailwind.mdc
  .cursorrules/typescript.mdc
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/PeoplePage.jsx
  web/apps/labelstudio/src/pages/index.js
  web/libs/app-common/.babelrc
  web/libs/app-common/README.md
  web/libs/app-common/jest.config.ts
  web/libs/app-common/package.json
  web/libs/app-common/project.json
  web/libs/app-common/src/blocks/SampleDatasetSelect/SampleDatasetSelect.tsx
  web/libs/app-common/src/blocks/TokenSettingsModal/index.tsx
  web/libs/app-common/src/blocks/TokenSettingsModal/styles.module.scss
  web/libs/app-common/src/index.ts
  web/libs/app-common/src/pages/AccountSettings/AccountSettings.module.scss
  web/libs/app-common/src/pages/AccountSettings/AccountSettings.tsx
  web/libs/app-common/src/pages/AccountSettings/atoms/index.ts
  web/libs/app-common/src/pages/AccountSettings/sections/EmailPreferences.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/MembershipInfo.module.scss
  web/libs/app-common/src/pages/AccountSettings/sections/MembershipInfo.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/PersonalAccessToken.module.scss
  web/libs/app-common/src/pages/AccountSettings/sections/PersonalAccessToken.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/PersonalInfo.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/PersonalJWTToken.module.scss
  web/libs/app-common/src/pages/AccountSettings/sections/PersonalJWTToken.tsx
  web/libs/app-common/src/pages/AccountSettings/sections/index.raw.css
  web/libs/app-common/src/pages/AccountSettings/sections/index.tsx
  web/libs/app-common/src/pages/AccountSettings/types/index.ts
  web/libs/app-common/src/pages/index.ts
  web/libs/app-common/tsconfig.json
  web/libs/app-common/tsconfig.lib.json
  web/libs/app-common/tsconfig.spec.json
  web/libs/core/src/index.ts
  web/tsconfig.base.json
Labels: chore

#7369 chore: OPTIC-1956: Update Menubar to have the proper new import of pages from app-common
  web/apps/labelstudio/src/components/Menubar/Menubar.jsx
Labels: chore

#7374 fix: LEAP-1945: [FE][lso] Fix Babel has inefficient RexExp complexity
  web/package.json
  web/yarn.lock
Labels: fix, Confirmed

#7378 chore: Update cursor rules glob matching and directory structure
  .cursor/rules/react.mdc
  .cursor/rules/tailwind.mdc
  .cursor/rules/typescript.mdc
Labels: chore

#7381 fix: DIA-2156: Fix button imports
  web/apps/labelstudio/src/pages/Home/HomePage.tsx
Labels: fix

#7386 feat: DIA-2196: Dedup JSON Preview and Sample Data FFs
  web/apps/labelstudio/src/pages/CreateProject/Import/Import.jsx
  web/libs/core/src/lib/utils/feature-flags/flags.ts
Labels: feat

#7342 feat: DIA-2148: write exports using thread pool
  label_studio/io_storages/base_models.py
Labels: feat, FM Stale

#7366 docs: Update AI Assistant page
  docs/source/guide/ask_ai.md
  docs/themes/v2/source/images/admin/ai-ask.png
  docs/themes/v2/source/images/admin/ai-project.png
  docs/themes/v2/source/images/admin/ai-settings.png
Labels: docs

#7396 docs: OPTIC-1984: awesome label studio call to action on docs
  docs/themes/v2/layout/layout.ejs
  docs/themes/v2/source/css/styles.css
Labels: docs, Confirmed

#7190 fix: CSP issue by removing `unsafe-eval` usage
  web/libs/datamanager/src/components/Common/Table/utils.js
Labels: fix

#7413 feat: DIA-2208: add flag to enable legacy tokens from cli
  docs/source/guide/start.md
  label_studio/core/argparser.py
  label_studio/core/settings/base.py
  label_studio/organizations/functions.py
  label_studio/server.py
Labels: feat

#7387 fix: LEAP-1947: Fix interactive view all FF in image tag case
  web/libs/editor/src/core/Tree.tsx
  web/libs/editor/src/core/feature-flags/flags.json
  web/libs/editor/src/mixins/Tool.js
  web/libs/editor/src/mixins/ToolManagerMixin.js
  web/libs/editor/src/stores/Annotation/Annotation.js
  web/libs/editor/src/tags/object/Image/Image.js
  web/libs/editor/src/tools/Manager.js
Labels: fix, Confirmed

#7410 feat: DIA-2206: prefetch fields in data export
  label_studio/data_export/mixins.py
Labels: feat

#7364 fix: LEAP-2009: Respect granularity when resizing NER spans
  web/libs/editor/src/tags/object/RichText/view.jsx
  web/libs/editor/src/utils/selection-tools.js
Labels: fix, Confirmed, FM Stale

#7417 feat: DIA-2206: prefetch completed_by info
  label_studio/data_export/mixins.py
Labels: feat

#7362 feat: DIA-2067: Per-task stats in Prompts
  label_studio/tasks/serializers.py
  label_studio/tests/conftest.py
Labels: feat

#7373 fix: LEAP-1983: [FE] Conditional View Visibility Fails When Based on a Choice Selected Within a Taxonomy Tag
  web/libs/editor/src/mixins/SelectedChoiceMixin.js
Labels: fix, Confirmed, FM Stale

#7422 fix: LEAP-2051: Don't allow to resize spans in readonly mode
  web/libs/editor/src/tags/object/RichText/model.js
  web/libs/editor/src/tags/object/RichText/view.jsx
  web/libs/editor/tests/integration/e2e/control_tags/classification/taxonomy-mig-per-item.cy.ts
Labels: fix, Confirmed, FM Stale

#7430 feat: LEAP-2042: [FE] Implement agreement popover component showing agreement between annotators as list
  web/libs/datamanager/src/components/CellViews/Agreement/Agreement.jsx
Labels: feat

#7434 docs: Add BrushLabels support for COCO export
  docs/source/guide/export.md
Labels: docs

#7440 fix: LEAP-2058: delete unused upload-example endpoint
  label_studio/core/all_urls.json
  label_studio/projects/urls.py
  label_studio/projects/views.py
  label_studio/tests/sample_tasks.tavern.yml
Labels: fix

#7447 fix: DIA-2092: hardcode test values to fix isolation failure
  label_studio/io_storages/tests/test_multitask_import.py
  label_studio/tests/utils.py
Labels: fix

#7442 fix: OPTIC-1982: Allow any errors to be displayed inline for external connection testing
  web/apps/labelstudio/src/components/Form/Form.jsx
  web/apps/labelstudio/src/pages/Settings/StorageSettings/StorageForm.jsx
  web/apps/labelstudio/src/providers/ApiProvider.tsx
Labels: fix, Confirmed, FM Stale
