Repository HumanSignal/label-studio, pull requests merged in 2025-09, with the labels that each got.

#8351 docs: Remove notion references from docs
  docs/package.json
  docs/scripts/notion-troubleshooting-page.js
  docs/source/guide/notion-faq.md
  docs/themes/v2/layout/notion.ejs
  docs/themes/v2/source/css/styles.css
  docs/yarn.lock
Labels: docs

#8357 fix: ROOT-94: Revert "fix: ROOT-94: remove redundant static dir from lso wheel"
  label_studio/core/static/drf-yasg/redoc/redoc.min.js
  label_studio/core/urls.py
  label_studio/core/views.py
  pyproject.toml
Labels: fix

#8358 chore: Updating resolutions to transitive dep koa to patched version
  web/package.json
  web/yarn.lock
Labels: chore

#8366 chore: Updating transitive dependency @module-federation/dts-plugin 0.18.0
  web/package.json
  web/yarn.lock
Labels: chore

#8354 fix: PLT-881: Upgrade numpy
  poetry.lock
  pyproject.toml
Labels: fix

#8371 fix: BROS-357: Org settings postfixes
  docs/source/guide/admin_user.md
  docs/source/guide/signup.md
  web/apps/labelstudio/src/pages/Home/HomePage.tsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/InviteLink.tsx
  web/apps/labelstudio/src/pages/Organization/PeoplePage/PeoplePage.jsx
  web/libs/app-common/src/pages/AccountSettings/AccountSettings.tsx
Labels: fix

#8383 docs: Add new Gemini models to support models list
  docs/source/includes/base_models.md
Labels: docs

#8398 fix: FIT-641: 'Label Tasks As Displayed' is displayed outside the Label All Tasks dropdown
  web/libs/datamanager/src/components/DataManager/Toolbar/LabelButton.jsx
Labels: fix

#8415 fix: BROS-389: Fix waveforms rendering for multi channels case
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
Labels: fix

#8464 fix: FIT-694: Import from Data Manager is NOT working when navigating via browser Back button from Settings page
  web/apps/labelstudio/src/pages/DataManager/DataManager.jsx
  web/libs/frontend-test/src/helpers/utils/media/SyncGroup.ts
Labels: fix

#8447 fix: BROS-413: Update children list for Panel tag
  web/libs/editor/src/tags/visual/Collapse.jsx
Labels: fix

#8459 chore: cherry-pick: BROS-389: Fix waveforms rendering for multi channels case (#8415)
  web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts
Labels: fix, chore

#8463 docs: UTC-289: Add docs for Agreement (Selected) column
  docs/source/guide/manage_data.md
  docs/source/guide/stats.md
  docs/themes/v2/source/images/project/agreement-selected.png
Labels: docs

#8486 fix: BROS-440: Video files does not open in Azure Blob and SPI when presigned OFF
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/azure_blob/utils.py
  label_studio/io_storages/tests/test_get_bytes_stream.py
Labels: fix

#8485 ci: ECHO-413: Remove LSO Server Dependency from E2E Workflow
  .github/workflows/tests-yarn-e2e.yml
Labels: ci

#8508 fix: ROOT-193: prevent double presigning attempt of s3 url in taxonomy
  web/apps/labelstudio/src/pages/CreateProject/Config/Preview.jsx
  web/libs/datamanager/src/sdk/lsf-sdk.js
Labels: fix

#8530 fix: BROS-446: Add recursive scan to storages (#8506)
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/gcs/utils.py
  label_studio/io_storages/localfiles/models.py
  label_studio/io_storages/migrations/0021_azureblobimportstorage_recursive_scan_and_more.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/tests/test_multitask_import.py
  label_studio/tests/data_manager/api_tasks.tavern.yml
  label_studio/tests/io_storages.tavern.yml
  label_studio/tests/io_storages_presign_proxy.tavern.yml
  label_studio/tests/sdk/legacy/test_storages.py
  label_studio/tests/sdk/test_storages.py
  label_studio/tests/utils.py
  web/libs/app-common/src/blocks/StorageProviderForm/Steps/preview-step.tsx
  web/libs/app-common/src/blocks/StorageProviderForm/atoms.ts
  web/libs/app-common/src/blocks/StorageProviderForm/hooks/useStorageForm.ts
Labels: fix

#8532 fix: BROS-446: Add recursive scan to storages (#8506)
  label_studio/io_storages/azure_blob/models.py
  label_studio/io_storages/gcs/models.py
  label_studio/io_storages/gcs/utils.py
  label_studio/io_storages/localfiles/models.py
  label_studio/io_storages/migrations/0021_azureblobimportstorage_recursive_scan_and_more.py
  label_studio/io_storages/s3/models.py
  label_studio/io_storages/tests/test_multitask_import.py
  label_studio/tests/data_manager/api_tasks.tavern.yml
  label_studio/tests/io_storages.tavern.yml
  label_studio/tests/io_storages_presign_proxy.tavern.yml
  label_studio/tests/sdk/legacy/test_storages.py
  label_studio/tests/sdk/test_storages.py
  label_studio/tests/utils.py
  web/libs/app-common/src/blocks/StorageProviderForm/Steps/preview-step.tsx
  web/libs/app-common/src/blocks/StorageProviderForm/atoms.ts
  web/libs/app-common/src/blocks/StorageProviderForm/hooks/useStorageForm.ts
Labels: fix

#8539 fix: BROS-446: Pytests
  label_studio/data_manager/actions/next_task.py
  label_studio/io_storages/tests/test_multitask_import.py
  label_studio/projects/api.py
  label_studio/tests/conftest.py
  label_studio/tests/utils.py
Labels: fix

#8545 chore: OPTIC-1337 Live Tooltips update
  web/apps/labelstudio/src/components/HeidiTips/liveContent.json
Labels: chore

#8528 docs: BROS-421: Review sampling with task limits and UI refinements
  docs/source/guide/dashboard_project.md
  docs/source/guide/project_settings_lse.md
  docs/source/guide/quality.md
  docs/source/guide/setup_project.md
  docs/themes/v2/source/css/styles.css
  docs/themes/v2/source/images/badge.svg
Labels: docs
